
if(!window.XartWebui_Splitter_Loaded){function XartWebui_SplitterPane(id){this.Id=id;this.Height=0;this.HeightProportion=0;this.Width=0;this.WidthProportion=0;this.Panes=[];}
XartWebui_SplitterPane.prototype.GetProperty=function(propName){return this[propName];};XartWebui_SplitterPane.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};function XartWebui_Splitter(id){this.Id=id;this.Panes=[];this.Loaded=false;}
XartWebui_Splitter.prototype.GetProperty=function(propName){return this[propName];};XartWebui_Splitter.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};XartWebui_Splitter.prototype.AdjustSize=function(bForce){if(!this.Loaded){return;}
var windowHeight=XartWebui_GetWindowHeight(),windowWidth=XartWebui_GetWindowWidth();if(!bForce&&this.WindowHeight==windowHeight&&this.WindowWidth==windowWidth){return;}
this.WindowHeight=windowHeight;this.WindowWidth=windowWidth;if(this.FillContainer){this.Height=XartWebui_GetAdjustedHeight(this.OuterDomObj,this.OuterDomObj.parentNode.offsetHeight);this.Width=XartWebui_GetAdjustedWidth(this.OuterDomObj,this.OuterDomObj.parentNode.offsetWidth);this.AssignPaneHeights(this.Panes,this.Height,bForce);this.AssignPaneWidths(this.Panes,this.Width,bForce);this.OuterDomObj.style.height=this.Height+"px";this.OuterDomObj.style.width=this.Width+"px";}else{if(this.FillHeight||this.FillWidth){if(this.FillHeight){this.OuterDomObj.style.display="none";this.AvailableHeight=XartWebui_GetAvailableHeight();this.OuterDomObj.style.display="";this.Height=this.AvailableHeight-this.HeightAdjustment;}else{this.Height=XartWebui_GetAdjustedHeight(this.OuterDomObj);}
if(this.Height>0){this.AssignPaneHeights(this.Panes,this.Height,bForce);this.OuterDomObj.style.height=this.Height+"px";}
if(this.FillWidth){this.Width=XartWebui_GetAdjustedWidth(this.OuterDomObj,windowWidth-this.WidthAdjustment);}else{this.Width=XartWebui_GetAdjustedWidth(this.OuterDomObj);}
if(this.Width>0){this.AssignPaneWidths(this.Panes,this.Width,bForce);this.OuterDomObj.style.width=this.Width+"px";}}else{if(bForce){if(this.OuterDomObj.style.height.indexOf("px")>0){this.Height=XartWebui_GetAdjustedHeight(this.OuterDomObj,parseInt(this.OuterDomObj.style.height));}else{this.Height=XartWebui_GetAdjustedHeight(this.OuterDomObj);}
if(this.OuterDomObj.style.width.indexOf("px")>0){this.Width=XartWebui_GetAdjustedWidth(this.OuterDomObj,parseInt(this.OuterDomObj.style.width));}else{this.Width=XartWebui_GetAdjustedWidth(this.OuterDomObj);}
if(this.Height>0){this.AssignPaneHeights(this.Panes,this.Height,bForce);this.OuterDomObj.style.height=this.Height+"px";}
if(this.Width>0){this.AssignPaneWidths(this.Panes,this.Width,bForce);this.OuterDomObj.style.width=this.Width+"px";}}}}};XartWebui_Splitter.prototype.AssignPaneHeights=function(panes,height,bForce){if(!panes.Orientation){var variableGroupHeight=height-panes.SplitterBarWidth*(panes.length-1),remainingVariableGroupHeight=variableGroupHeight;for(var qzba=0;qzba<panes.length;qzba++){var pane=panes[qzba],paneHeight=pane.Height;if(qzba==panes.length-1){paneHeight=remainingVariableGroupHeight;}else{if(pane.HeightProportion){paneHeight=Math.round(variableGroupHeight*pane.HeightProportion);}}
remainingVariableGroupHeight-=paneHeight;if(bForce||paneHeight!=pane.Height){this.SetHeight(pane,paneHeight,true,bForce);}}}else{for(var qzba=0;qzba<panes.length;qzba++){var pane=panes[qzba];if(bForce||paneHeight!=pane.Height){this.SetHeight(pane,height,true,bForce);}}}};XartWebui_Splitter.prototype.AssignPaneWidths=function(panes,width,bForce){if(panes.Orientation){var variableGroupWidth=width-panes.SplitterBarWidth*(panes.length-1),remainingVariableGroupWidth=variableGroupWidth;for(var qzba=0;qzba<panes.length;qzba++){var pane=panes[qzba],paneWidth=pane.Width;if(qzba==panes.length-1){paneWidth=remainingVariableGroupWidth;}else{if(pane.WidthProportion){paneWidth=Math.round(variableGroupWidth*pane.WidthProportion);}}
remainingVariableGroupWidth-=paneWidth;if(bForce||paneWidth!=pane.Width){this.SetWidth(pane,paneWidth,true,bForce);}}}else{for(var qzba=0;qzba<panes.length;qzba++){var pane=panes[qzba];if(bForce||paneWidth!=pane.Width){this.SetWidth(pane,width,true,bForce);}}}};XartWebui_Splitter.prototype.ChangeHeight=function(pane,heightDiff,bTriggerEvent,bTriggerSiblingEvent,bDoSibling,bForce){var qzAcc=pane.Height,qzdh=qzAcc+heightDiff;if(!bForce&&qzdh<pane.MinHeight){qzdh=pane.MinHeight;heightDiff=qzdh-qzAcc;}
var siblingPane=bDoSibling?pane.NextPane:pane.ParentGroup[pane.ParentGroup.length-1],newSiblingHeight=siblingPane.Height-heightDiff;if(!bForce&&newSiblingHeight<siblingPane.MinHeight){newSiblingHeight=siblingPane.MinHeight;heightDiff=newSiblingHeight-siblingPane.Height;qzdh=pane.Height+heightDiff;}
this.SetHeight(pane,qzdh,bTriggerEvent);this.SetHeight(siblingPane,newSiblingHeight,bTriggerSiblingEvent);return heightDiff;};XartWebui_Splitter.prototype.ChangeWidth=function(pane,widthDiff,bTriggerEvent,bTriggerSiblingEvent,bDoSibling,bForce){var oldWidth=pane.Width,qzgj=oldWidth+widthDiff;if(!bForce&&qzgj<pane.MinWidth){qzgj=pane.MinWidth;widthDiff=qzgj-oldWidth;}
var siblingPane=bDoSibling?pane.NextPane:pane.ParentGroup[pane.ParentGroup.length-1],newSiblingWidth=siblingPane.Width-widthDiff;if(!bForce&&newSiblingWidth<siblingPane.MinWidth){newSiblingWidth=siblingPane.MinWidth;widthDiff=newSiblingWidth-siblingPane.Width;qzgj=pane.Width+widthDiff;}
this.SetWidth(pane,qzgj,bTriggerEvent);this.SetWidth(siblingPane,newSiblingWidth,bTriggerSiblingEvent);return widthDiff;};XartWebui_Splitter.prototype.Collapse=function(domObj){var pane=domObj.Pane;if(pane.ParentGroup.Orientation){pane.ExpandedWidth=pane.Width;this.ChangeWidth(pane,(-1*pane.Width),false,true,this.ResizeAdjacentPane,true);}else{pane.ExpandedHeight=pane.Height;this.ChangeHeight(pane,(-1*pane.Height),false,true,this.ResizeAdjacentPane,true);}
domObj.style.display="none";pane.Collapsed=true;if(pane.ParentGroup.SplitterBarExpandImageUrl&&pane.BarDomElement.firstChild){pane.BarDomElement.firstChild.src=pane.ParentGroup.SplitterBarExpandImageUrl;}
if(pane.ParentGroup.SplitterBarCollapsedCssClass){pane.BarDomElement.className=pane.ParentGroup.SplitterBarCollapsedCssClass;}
this.RecordCollapseChange(domObj.id,true);if(this.ClientSideOnCollapse){this.ClientSideOnCollapse(domObj);}};XartWebui_Splitter.prototype.CollapsePane=function(pane){this.Collapse(pane.DomElement);};XartWebui_Splitter.prototype.Expand=function(domObj){var pane=domObj.Pane;domObj.style.display="block";if(pane.ParentGroup.Orientation){this.ChangeWidth(pane,pane.ExpandedWidth,true,true,this.ResizeAdjacentPane,true);}else{this.ChangeHeight(pane,pane.ExpandedHeight,true,true,this.ResizeAdjacentPane,true);}
pane.Collapsed=false;if(pane.ParentGroup.SplitterBarExpandImageUrl&&pane.BarDomElement.firstChild){pane.BarDomElement.firstChild.src=pane.ParentGroup.SplitterBarCollapseImageUrl;}
if(pane.ParentGroup.SplitterBarCollapsedCssClass){pane.BarDomElement.className=pane.ParentGroup.SplitterBarCssClass;}
this.RecordCollapseChange(domObj.id,false);if(this.ClientSideOnExpand){this.ClientSideOnExpand(domObj);}};XartWebui_Splitter.prototype.ExpandPane=function(pane){this.Expand(pane.DomElement);};XartWebui_Splitter.prototype.HandleBarMouseOver=function(barObj){if(barObj.Pane.Collapsed&&barObj.ParentGroup.SplitterBarCollapsedHoverCssClass){barObj.className=barObj.ParentGroup.SplitterBarCollapsedHoverCssClass;}else{barObj.className=barObj.ParentGroup.SplitterBarHoverCssClass;}};XartWebui_Splitter.prototype.HandleBarMouseOut=function(barObj){if(barObj.Pane.Collapsed&&barObj.ParentGroup.SplitterBarCollapsedCssClass){barObj.className=barObj.ParentGroup.SplitterBarCollapsedCssClass;}else{barObj.className=barObj.ParentGroup.SplitterBarCssClass;}};XartWebui_Splitter.prototype.HandleButtonMouseOver=function(buttonObj){if(buttonObj.parentNode.Pane.Collapsed&&buttonObj.parentNode.ParentGroup.SplitterBarExpandHoverImageUrl){buttonObj.src=buttonObj.parentNode.ParentGroup.SplitterBarExpandHoverImageUrl;}else{buttonObj.src=buttonObj.parentNode.ParentGroup.SplitterBarCollapseHoverImageUrl;}};XartWebui_Splitter.prototype.HandleButtonMouseOut=function(buttonObj){if(buttonObj.parentNode.Pane.Collapsed&&buttonObj.parentNode.ParentGroup.SplitterBarExpandImageUrl){buttonObj.src=buttonObj.parentNode.ParentGroup.SplitterBarExpandImageUrl;}else{buttonObj.src=buttonObj.parentNode.ParentGroup.SplitterBarCollapseImageUrl;}};XartWebui_Splitter.prototype.HandleResizeStart=function(qzim,qzgx,id,qzyx){XartWebui_CancelEvent(qzim);var domObj=document.getElementById(id);if(domObj.Pane.Collapsed){return false;}
XartWebui_Splitter_Resizing=this;XartWebui_Splitter_ResizingDirection=qzyx;XartWebui_Splitter_ResizeGripObject=qzgx;XartWebui_Splitter_ResizeLive=domObj.Pane.ParentGroup.LiveResize;XartWebui_Splitter_ResizeStep=domObj.Pane.ParentGroup.ResizeStep;this.ResizingPaneId=id;this.ResizingDirection=qzyx;XartWebui_Splitter_ResizingOffsetX=cart_browser_ie?event.offsetX:qzim.pageX-qzAfx(qzgx);XartWebui_Splitter_ResizingOffsetY=cart_browser_ie?event.offsetY:qzim.pageY-qzAfw(qzgx);if(this.ClientSideOnResizeStart&&!this.ClientSideOnResizeStart(domObj)){return false;}
var siblingPane=this.ResizeAdjacentPane?domObj.Pane.NextPane:domObj.Pane.ParentGroup[domObj.Pane.ParentGroup.length-1];if(qzyx){XartWebui_Splitter_ResizingMinX=1+qzAfx(domObj)+domObj.Pane.MinWidth+XartWebui_Splitter_ResizingOffsetX;XartWebui_Splitter_ResizingMaxX=qzAfx(domObj)+domObj.Pane.Width+siblingPane.Width-siblingPane.MinWidth-1;this.ResizingStartX=cart_browser_ie?event.clientX+(document.documentElement&&document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft):qzim.pageX;}else{XartWebui_Splitter_ResizingMinY=1+qzAfw(domObj)+domObj.Pane.MinHeight+XartWebui_Splitter_ResizingOffsetY;XartWebui_Splitter_ResizingMaxY=qzAfw(domObj)+domObj.Pane.Height+siblingPane.Height-siblingPane.MinHeight-1;this.ResizingStartY=cart_browser_ie?event.clientY+(document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop):qzim.pageY;}
if(!domObj.Pane.ParentGroup.LiveResize){XartWebui_Splitter_ResizeDragObject=document.createElement("table");XartWebui_Splitter_ResizeDragObject.cellSpacing=50;XartWebui_Splitter_ResizingOffsetX+=50;XartWebui_Splitter_ResizingOffsetY+=50;var tb=document.createElement("tbody");XartWebui_Splitter_ResizeDragObject.appendChild(tb);var tr=document.createElement("tr");tb.appendChild(tr);var td=document.createElement("td");tr.appendChild(td);var div=document.createElement("div");div.className=domObj.Pane.ParentGroup.SplitterBarActiveCssClass?domObj.Pane.ParentGroup.SplitterBarActiveCssClass:qzgx.className;div.style.width=qzgx.offsetWidth+"px";div.style.height=qzgx.offsetHeight+"px";div.style.overflow="hidden";td.appendChild(div);XartWebui_Splitter_ResizeDragObject.style.position="absolute";XartWebui_Splitter_ResizeDragObject.style.cursor=qzgx.style.cursor;XartWebui_Splitter_ResizeDragObject.style.top=(qzAfw(qzgx)-50)+"px";XartWebui_Splitter_ResizeDragObject.style.left=(qzAfx(qzgx)-50)+"px";document.body.insertBefore(XartWebui_Splitter_ResizeDragObject,document.body.firstChild);}else{XartWebui_Splitter_ResizeDragObject=null;}
document.onmousemove=XartWebui_Splitter_ResizeHandler;document.onmouseup=XartWebui_Splitter_ResizeDoneHandler;return false;};XartWebui_Splitter.prototype.HandleResizeDone=function(bLive){var domObj=document.getElementById(this.ResizingPaneId);if(this.ClientSideOnResizeEnd&&!this.ClientSideOnResizeEnd(domObj)){return false;}
if(this.ResizingDirection){if(XartWebui_Splitter_ResizingX){var widthDiff=XartWebui_Splitter_ResizingX-this.ResizingStartX;this.ChangeWidth(domObj.Pane,widthDiff,!bLive,!bLive,this.ResizeAdjacentPane);}}else{if(XartWebui_Splitter_ResizingY){var heightDiff=XartWebui_Splitter_ResizingY-this.ResizingStartY;this.ChangeHeight(domObj.Pane,heightDiff,!bLive,!bLive,this.ResizeAdjacentPane);}}};XartWebui_Splitter.prototype.HandleWindowResize=function(qzim){if(!this.Loaded){return;}
if(this.ResizeTimeout){clearTimeout(this.ResizeTimeout);}
this.ResizeTimeout=setTimeout(this.Id+".AdjustSize()",40);if(this.OldWindowResize&&this.OldWindowResize!=this.ResizeHandler){this.OldWindowResize(qzim);}};XartWebui_Splitter.prototype.Initialize=function(domElement){this.OuterDomObj=document.getElementById(this.Id+"_table");if(this.FillHeight){this.OuterDomObj.style.display="none";this.AvailableHeight=XartWebui_GetAvailableHeight()-this.HeightAdjustment;this.OuterDomObj.style.display="";this.OuterDomObj.style.height=this.AvailableHeight+"px";}
if(this.FillWidth){var screenWidth=XartWebui_GetWindowWidth(),qzoz=XartWebui_GetAdjustedWidth(this.OuterDomObj,screenWidth-this.WidthAdjustment);this.OuterDomObj.style.width=qzoz+"px";}
setTimeout(this.Id+".InitializeDelayed()",100);};XartWebui_Splitter.prototype.InitializeDelayed=function(){this.LoadPanes(this.Panes);this.Loaded=true;this.AdjustSize(true);this.OuterDomObj.style.visibility="visible";};XartWebui_Splitter.prototype.LoadPanes=function(panes){for(var qzba=0;qzba<panes.length;qzba++){var pane=panes[qzba],domObj=document.getElementById(pane.Id);if(domObj.firstChild.style.overflow=="auto"){domObj.firstChild.onscroll=XartWebui_Splitter_ScrollHandler;}
pane.ParentGroup=panes;pane.DomElement=domObj;domObj.Pane=pane;if(qzba>0){panes[qzba-1].NextPane=pane;}
var paneWidth=domObj.offsetWidth,paneHeight=domObj.offsetHeight;if(pane.Collapsed){if(panes.Orientation){pane.ExpandedWidth=parseInt(domObj.style.width);}else{pane.ExpandedHeight=parseInt(domObj.style.height);}}else{pane.Width=paneWidth;pane.Height=paneHeight;}
if(domObj.style.width.indexOf("%")>0){pane.WidthProportion=parseInt(domObj.style.width)/100;}
if(domObj.style.height.indexOf("%")>0){pane.HeightProportion=parseInt(domObj.style.height)/100;}
if(panes.Orientation&&domObj.nextSibling){pane.BarDomElement=domObj.nextSibling;pane.BarDomElement.Pane=pane;pane.BarDomElement.ParentGroup=panes;}else{if(!panes.Orientation&&domObj.parentNode){var qzgx=domObj.parentNode.nextSibling;while(qzgx&&qzgx.nodeName!="TR"){qzgx=qzgx.nextSibling;}
if(qzgx){qzgx=qzgx.firstChild;while(qzgx&&qzgx.nodeName!="TD"){qzgx=qzgx.nextSibling;}
if(qzgx){pane.BarDomElement=qzgx;pane.BarDomElement.Pane=pane;pane.BarDomElement.ParentGroup=panes;}}}}
if(pane.Panes.length>0){this.LoadPanes(pane.Panes);}}};XartWebui_Splitter.prototype.RecordCollapseChange=function(id,bCollapsed){if(!this.CollapseChangeList){this.CollapseChangeList=document.getElementById(this.Id+"_CollapseChangeList");}
var arCollapseChangeList=this.CollapseChangeList.value==""?[]:this.CollapseChangeList.value.split(";");var arNewCollapseChangeList=[];for(var qzba=0;qzba<arCollapseChangeList.length;qzba++){if(arCollapseChangeList[qzba].indexOf(id)<0){arNewCollapseChangeList[arNewCollapseChangeList.length]=arCollapseChangeList[qzba];}}
arNewCollapseChangeList[arNewCollapseChangeList.length]=id+" "+(bCollapsed?1:0);this.CollapseChangeList.value=arNewCollapseChangeList.join(";");};XartWebui_Splitter.prototype.RecordResize=function(id,height,width){if(!this.ResizeList){this.ResizeList=document.getElementById(this.Id+"_ResizeList");}
var arResizeList=this.ResizeList.value==""?[]:this.ResizeList.value.split(";");var arNewResizeList=[];for(var qzba=0;qzba<arResizeList.length;qzba++){if(arResizeList[qzba].indexOf(id)<0){arNewResizeList[arNewResizeList.length]=arResizeList[qzba];}}
arNewResizeList[arNewResizeList.length]=id+" "+height+" "+width;this.ResizeList.value=arNewResizeList.join(";");};XartWebui_Splitter.prototype.SetHeight=function(pane,height,bFireEvent,bForce){if(bForce||height!=pane.Height){var adjustedHeight=XartWebui_GetAdjustedHeight(pane.DomElement,height);if(height>0){if(adjustedHeight<0){adjustedHeight=1;}
if(height>=pane.Height){pane.DomElement.style.height=adjustedHeight+"px";}
pane.DomElement.firstChild.style.height=adjustedHeight+"px";if(height<pane.Height){pane.DomElement.style.height=adjustedHeight+"px";}}
pane.Height=height;if(pane.HeightProportion){pane.HeightProportion=height/this.Height;}
if(bFireEvent){if(pane.ClientSideOnResize){pane.ClientSideOnResize(pane.Id,pane.Height,pane.Width);}
this.RecordResize(pane.Id,pane.Height,pane.Width);if(pane.Panes.length>0){this.AssignPaneHeights(pane.Panes,adjustedHeight,true,bForce);}}}};XartWebui_Splitter.prototype.SetWidth=function(pane,width,bFireEvent,bForce){if(bForce||width!=pane.Width){var adjustedWidth=XartWebui_GetAdjustedWidth(pane.DomElement,width);if(width>0){if(adjustedWidth<0){adjustedWidth=1;}
if(width>=pane.Width){pane.DomElement.style.width=adjustedWidth+"px";}
pane.DomElement.firstChild.style.width=adjustedWidth+"px";if(width<pane.Width){pane.DomElement.style.width=adjustedWidth+"px";}}
pane.Width=width;if(pane.WidthProportion){pane.WidthProportion=width/this.Width;}
if(bFireEvent){if(pane.ClientSideOnResize){pane.ClientSideOnResize(pane.Id,pane.Height,pane.Width);}
this.RecordResize(pane.Id,pane.Height,pane.Width);if(pane.Panes.length>0){this.AssignPaneWidths(pane.Panes,adjustedWidth,true,bForce);}}}};XartWebui_Splitter.prototype.ToggleExpand=function(id){var domObj=document.getElementById(id);if(domObj.Pane.Collapsed){this.Expand(domObj);}else{this.Collapse(domObj);}};var XartWebui_Splitter_Resizing,XartWebui_Splitter_ResizeDiff,XartWebui_Splitter_ResizeDragObject,XartWebui_Splitter_ResizeGripObject,XartWebui_Splitter_ResizeLive,XartWebui_Splitter_ResizeStep,XartWebui_Splitter_ResizingDirection,XartWebui_Splitter_ResizingOffsetX,XartWebui_Splitter_ResizingOffsetY,XartWebui_Splitter_ResizingMinX,XartWebui_Splitter_ResizingMinY,XartWebui_Splitter_ResizingMaxX,XartWebui_Splitter_ResizingMaxY,XartWebui_Splitter_ResizingX,XartWebui_Splitter_ResizingY;function XartWebui_Splitter_ResizeHandler(qzim){if(XartWebui_Splitter_ResizingDirection){var qzp=cart_browser_ie?event.clientX+(document.documentElement&&document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft):qzim.pageX;if(qzp<XartWebui_Splitter_ResizingMinX){qzp=XartWebui_Splitter_ResizingMinX;}else{if(qzp>XartWebui_Splitter_ResizingMaxX){qzp=XartWebui_Splitter_ResizingMaxX;}}
if(XartWebui_Splitter_ResizeStep){if(Math.abs(qzp-XartWebui_Splitter_ResizingX)<XartWebui_Splitter_ResizeStep){qzp=XartWebui_Splitter_ResizingX;}}
if(XartWebui_Splitter_ResizeDragObject){XartWebui_Splitter_ResizeDragObject.style.left=(qzp-XartWebui_Splitter_ResizingOffsetX)+"px";}
var bDoResize=XartWebui_Splitter_ResizeLive&&XartWebui_Splitter_ResizingX!=qzp;XartWebui_Splitter_ResizingX=qzp;if(bDoResize){XartWebui_Splitter_Resizing.HandleResizeDone(true);XartWebui_Splitter_Resizing.ResizingStartX=qzp;}}else{var qzf=cart_browser_ie?event.clientY+(document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop):qzim.pageY;if(qzf<XartWebui_Splitter_ResizingMinY){qzf=XartWebui_Splitter_ResizingMinY;}else{if(qzf>XartWebui_Splitter_ResizingMaxY){qzf=XartWebui_Splitter_ResizingMaxY;}}
if(XartWebui_Splitter_ResizeStep){if(Math.abs(qzf-XartWebui_Splitter_ResizingY)<=XartWebui_Splitter_ResizeStep){qzf=XartWebui_Splitter_ResizingY;}}
if(XartWebui_Splitter_ResizeDragObject){XartWebui_Splitter_ResizeDragObject.style.top=(qzf-XartWebui_Splitter_ResizingOffsetY)+"px";}
var bDoResize=XartWebui_Splitter_ResizeLive&&XartWebui_Splitter_ResizingY!=qzf;XartWebui_Splitter_ResizingY=qzf;if(bDoResize){XartWebui_Splitter_Resizing.HandleResizeDone();XartWebui_Splitter_Resizing.ResizingStartY=qzf;}}
return false;}
function XartWebui_Splitter_ResizeDoneHandler(qzim,qzgx){qzff(XartWebui_Splitter_ResizeDragObject);XartWebui_Splitter_ResizeDragObject=null;document.onmousemove=null;document.onmouseup=null;if(!XartWebui_Splitter_ResizeLive){XartWebui_Splitter_Resizing.HandleResizeDone();}
return false;}
function XartWebui_Splitter_ScrollHandler(qzim){if(cart_browser_ie){qzim=event;}
var qzgx=qzim.target?qzim.target:qzim.srcElement;if(qzgx){}}
function XartWebui_GetAvailableHeight(){var windowHeight=XartWebui_GetWindowHeight(),qzAbm=cart_browser_ie?document.body.scrollHeight:document.body.offsetHeight;return windowHeight-qzAbm;}
function XartWebui_GetWindowHeight(){if(window.innerHeight){return window.innerHeight;}
if(document.documentElement.clientHeight){return document.documentElement.clientHeight;}
if(document.body.clientHeight){return document.body.clientHeight;}}
function XartWebui_GetWindowWidth(){if(window.innerWidth){return window.innerWidth;}
if(document.documentElement.clientWidth){return document.documentElement.clientWidth;}
if(document.body.clientWidth){return document.body.clientWidth;}}
function qzff(qzbc){if(qzbc){if(cart_browser_ie){qzbc.removeNode(true);}else{qzbc.parentNode.removeChild(qzbc);}}}
window.XartWebui_Splitter_Loaded=true;}