
if(!window.XartWebui_Callback_Loaded){window.XartWebui_Callback=function(id){this.Id=id;this.DomElement=document.getElementById(id+"_div");this.Parameter=null;};XartWebui_Callback.prototype.GetProperty=function(propName){return this[propName];};XartWebui_Callback.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};window.XartWebui_Callback.prototype.ReadData=function(qzau){return qzau.firstChild.nodeValue;};window.XartWebui_Callback.prototype.Callback=function(param){this.DomElement=document.getElementById(this.Id+"_div");if(this.Parameter!=param){this.Parameter=param;var oParamObj=document.getElementById(this.Id+"_ParamField");if(oParamObj){oParamObj.value=param;}}else{if(this.IsDownLevel){return false;}}
if(this.IsDownLevel){if(!window.CallbackPostingBack){setTimeout(this.Id+".Postback();",300);window.CallbackPostingBack=true;}
return false;}
if(this.Cache){var sContent=this.Cache[param];if(sContent){this.ProcessContent(sContent);return true;}}
if(this.CallbackInProgress){return false;}else{this.CallbackInProgress=true;}
if(this.ClientSideOnCallback){this.ClientSideOnCallback(param);}
if(this.LoadingPanelClientTemplate){this.DomElement.innerHTML=this.LoadingPanelClientTemplate;}
var url=this.CallbackPrefix,postData="";if(param instanceof Array){for(var qzba=0;qzba<param.length;qzba++){postData+=(qzba>0?"&":"")+"Cart_"+this.Id+"_Callback_Param="+encodeURIComponent(param[qzba]);}}else{if(arguments.length>1){for(var qzba=0;qzba<arguments.length;qzba++){postData+=(qzba>0?"&":"")+"Cart_"+this.Id+"_Callback_Param="+encodeURIComponent(arguments[qzba]);}}else{postData="Cart_"+this.Id+"_Callback_Param="+encodeURIComponent(param);}}
if(this.PostState){if(window.XartWebui_ClientStateControls){for(var qzba=0;qzba<XartWebui_ClientStateControls.length;qzba++){if(XartWebui_ClientStateControls[qzba].SaveData){XartWebui_ClientStateControls[qzba].SaveData();}}}
var form=document.forms[0];for(var qzba=0;qzba<form.length;qzba++){var qzcg=form.elements[qzba];if(qzcg.name){var elementValue=null;if(qzcg.nodeName=="INPUT"){var inputType=qzcg.getAttribute("TYPE").toUpperCase();if(inputType=="TEXT"||inputType=="PASSWORD"||inputType=="HIDDEN"){elementValue=qzcg.value;}else{if(inputType=="CHECKBOX"||inputType=="RADIO"){if(qzcg.checked){elementValue=qzcg.value;}}}}else{if(qzcg.nodeName=="TEXTAREA"){elementValue=qzcg.value;}else{if(qzcg.nodeName=="SELECT"){if(qzcg.multiple){elementValue=[];for(var qzAde=0;qzAde<qzcg.length;qzAde++){if(qzcg.options[qzAde].selected){elementValue.push(qzcg.options[qzAde].value);}}}else{elementValue=qzcg.value;if(elementValue==""){elementValue=null;}}}}}
if(elementValue instanceof Array){for(var qzAde=0;qzAde<elementValue.length;qzAde++){postData+="&"+qzcg.name+"="+encodeURIComponent(elementValue[qzAde]);}}else{if(elementValue){postData+="&"+qzcg.name+"="+encodeURIComponent(elementValue);}}}}
if(!form.__VIEWSTATE){postData+="&__VIEWSTATE=";}
if(!form.__EVENTTARGET){postData+="&__EVENTTARGET=";}}
if(this.Debug){alert("Performing callback: "+param);}
this.DoCallback(url,postData,param);return true;};window.XartWebui_Callback.prototype.DoCallback=function(url,postData,param){var ajaxbox=this,xmlHttpRequest=false,qzzc;function qzAjj(){ajaxbox.CallbackInProgress=false;if(ajaxbox.ClientSideOnCallbackComplete){setTimeout(ajaxbox.Id+".ClientSideOnCallbackComplete()",10);}}
function qzzs(){if(qzzc.readyState&&qzzc.readyState!=4&&qzzc.readyState!="complete"){return;}
var responseText=qzzc.responseText;if(ajaxbox.Debug){if(responseText){alert("Received content:\n"+responseText);}}
if(xmlHttpRequest){qzzc=qzzc.responseXML;}
if(qzzc&&qzzc.documentElement){var arData=qzzc.documentElement,sEncodedContent=ajaxbox.ReadData(arData),sContent=sEncodedContent.replace(/\$\$\$CART_CDATA_CLOSE\$\$\$/g,"]]>");if(ajaxbox.Cache){ajaxbox.Cache[param]=sContent;}
ajaxbox.ProcessContent(sContent);}else{if(ajaxbox.ClientSideOnCallbackError){ajaxbox.ClientSideOnCallbackError();}else{alert("The data could not be loaded.");}}
qzAjj();}
if(window.XMLHttpRequest){xmlHttpRequest=true;qzzc=new XMLHttpRequest();qzzc.onreadystatechange=qzzs;qzzc.open("POST",url,true);qzzc.setRequestHeader("Content-Type","application/x-www-form-urlencoded");qzzc.send(postData);}else{if(document.implementation&&document.implementation.createDocument){qzzc=document.implementation.createDocument("","",null);qzzc.onload=qzzs;}else{if(document.all){if(window.ActiveXObject){try{qzzc=new ActiveXObject("Microsoft.XMLHTTP");qzzc.onreadystatechange=qzzs;qzzc.open("POST",url,true);qzzc.setRequestHeader("Content-Type","application/x-www-form-urlencoded");qzzc.send(postData);xmlHttpRequest=true;}
catch(ex){}}
if(qzzc==null){var qzac=this.Id+"_island",qzv=document.getElementById(qzac);if(!qzv){qzv=document.createElement("xml");qzv.id=qzac;document.body.appendChild(qzv);}
if(qzv.XMLDocument){qzzc=qzv.XMLDocument;qzzc.onreadystatechange=qzzs;}else{return false;}}}else{if(this.Postback){this.Postback();}
return false;}}}
if(!xmlHttpRequest){qzzc.async=true;try{qzzc.load(url+ajaxbox.CallbackParamDelimiter+postData);}
catch(ex){qzAjj();alert("Data not loaded: "+(ex.message?ex.message:ex));}}
return true;};window.XartWebui_Callback.prototype.GetParameter=function(){if(this.Parameter){return this.Parameter;}else{var oParamObj=document.getElementById(this.Id+"_ParamField");if(oParamObj){this.Parameter=oParamObj.value;}}
return this.Parameter;};window.XartWebui_Callback.prototype.ProcessContent=function(sContent){var qzzv="",sProcessContent=sContent.toLowerCase();while(true){var iStartIndex=sProcessContent.indexOf("<script");if(iStartIndex<0){break;}else{var iStartScriptIndex=sProcessContent.indexOf(">",iStartIndex)+1,iEndScriptIndex=sProcessContent.indexOf("</scr"+"ipt>",iStartIndex);if(iEndScriptIndex>=iStartScriptIndex){if(iEndScriptIndex==iStartScriptIndex){var iStartFileNameIndex=sProcessContent.indexOf("src=\"",iStartIndex);if(iStartFileNameIndex>0){iStartFileNameIndex+=5;var iEndFileNameIndex=sProcessContent.indexOf("\"",iStartFileNameIndex),sFileName=sContent.substring(iStartFileNameIndex,iEndFileNameIndex);if(sFileName.length>0){var scriptElement=document.createElement("script");scriptElement.setAttribute("type","text/javascript");scriptElement.setAttribute("src",sFileName);document.getElementsByTagName("head").item(0).appendChild(scriptElement);}}}
var iEndIndex=iEndScriptIndex+9;if(iEndScriptIndex>iStartScriptIndex){var sScriptBlock=sContent.substring(iStartScriptIndex,iEndScriptIndex);qzzv+=sScriptBlock+"\n";}
sContent=sContent.substring(0,iStartIndex)+sContent.substring(iEndIndex);sProcessContent=sProcessContent.substring(0,iStartIndex)+sProcessContent.substring(iEndIndex);}}}
this.DomElement.innerHTML=sContent;if(qzzv.length>0){window.eval(qzzv);}};window.XartWebui_Callback_Loaded=true;}