
var cart_calendar_calendarcontroltype_calendar=0,cart_calendar_calendarcontroltype_picker=1,cart_calendar_calendarpopuptype_none=0,cart_calendar_calendarpopuptype_custom=1,cart_calendar_calendartitletype_todaydatetext=0,cart_calendar_calendartitletype_selecteddatetext=1,cart_calendar_calendartitletype_visibledatetext=2,cart_calendar_calendartitletype_visiblerangetext=3,cart_calendar_calendartitletype_selecteddatepicker=4,cart_calendar_calendartitletype_visibledatepicker=5;function XartWebui_Calendar(calendarId){this.CalendarId=calendarId;this.CellData=new Object();}
XartWebui_Calendar.prototype.GetProperty=function(propName){return this[propName];};XartWebui_Calendar.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};XartWebui_Calendar.prototype.Render=function(){if(this.TodaysDate==null){this.TodaysDate=new Date();}
if(this.VisibleDate==null){this.VisibleDate=this.TodaysDate;}
XartWebui_Calendar_ConfineVisibleDate(this);var apparentVisibleDateInput=document.getElementById(this.CalendarId+"_apparentvisibledate");if(apparentVisibleDateInput!=null&&apparentVisibleDateInput.value==""){apparentVisibleDateInput.value=this.VisibleDate.getFullYear()+"."+(1+this.VisibleDate.getMonth());}
if(this.ControlType==cart_calendar_calendarcontroltype_calendar){if(this.AllowMonthSelection||this.AllowWeekSelection){this.SelectMonthEffectiveActiveCssClass=this.SelectMonthEffectiveHoverCssClass=this.SelectMonthEffectiveCssClass=this.SelectMonthCssClass;if(this.SelectMonthHoverCssClass!=null){this.SelectMonthEffectiveActiveCssClass=this.SelectMonthEffectiveHoverCssClass=this.SelectMonthHoverCssClass;}
if(this.SelectMonthActiveCssClass!=null){this.SelectMonthEffectiveActiveCssClass=this.SelectMonthActiveCssClass;}
this.SelectWeekEffectiveActiveCssClass=this.SelectWeekEffectiveHoverCssClass=this.SelectWeekEffectiveCssClass=this.SelectWeekCssClass;if(this.SelectWeekHoverCssClass!=null){this.SelectWeekEffectiveActiveCssClass=this.SelectWeekEffectiveHoverCssClass=this.SelectWeekHoverCssClass;}
if(this.SelectWeekActiveCssClass!=null){this.SelectWeekEffectiveActiveCssClass=this.SelectWeekActiveCssClass;}}else{this.SelectMonthEffectiveActiveCssClass=this.SelectMonthEffectiveHoverCssClass=this.SelectMonthEffectiveCssClass=null;this.SelectWeekEffectiveActiveCssClass=this.SelectWeekEffectiveHoverCssClass=this.SelectWeekEffectiveCssClass=null;}
this.NextPrevEffectiveActiveCssClass=this.NextPrevEffectiveHoverCssClass=this.NextPrevEffectiveCssClass=this.NextPrevCssClass;if(this.NextPrevHoverCssClass!=null){this.NextPrevEffectiveActiveCssClass=this.NextPrevEffectiveHoverCssClass=this.NextPrevHoverCssClass;}
if(this.NextPrevActiveCssClass!=null){this.NextPrevEffectiveActiveCssClass=this.NextPrevActiveCssClass;}
this.PickerTokens=XartWebui_Calendar_LoadTokens(this,this.CalendarTitleTokensArray);this.PickerEditableTokenIndexes=XartWebui_Calendar_EnumerateEditableTokens(this.PickerTokens);XartWebui_Calendar_CalculateVisibleDateData(this,this.VisibleDateStart);if(this.PopUp==cart_calendar_calendarpopuptype_none){if(this.CalendarPlaceHolder==null||XartWebui_IsStray(this.CalendarPlaceHolder)){this.CalendarPlaceHolder=document.getElementById(this.CalendarId+"_calendarcontents");}
if(this.IsCalendarUplevel){this.CalendarPlaceHolder.innerHTML=XartWebui_Calendar_CalendarHtml(this);}else{this.UpdateHeaderAndFooter();}}else{if(this.IsPopupUplevel){if(this.PopUpObject==null){if(window.cart_calendar_popupcontainer==null){window.cart_calendar_popupcontainer=new XartWebui_ElementContainer();}
this.PopUpContainer=window.cart_calendar_popupcontainer;this.PopUpObject=new XartWebui_PopUp();this.PopUpObject.Id=this.CalendarId+".PopUpObject";this.PopUpObject.ExpandSlideDirection=cart_slidedirection_down;this.PopUpObject.ExpandDuration=this.PopUpExpandDuration;this.PopUpObject.ExpandSlideType=this.PopUpExpandSlide;this.PopUpObject.ExpandTransition=this.PopUpExpandTransition;this.PopUpObject.ExpandTransitionCustomFilter=this.PopUpExpandTransitionCustomFilter;this.PopUpObject.CollapseSlideDirection=cart_slidedirection_up;this.PopUpObject.CollapseDuration=this.PopUpCollapseDuration;this.PopUpObject.CollapseSlideType=this.PopUpCollapseSlide;this.PopUpObject.CollapseTransition=this.PopUpCollapseTransition;this.PopUpObject.CollapseTransitionCustomFilter=this.PopUpCollapseTransitionCustomFilter;this.PopUpObject.CssClass=this.CalendarCssClass;this.PopUpObject.Contents=XartWebui_Calendar_CalendarHtml(this);this.PopUpObject.StateChangeEvent=new Function("popup",this.CalendarId+".PopUpStateChanged(popup)");if(this.PopUpExpandControlId!=null){this.PopUpObject.AlignElement=document.getElementById(this.PopUpExpandControlId);}
this.PopUpObject.ExpandOffsetX=this.PopUpExpandOffsetX;this.PopUpObject.ExpandOffsetY=this.PopUpExpandOffsetY;this.PopUpObject.qzvc=this.PopUpExpandDirection;this.PopUpObject.AlwaysInitialize=true;this.PopUpObject.Init();}else{this.PopUpObject.qzbi.innerHTML=XartWebui_Calendar_CalendarHtml(this);this.PopUpObject.qzcg=this.PopUpObject.qzbi.firstChild;}}}}
if(this.ControlType==cart_calendar_calendarcontroltype_picker){this.PickerTokens=XartWebui_Calendar_LoadTokens(this,this.PickerTokensArray);this.PickerEditableTokenIndexes=XartWebui_Calendar_EnumerateEditableTokens(this.PickerTokens);this.PickerActiveArea=this.PickerEditableTokenIndexes.length>0?0:null;this.PickerDateDecomposition=XartWebui_Calendar_DecomposeDate(this.SelectedDates.DateArray[0]);var pickerBoxes=[document.getElementById(this.CalendarId+"_picker")];pickerBoxes[0].Calendar=this;pickerBoxes[0].CalendarId=this.CalendarId;this.PickerDigitsTyped="";XartWebui_Calendar_PickerShowText(this);if(this.IsPickerUplevel){pickerBoxes[0].disabled=this.PickerDateDecomposition==null;}}};XartWebui_Calendar.prototype.Show=function(){if(this.PopUpObject==null||this.PopUpObjectShowing){return;}
var oldAlignElement=this.PopUpObject.AlignElement,oldX=this.PopUpObject.x,oldY=this.PopUpObject.y;if(arguments.length>0){switch(arguments.length){case 1:this.PopUpObject.AlignElement=arguments[0];break;case 2:this.PopUpObject.x=arguments[0];this.PopUpObject.y=arguments[1];break;}}
this.PopUpObject.Show();this.PopUpObjectShowing=true;this.DocumentMouseUpHandler=new Function("event","XartWebui_Calendar_HandleDocumentMouseUp("+this.CalendarId+",event)");XartWebui_AddEventHandler(document,"mouseup",this.DocumentMouseUpHandler);this.PopUpObject.AlignElement=oldAlignElement;this.PopUpObject.x=oldX;this.PopUpObject.y=oldY;};XartWebui_Calendar.prototype.Hide=function(){if(this.PopUpObject==null||!this.PopUpObjectShowing){return;}
this.PopUpObject.Hide(true);this.PopUpObjectShowing=false;XartWebui_RemoveEventHandler(document,"mouseup",this.DocumentMouseUpHandler);this.DocumentMouseUpHandler=null;};XartWebui_Calendar.prototype.PopUpStateChanged=function(popup){if(popup&&popup.PopUpState==cart_popupstate_collapsed){this.PopUpObjectShowing=false;delete this.PopUpCalendar;}};XartWebui_Calendar.prototype.GetSelectedDate=function(){return(this.SelectedDates.DateArray.length>0)?this.SelectedDates.DateArray[0]:null;};XartWebui_Calendar.prototype.ClearCellData=function(dates){if(dates.join==null){dates=[dates];}
for(var qzba=0;qzba<dates.length;qzba++){delete this.CellData[XartWebui_Calendar_DateToCellId(dates[qzba],0)];delete this.CellData[XartWebui_Calendar_DateToCellId(dates[qzba],1)];}};XartWebui_Calendar.prototype.ClearCellDataRange=function(startDate,endDate){var startDate=XartWebui_Calendar_GetDateOnly(startDate),endDate=XartWebui_Calendar_GetDateOnly(endDate);for(var curDate=startDate;curDate<=endDate;curDate=XartWebui_Calendar_DateAddDays(curDate,1)){delete this.CellData[XartWebui_Calendar_DateToCellId(curDate,0)];delete this.CellData[XartWebui_Calendar_DateToCellId(curDate,1)];}};XartWebui_Calendar.prototype.SetSelectedDate=function(date,force,internal){if(date==null){date=this.VisibleDate;}
if(this.ControlType==cart_calendar_calendarcontroltype_calendar){if(this.MonthsSwapInProgress){this.CalendarSetDateQueuedDate=date;this.CalendarSetDateQueuedInternal=internal;return;}
this.CalendarSetDateQueuedDate=null;this.CalendarSetDateQueuedInternal=null;var dateonly=XartWebui_Calendar_GetDateOnly(date);this.ClearCellData(dateonly);this.ClearCellData(this.SelectedDates.DateArray);this.SelectedDates.Select(dateonly,this.AllowMultipleSelection);if(this.VisibleDateStart<=dateonly&&dateonly<this.VisibleDateEnd){this.Render();}else{XartWebui_Calendar_FireClientSideOnBeforeVisibleDateChanged(this,this.AutoPostBackOnVisibleDateChanged);this.VisibleDate=dateonly;XartWebui_Calendar_ConfineVisibleDate(this);document.getElementById(this.CalendarId+"_visibledate").value=XartWebui_Calendar_DateToString(this.VisibleDate);if(this.AutoPostBackOnVisibleDateChanged){eval(this.PostBackCommand);}else{this.UpdateHeaderAndFooter();XartWebui_Calendar_FireClientSideOnVisibleDateChanged(this);var monthCount=this.MonthRows*this.MonthColumns,visibleMonthPosition=this.MonthColumns*(this.VisibleMonthRow-1)+(this.VisibleMonthColumn-1),newVisibleDateStart=new Date(this.VisibleDate.getFullYear(),this.VisibleDate.getMonth()-visibleMonthPosition,1),newVisibleDateEnd=new Date(newVisibleDateStart.getFullYear(),newVisibleDateStart.getMonth()+monthCount,1),oldVisibleDateStart=this.VisibleDateStart,oldVisibleDateEnd=this.VisibleDateEnd,swapDirection;if(newVisibleDateStart<oldVisibleDateStart){var oneMonthCountToPast=new Date(oldVisibleDateStart.getFullYear(),oldVisibleDateStart.getMonth()-monthCount,1);swapDirection=newVisibleDateStart<oneMonthCountToPast?"down":"left";}else{var oneMonthCountToFuture=new Date(oldVisibleDateStart.getFullYear(),oldVisibleDateStart.getMonth()+monthCount,1);swapDirection=oneMonthCountToFuture>=newVisibleDateStart?"right":"up";}
XartWebui_Calendar_SwapToDate(this,newVisibleDateStart,newVisibleDateEnd,swapDirection);}}}else{if(this.ControlType==cart_calendar_calendarcontroltype_picker){var newdate=XartWebui_Calendar_GetDateOnly(date),olddate=XartWebui_Calendar_RecomposeDate(this.PickerDateDecomposition);if(newdate==olddate){return false;}
var intoTheFuture=newdate>olddate,withinLimits=(intoTheFuture&&newdate<=this.MaxDate)||(!intoTheFuture&&newdate>=this.MinDate);if(!force){if(!withinLimits||this.DisabledDates.Contains(newdate)){return false;}}else{if(!withinLimits){if(newdate<this.MinDate){newdate=this.MinDate;intoTheFuture=true;}else{newdate=this.MaxDate;intoTheFuture=false;}
withinLimits=(intoTheFuture&&newdate<=this.MaxDate)||(!intoTheFuture&&newdate>=this.MinDate);}
if(withinLimits){while(withinLimits&&this.DisabledDates.Contains(newdate)){newdate=XartWebui_Calendar_DateAddDays(newdate,intoTheFuture?+1:-1);withinLimits=(intoTheFuture&&newdate<=this.MaxDate)||(!intoTheFuture&&newdate>=this.MinDate);}}
if(!withinLimits){return false;}}
this.PickerDateDecomposition=XartWebui_Calendar_DecomposeDate(newdate);var pickerBoxes=[document.getElementById(this.CalendarId+"_picker")];pickerBoxes[0].disabled=this.PickerDateDecomposition==null;this.SelectedDates.Clear();this.SelectedDates.Add(newdate);document.getElementById(this.CalendarId+"_selecteddates").value=XartWebui_Calendar_DateArrayToString(this.SelectedDates.DateArray);XartWebui_Calendar_PickerShowTextAndFocus(this);if(this.AutoPostBackOnSelectionChanged){eval(this.PostBackCommand);}else{XartWebui_Calendar_FireClientSideOnSelectionChanged(this,!internal);}
return true;}}};XartWebui_Calendar.prototype.ClearSelectedDate=function(){this.ClearCellData(this.SelectedDates.DateArray);this.SelectedDates.Clear();document.getElementById(this.CalendarId+"_selecteddates").value=XartWebui_Calendar_DateArrayToString(this.SelectedDates.DateArray);this.Render();};XartWebui_Calendar.prototype.PopulateCellData=function(cellDataArray){for(var qzba=0;qzba<cellDataArray.length;qzba++){this.CellData[cellDataArray[qzba][0]]=XartWebui_Calendar_CreateCellDataObject(cellDataArray[qzba][1]);}};XartWebui_Calendar.prototype.FilterSelectedDates=function(){for(var qzba=this.SelectedDates.DateArray.length-1;qzba>=0;qzba--){var curSelectedDate=this.SelectedDates.DateArray[qzba];if(this.DisabledDates.Contains(curSelectedDate)||curSelectedDate<this.MinDate||this.MaxDate<curSelectedDate){this.SelectedDates.Remove(curSelectedDate);}}};XartWebui_Calendar.prototype.GetPrevVisibleDate=function(){if(this.ControlType!=cart_calendar_calendarcontroltype_calendar){return null;}
if(this.VisibleDateStart<=this.MinDate){return null;}
var monthCount=this.MonthRows*this.MonthColumns,newVisibleDateStart=new Date(this.VisibleDateStart.getFullYear(),this.VisibleDateStart.getMonth()-monthCount,1);return newVisibleDateStart;};XartWebui_Calendar.prototype.GetPrevVisibleDateString=function(){var prevVisibleDate=this.GetPrevVisibleDate();return(prevVisibleDate==null)?null:XartWebui_Calendar_DateText(this,XartWebui_Calendar_DecomposeDate(prevVisibleDate),this.PickerTokens);};XartWebui_Calendar.prototype.GetNextVisibleDate=function(){if(this.ControlType!=cart_calendar_calendarcontroltype_calendar){return null;}
if(this.MaxDate<this.VisibleDateEnd){return null;}
var monthCount=this.MonthRows*this.MonthColumns,newVisibleDateStart=new Date(this.VisibleDateStart.getFullYear(),this.VisibleDateStart.getMonth()+monthCount,1);return newVisibleDateStart;};XartWebui_Calendar.prototype.GetNextVisibleDateString=function(){var nextVisibleDate=this.GetNextVisibleDate();return(nextVisibleDate==null)?null:XartWebui_Calendar_DateText(this,XartWebui_Calendar_DecomposeDate(nextVisibleDate),this.PickerTokens);};XartWebui_Calendar.prototype.SetVisibleDate=function(newVisibleDateStart){if(newVisibleDateStart==null){return;}
if(newVisibleDateStart.getDate()!=1){newVisibleDateStart=new Date(newVisibleDateStart.getFullYear(),newVisibleDateStart.getMonth(),1);}
if(newVisibleDateStart.getMonth()==this.VisibleDateStart.getMonth()&&newVisibleDateStart.getFullYear()==this.VisibleDateStart.getFullYear()){return;}
XartWebui_Calendar_FireClientSideOnBeforeVisibleDateChanged(this,this.AutoPostBackOnVisibleDateChanged);var qzyx;if(newVisibleDateStart<this.VisibleDateStart){qzyx=(newVisibleDateStart<this.GetPrevVisibleDate())?"down":"left";}else{qzyx=(newVisibleDateStart>this.GetNextVisibleDate())?"up":"right";}
this.VisibleDate=newVisibleDateStart;XartWebui_Calendar_ConfineVisibleDate(this);document.getElementById(this.CalendarId+"_visibledate").value=XartWebui_Calendar_DateToString(this.VisibleDate);if(this.AutoPostBackOnVisibleDateChanged||!this.IsCalendarUplevel){eval(this.PostBackCommand);}else{this.UpdateHeaderAndFooter();XartWebui_Calendar_FireClientSideOnVisibleDateChanged(this);var monthCount=this.MonthRows*this.MonthColumns,newVisibleDateEnd=new Date(newVisibleDateStart.getFullYear(),newVisibleDateStart.getMonth()+monthCount,1);XartWebui_Calendar_SwapToDate(this,newVisibleDateStart,newVisibleDateEnd,qzyx);}};XartWebui_Calendar.prototype.FormatDate=function(date,format){return XartWebui_Calendar_DateText(this,XartWebui_Calendar_DecomposeDate(date),XartWebui_Calendar_LoadTokens(this,XartWebui_Calendar_TokenizeDateString(format)));};XartWebui_Calendar.prototype.UpdateHeaderAndFooter=function(){if(this.HeaderClientTemplate){var headerPlaceHolder=document.getElementById(this.CalendarId+"_HeaderTd");if(headerPlaceHolder){headerPlaceHolder.innerHTML=XartWebui_InstantiateClientTemplate(this.HeaderClientTemplate,this);}}
if(this.FooterClientTemplate){var footerPlaceHolder=document.getElementById(this.CalendarId+"_FooterTd");if(footerPlaceHolder){footerPlaceHolder.innerHTML=XartWebui_InstantiateClientTemplate(this.FooterClientTemplate,this);}}};XartWebui_Calendar.prototype.GoPrevYear=function(){this.GoDate(new Date(this.VisibleDate.getFullYear()-1,this.VisibleDate.getMonth(),this.VisibleDate.getDate()));};XartWebui_Calendar.prototype.GoPrevMonth=function(){this.GoDate(new Date(this.VisibleDate.getFullYear(),this.VisibleDate.getMonth()-(this.MonthRows*this.MonthColumns),this.VisibleDate.getDate()));};XartWebui_Calendar.prototype.GoNextMonth=function(){this.GoDate(new Date(this.VisibleDate.getFullYear(),this.VisibleDate.getMonth()+(this.MonthRows*this.MonthColumns),this.VisibleDate.getDate()));};XartWebui_Calendar.prototype.GoNextYear=function(){this.GoDate(new Date(this.VisibleDate.getFullYear()+1,this.VisibleDate.getMonth(),this.VisibleDate.getDate()));};XartWebui_Calendar.prototype.GoToday=function(){this.GoDate(this.TodaysDate);};XartWebui_Calendar.prototype.GoDate=function(date){if(this.ControlType==cart_calendar_calendarcontroltype_picker){this.SetSelectedDate(date,true);return;}
if(this.MonthsSwapInProgress){return;}
var monthCount=this.MonthRows*this.MonthColumns,newVisibleDateStart=new Date(date.getFullYear(),date.getMonth(),1),newVisibleDateEnd=new Date(newVisibleDateStart.getFullYear(),newVisibleDateStart.getMonth()+monthCount,1);if(newVisibleDateEnd<=this.MinDate){return;}
if(this.MaxDate<newVisibleDateStart){return;}
if(newVisibleDateStart<=this.VisibleDate&&this.VisibleDate<newVisibleDateEnd){return;}
this.SetVisibleDate(date);};function XartWebui_Calendar_DateTimeFormatToken(dataArray){for(var qzba=0;qzba<this.qqGr.length;qzba++){this[this.qqGr[qzba]]=dataArray[qzba];}
for(var qzba=0;qzba<this.TransitoryProperties.length;qzba++){this[this.TransitoryProperties[qzba]]=null;}}
XartWebui_Calendar_DateTimeFormatToken.prototype.GetProperty=function(propName){return this[propName];};XartWebui_Calendar_DateTimeFormatToken.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};XartWebui_Calendar_DateTimeFormatToken.prototype.qqGr=["IsSymbol","Value"];XartWebui_Calendar_DateTimeFormatToken.prototype.TransitoryProperties=["Length","StartIndex","EndIndex","Unit","Editable","Textual","LengthFixed","x1","x2","y1","y2"];function XartWebui_Calendar_DateCollection(dateArray){this.DateArray=dateArray;}
XartWebui_Calendar_DateCollection.prototype.GetProperty=function(propName){return this[propName];};XartWebui_Calendar_DateCollection.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};XartWebui_Calendar_DateCollection.prototype.Clear=function(){this.DateArray=new Array();};XartWebui_Calendar_DateCollection.prototype.Find=function(date){return XartWebui_Calendar_FindDate(XartWebui_Calendar_GetDateOnly(date),this.DateArray);};XartWebui_Calendar_DateCollection.prototype.Contains=function(date){return this.Find(date)[1];};XartWebui_Calendar_DateCollection.prototype.Remove=function(date){this.RemoveRange(date,date);};XartWebui_Calendar_DateCollection.prototype.Add=function(date){this.AddRange(date,date);};XartWebui_Calendar_DateCollection.prototype.Select=function(date,toggle){this.SelectRange(date,date,toggle);};XartWebui_Calendar_DateCollection.prototype.RemoveRange=function(startDate,endDate){var startFind=this.Find(startDate),endFind=this.Find(endDate),startIndex=startFind[0],endIndex=endFind[0]-(endFind[1]?0:1);if(startIndex>endIndex){return;}
var startSlice=startIndex==0?[]:this.DateArray.slice(0,startIndex),endSlice=this.DateArray.slice(endIndex+1);this.DateArray=startSlice.concat(endSlice);};XartWebui_Calendar_DateCollection.prototype.AddRange=function(startDate,endDate){this.RemoveRange(startDate,endDate);var insertIndex=this.Find(startDate)[0],startSlice=insertIndex==0?[]:this.DateArray.slice(0,insertIndex),endSlice=this.DateArray.slice(insertIndex),midSlice=[],startDate=XartWebui_Calendar_GetDateOnly(startDate),endDate=XartWebui_Calendar_GetDateOnly(endDate);for(var curDate=startDate;curDate<=endDate;curDate=XartWebui_Calendar_DateAddDays(curDate,1)){midSlice[midSlice.length]=curDate;}
this.DateArray=startSlice.concat(midSlice.concat(endSlice));};XartWebui_Calendar_DateCollection.prototype.SelectRange=function(startDate,endDate,toggle,unselectableDates){if(!toggle){this.Clear();this.AddRange(startDate,endDate);}else{var firstSelectableDateInRange;if(unselectableDates==null){firstSelectableDateInRange=startDate;}else{for(var curDate=startDate;curDate<=endDate;curDate=XartWebui_Calendar_DateAddDays(curDate,1)){if(!unselectableDates.Contains(curDate)){firstSelectableDateInRange=curDate;break;}}
if(firstSelectableDateInRange==null){return;}}
if(this.Find(firstSelectableDateInRange)[1]){this.RemoveRange(startDate,endDate);}else{this.AddRange(startDate,endDate);}}};function XartWebui_CalendarDay(storageArray){for(var qzba=0;qzba<this.qqGr.length;qzba++){this[this.qqGr[qzba]]=storageArray[qzba];}}
XartWebui_CalendarDay.prototype.GetProperty=function(propName){return this[propName];};XartWebui_CalendarDay.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};XartWebui_CalendarDay.prototype.qqGr=["Date","CssClass","HoverCssClass","ActiveCssClass","TemplateId","TemplateInstanceId"];function XartWebui_CalendarDayCollection(storageArray){this.CalendarDayArray=new Array();for(var qzba=0;qzba<storageArray.length;qzba++){this.CalendarDayArray[qzba]=new XartWebui_CalendarDay(storageArray[qzba]);}}
XartWebui_CalendarDayCollection.prototype.GetProperty=function(propName){return this[propName];};XartWebui_CalendarDayCollection.prototype.SetProperty=function(propName,propValue){this[propName]=propValue;};XartWebui_CalendarDayCollection.prototype.Find=function(date){var index=null,lowerBound=0,upperBound=this.CalendarDayArray.length;while(lowerBound<upperBound){index=(lowerBound+upperBound)>>1;if(date.valueOf()==this.CalendarDayArray[index].Date.valueOf()){return this.CalendarDayArray[index];}
if(date<this.CalendarDayArray[index].Date){upperBound=index;}else{lowerBound=index+1;}}
return null;};var cart_calendar_kernel_loaded=true;