
if(!window.XartWebui_TreeView_Keyboard_Loaded){window.qzjl=function(){if(qqPa.qzfw==0){return qqPa.qzai;}
var qzjf=qqPa.qzal.parentNode;qqPa.qzfw--;for(var qzba=0;qzba<qzjf.childNodes.length;qzba++){if(qzjf.childNodes[qzba].nodeName=="TABLE"){qqPa.qzap=qzba;}else{if(qzjf.childNodes[qzba]==qqPa.qzal){break;}}}
qqPa.qzal=qzjf;qqPa.qzai=qqPa.qzal.childNodes[qqPa.qzap];return qqPa.qzai;};window.qzlf=function(){qzaq=qzer(false,true);var qzmd;do{qzmd=qzaq;qzaq=qzer(true,true);}while(qzmd!=qzaq);var qzut=qqPa.qzo(qzdu(qqPa.qzai.id));if(qzut.Expanded&&qzut.ChildIndices.length>0){return qzlf();}
return qqPa.qzai;};window.qzub=function(){if(qqPa.qzap>0){for(qqPa.qzap--;qqPa.qzap>=0;qqPa.qzap--){if(qqPa.qzal.childNodes[qqPa.qzap].nodeName=="TABLE"){break;}}
qqPa.qzai=qqPa.qzal.childNodes[qqPa.qzap];var qzut=qqPa.qzo(qzdu(qqPa.qzai.id));if(qzut.Expanded&&qzut.ChildIndices.length>0){return qzlf();}}else{if(qqPa.qzfw>0){return qzjl();}}
return qqPa.qzai;};window.qzer=function(qzya,qzAbh){var group=null,qzs=0;if(qqPa.qzal.childNodes.length>qqPa.qzap+1&&qqPa.qzal.childNodes[qqPa.qzap+1].nodeName=="DIV"){if(qqPa.qzal.childNodes.length>qqPa.qzap+2&&qqPa.qzal.childNodes[qqPa.qzap+2].nodeName=="DIV"){qzs=qqPa.qzap+2;group=qqPa.qzal.childNodes[qzs];}else{qzs=qqPa.qzap+1;group=qqPa.qzal.childNodes[qzs];}}
if(!group){return;}
if(!qzya&&group.style.display!="none"&&group.childNodes.length>0){qqPa.qzal=group;qqPa.qzai=qqPa.qzal.childNodes[0];qqPa.qzap=0;qqPa.qzfw++;}else{if(qqPa.qzal.lastChild!=group){qqPa.qzap=qzs+1;qqPa.qzai=qqPa.qzal.childNodes[qqPa.qzap];}else{if(!qzAbh&&qqPa.qzfw>0){for(var qzbc=qqPa.qzad;qzbc!=null;qzbc=qqPa.qzo(qzbc.ParentStorageIndex)){if(!qzbc.qzvn()){qzjl();return qzer(true);}}}}}
return qqPa.qzai;};window.qzpp=function(){var qzbu=document.getElementById(qqPa.TreeViewID+"_div");qqPa.qzal=qzbu;qqPa.qzai=qqPa.qzal.childNodes[0];qqPa.qzap=0;qqPa.qzfw=0;return qqPa.qzai;};window.XartWebui_KeyMoveHome=function(){var qzar=qqPa.qzai,qzaq=qzpp();qzAgv(qzaq);qzco(qzar,qzaq);};window.XartWebui_KeyMoveEnd=function(){var qzar=qqPa.qzai,qzmd=qzpp(),qzst=null;while(qzmd!=qzst){qzmd=qzst;qzst=qzer(true,true);}
var qzaq=qzlf();qzAgv(qzaq);qzco(qzar,qzaq);};window.XartWebui_KeyMoveDown=function(){var qzar=qqPa.qzai,qzaq=qzer();qzAgv(qzaq);qzco(qzar,qzaq);};window.XartWebui_KeyMoveUp=function(){var qzar=qqPa.qzai,qzaq=qzub();qzAgv(qzaq);qzco(qzar,qzaq);};window.XartWebui_KeyMoveLeft=function(){var qzss=qzvk(qqPa.qzai);if(qzss&&qzss.style.display!="none"){qzqp(qqPa,qzss,qqPa.qzad);}else{var qzar=qqPa.qzai,qzaq=qzjl();qzco(qzar,qzaq);}};window.XartWebui_KeyMoveRight=function(){if(qqPa.qzad.ChildIndices.length>0||qqPa.qzad.ContentCallbackUrl){var group=qzvk(qqPa.qzai);if(group&&group.style.display=="none"){qzzn(qqPa,group,qqPa.qzad,qqPa.qzfw);}else{var qzar=qqPa.qzai,qzaq=qzer();qzco(qzar,qzaq);}}};window.qzco=function(qzar,qzaq){if(qzar&&qzar.onmouseout){qzar.onmouseout();}
if(qqPa.qzfj&&qqPa.qzfj.onmouseout){qqPa.qzfj.onmouseout();}
if(qqPa.qzai){qqPa.qzad=qqPa.qzo(qzdu(qqPa.qzai.id));qqPa.qzfj=document.getElementById(qqPa.qzai.id+"_cell");if(qzaq.onmouseover){qzaq.onmouseover();}
if(qqPa.qzfj.onmouseover){qqPa.qzfj.onmouseover();}}
qqPa.qzkj=1;};window.qzAex=function(treeView,qzm,qzcd){var qzar=treeView.qzai;treeView.qzad=qzm;treeView.qzai=qzcd;treeView.qzal=qzcd.parentNode;treeView.qzfw=qzm.qzcu;for(var qzba=0;qzba<treeView.qzal.childNodes.length;qzba++){if(treeView.qzal.childNodes[qzba]==qzcd){treeView.qzap=qzba;break;}}
treeView.qzfw=qzm.CalculateDepth();qqPa=treeView;qzco(qzar,qzcd);};window.XartWebui_SetKeyboardFocusedTree=function(qzAjw,qzwz){if(qqPa&&qqPa==qzwz){return;}
if(qqPa){var qzrr=document.getElementById(qqPa.TreeViewID+"_div");if(qzrr){qzrr.className=qqPa.CssClass;}}
qqPa=qzwz;if(qzwz.FocusedCssClass){qzAjw.className=qzwz.FocusedCssClass;}};window.XartWebui_InitKeyboard=function(treeView){var qzbu=document.getElementById(treeView.TreeViewID+"_div");XartWebui_SetKeyboardFocusedTree(qzbu,treeView);treeView.KeyboardEnabled=true;treeView.qzad=treeView.Nodes()[0];treeView.qzfj=document.getElementById(treeView.TreeViewID+"_item_0_cell");treeView.qzal=qzbu;treeView.qzai=treeView.qzal.childNodes[0];treeView.qzap=0;treeView.qzfw=0;XartWebui_RegisterKeyHandler(treeView,"Enter","XartWebui_SelectKeyItem()");XartWebui_RegisterKeyHandler(treeView,"(","XartWebui_KeyMoveDown()");XartWebui_RegisterKeyHandler(treeView,"&","XartWebui_KeyMoveUp()");XartWebui_RegisterKeyHandler(treeView,"'","XartWebui_KeyMoveRight()");XartWebui_RegisterKeyHandler(treeView,"%","XartWebui_KeyMoveLeft()");XartWebui_RegisterKeyHandler(treeView,"$","XartWebui_KeyMoveHome()");XartWebui_RegisterKeyHandler(treeView,"#","XartWebui_KeyMoveEnd()");Event.observe(document,"keydown",XartWebui_ProcessKeyPress,false);};window.XartWebui_SelectKeyItem=function(){if(qqPa){qqPa.SelectNode(qqPa.qzad,qqPa.qzai,qqPa.qzfj);}};window.XartWebui_TreeView_Keyboard_Loaded=true;}