
function XartWebui_Dialog(id,_2,_3,_4){Dialogs.push(id);this.DomElementId=id;if(!document.getElementById(this.DomElementId)){if(!_2){_2=100;}
if(!_3){_3=200;}
var _5=document.createElement("div");_5.setAttribute("id",this.DomElementId);_5.style.position="absolute";_5.style.visibility="hidden";_5.style.height=_2+"px";_5.style.width=_3+"px";var _6="";if(this.FocusOnClick){_6="onclick='"+id+".Focus();' ";}
if(cart_browser_ie&&_4.RenderOverWindowedObjects){_5.innerHTML="<iframe id='"+this.DomElementId+"_OverlayIFrame' style='position:absolute;top:0;left:0;width:100%;height:100%;display:block;z-index:-1;filter:progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0);'></iframe><div id='"+id+"_HeaderSpan'></div><div "+_6+"id='"+id+"_InnerSpan'></div><div id='"+id+"_FooterSpan'></div>";}else{_5.innerHTML="<div id='"+id+"_HeaderSpan'></div><div "+_6+"id='"+id+"_InnerSpan'></div><div id='"+id+"_FooterSpan'></div>";}
document.forms[0].appendChild(_5);var _7=new Array();if(_4){for(i in _4.PublicProperties){if(_4.PublicProperties[i][0]!="Id"&&_4.PublicProperties[i][0]!="IsShowing"){var _8=_4.PublicProperties[i][0];var _9=_4[_8];var _a=[_8,_9];_7.push(_a);}}}else{_7=[["Alignment","MiddleCentre"],["OffsetX",0],["OffsetY",0],["X",null],["Y",null]];}
this.ControlId=id;XartWebui_SetProperties(this,_7);_q123(this);this.DomElement=document.getElementById(id);this.DomElement.onmousemove=new Function("e","eval(\""+id+".getMouseXY(e);\");");this.DomElement.onmousedown=new Function("e","eval(\""+id+".HandleMouseDown(e);\");");this.DomElement.onmouseout=new Function("e","eval(\""+id+".HandleMouseOut(e);\");");this.DomElement.onmouseup=new Function("e","eval(\""+id+".HandleMouseUp(e);\");");}
this.element=this.DomElement=document.getElementById(this.DomElementId);this.DomElement.parentNode.removeChild(this.DomElement);document.forms[0].insertBefore(this.DomElement,document.forms[0].firstChild);zTop++;this.element.style.zIndex=zTop;if(window.XartWebui_Atlas){XartWebui.Web.UI.Dialog.initializeBase(this,[this.element]);this.beginUpdate=function(){this._updating=true;};this.dispose=function(){XartWebui.Web.UI.Dialog.callBaseMethod(this,"dispose");this.Dispose();};this.endUpdate=function(){this._updating=false;this.Render();};this.get_isUpdating=function(){return this._updating;};this.getDescriptor=function(){return _qE4(this.constructor);};}else{this.beginUpdate=function(){this._updating=true;};this.endUpdate=function(){this._updating=false;this.Render();};this.get_isUpdating=function(){return this._updating;};}
this.ClientControlId=this.Id=id;}
XartWebui_Dialog.prototype.Dispose=function(){XartWebui_Dispose(this);};XartWebui_Dialog.prototype.Initialize=function(){_q123(this);this.DomElement.onmousemove=new Function("e",this.Id+".getMouseXY(e);");this.DomElement.onmousedown=new Function("e",this.Id+".HandleMouseDown(e);");this.DomElement.onmouseout=new Function("e",this.Id+".HandleMouseOut(e);");this.DomElement.onmouseup=new Function("e",this.Id+".HandleMouseUp(e);");this.Render();};XartWebui_Dialog.prototype.PublicProperties=[["Enabled",Boolean],["IsShowing",Boolean,1],["Modal",Boolean],["ModalMaskImage",String],["ResizeArea",Boolean],["FocusOnClick",Boolean,1],["Id",String,1],["Alignment",String],["MinimumHeight",Number],["MinimumWidth",Number],["Height",String],["Width",String],["OffsetX",Number],["OffsetY",Number],["X",Number],["Y",Number],["Content",String],["ContentUrl",String],["Title",String],["Icon",String],["Value",String],["Result",Object],["CloseTransition",Number],["ShowTransition",Number],["AlignmentElement",String],["AnimationType",String],["AnimationPath",String],["AnimationDirectionElement",String],["AnimationDuration",Number],["TransitionDuration",Number],["AnimationSlide",Number],["ClientTemplates",Array],["ClientEvents",Array],["AllowDrag",Boolean],["AllowResize",Boolean],["RenderOverWindowedObjects",Boolean],["HeaderClientTemplateId",String],["ContentClientTemplateId",String],["FooterClientTemplateId",String],["ModalMaskCssClass",String],["HeaderCssClass",String],["FooterCssClass",String],["ContentCssClass",String],["IFrameCssClass",String],["OutlineCssClass",String],["CssClass",String]];window.XartWebui.Web.UI.Dialog=window.XartWebui_Dialog;XartWebui_Dialog.prototype.PublicMethods=[["Dispose"],["StartDrag"],["Focus"],["Show"],["Close"]];XartWebui_Dialog.prototype.PublicEvents=[["OnShow"],["OnClose"],["OnFocus"],["OnDrag"],["OnDrop"]];_qE3(XartWebui_Dialog,"this");window.XartWebui.Web.UI.Dialog=window.XartWebui_Dialog;if(window.XartWebui_Atlas){XartWebui.Web.UI.Dialog.registerClass("XartWebui.Web.UI.Dialog",Sys.UI.Control);if(Sys.TypeDescriptor){Sys.TypeDescriptor.addType("XartWebuiWebUI","dialog",XartWebui.Web.UI.Dialog);}}
XartWebui_Dialog.prototype.GetProperty=function(_b){return this[_b];};XartWebui_Dialog.prototype.SetProperty=function(_c,_d){this[_c]=_d;};XartWebui_Dialog.prototype.Focus=function(){if(Dialogs.length>1){var i=0;for(j=0;j<Dialogs.length;j++){if(eval(Dialogs[j]+".Modal")&&eval(Dialogs[j]+".IsShowing")){i++;}
if(i>1){return;}}
zTop++;this.DomElement.style.zIndex=zTop;}
var _f=this.get_events().getHandler("onFocus");if(_f){_f(this,Sys.EventArgs.Empty);}};XartWebui_Dialog.prototype.Show=function(_10,_11,_12,x,y){if(!this.IsShowing){if(this.AnimationType=="Live"&&cart_browser_ie){this.DomElement.style.zoom="1%";}
this.Result=null;if(_10){this.Content=_10;}
if(_11){this.Title=_11;}
if(_12){this.Icon=_12;}
if(x){this.X=x;}
if(y){this.Y=y;}
if(this.Modal){art_ShowModal(this.Id,this.ModalMaskCssClass);}
this.DomElement.style.visibility="visible";this.Render();if(Dialogs.length>1){for(i=0;i<Dialogs.length;i++){var _15=document.getElementById(Dialogs[i]);var _16=document.getElementById(this.Id);if(Math.abs(parseInt(_15.style.top)-parseInt(_16.style.top))<10&&Math.abs(parseInt(_15.style.left)-parseInt(_16.style.left))<10&&Dialogs[i]!=this.Id&&_15.style.visibility=="visible"){this.set_offsetX(this.OffsetX+15);this.set_offsetY(this.OffsetY+15);}}}
var _17=false;if(this.AnimationType!="None"){this.ShowAnimate(0,document.getElementById(this.AnimationDirectionElement),this.DomElement);_17=true;}
if((this.ShowTransition>0)&&cart_browser_transitions){this.DomElement.style.visibility="hidden";var _18=this.DomElement;_18.filters.clear();_18.runtimeStyle.filter=null;var _19=XartWebui_EffectiveTransitionString(this.ShowTransition-0);_18.ExpandTransitionFilterIndex=_18.filters.length;_18.ExpandTransitionFilterDefined=true;_18.runtimeStyle.filter=_18.currentStyle.filter+" "+_19;_18.filters[_18.ExpandTransitionFilterIndex].apply();_18.style.visibility="visible";_18.filters[_18.ExpandTransitionFilterIndex].play(this.TransitionDuration/1000);}
this.Focus();if(!_17){this.IsShowing=true;var _1a=this.get_events().getHandler("onShow");if(_1a){_1a(this,Sys.EventArgs.Empty);}}}};XartWebui_Dialog.prototype.Close=function(_1b){if(this.IsShowing){if(!(_1b===void 0)){this.SetProperty("Result",_1b);}
if(this.AnimationType!="None"){this.CloseAnimate();var _1c=true;}
if((this.CloseTransition>0)&&cart_browser_transitions){var _1d=this.DomElement;_1d.filters.clear();_1d.runtimeStyle.filter=null;var _1e=XartWebui_EffectiveTransitionString(this.CloseTransition-0);_1d.CollapseTransitionFilterIndex=_1d.filters.length;_1d.CollapseTransitionFilterDefined=true;_1d.runtimeStyle.filter=_1d.currentStyle.filter+" "+_1e;_1d.filters[_1d.CollapseTransitionFilterIndex].apply();this.DomElement.style.visibility="hidden";_1d.filters[_1d.CollapseTransitionFilterIndex].play(this.TransitionDuration/1000);}else{if(!_1c){this.DomElement.style.visibility="hidden";}}
if(!_1c){if(this.Modal){art_CloseModal(this.Id);}
this.IsShowing=false;var _1f=this.get_events().getHandler("onClose");if(_1f){_1f(this,Sys.EventArgs.Empty);}}}};XartWebui_Dialog.prototype.Render=function(){if(this.AnimationType!="Live"){this.DomElement.style.zoom="100%";}
if(this.Height){this.DomElement.style.height=this.Height;}
if(this.Width){this.DomElement.style.width=this.Width;}
art_PositionDialog(this.Id,this.Alignment,this.X,this.Y,this.OffsetX,this.OffsetY,this.AlignmentElement);if(this.ContentUrl&&document.getElementById(this.Id+"_IFrame")){document.getElementById(this.Id+"_IFrame").src=this.ContentUrl;}
if(this.HeaderClientTemplateId){var _20=this.GetClientTemplate(this.HeaderClientTemplateId);document.getElementById(this.Id+"_HeaderSpan").innerHTML=XartWebui_InstantiateClientTemplate(_20,this);}
if(this.ContentClientTemplateId){var _20=this.GetClientTemplate(this.ContentClientTemplateId);document.getElementById(this.Id+"_InnerSpan").innerHTML=XartWebui_InstantiateClientTemplate(_20,this);}else{if(this.Content){document.getElementById(this.Id+"_InnerSpan").innerHTML=this.Content;}}
if(this.FooterClientTemplateId){var _20=this.GetClientTemplate(this.FooterClientTemplateId);document.getElementById(this.Id+"_FooterSpan").innerHTML=XartWebui_InstantiateClientTemplate(_20,this);}
if(this.CssClass){this.DomElement.className=this.CssClass;}
if(this.HeaderCssClass){document.getElementById(this.Id+"_HeaderSpan").className=this.HeaderCssClass;}
if(this.ContentCssClass){document.getElementById(this.Id+"_InnerSpan").className=this.ContentCssClass;}
if(this.FooterCssClass){document.getElementById(this.Id+"_FooterSpan").className=this.FooterCssClass;}
if(this.RenderOverWindowedObjects&&cart_browser_ie){var _21=document.getElementById(this.Id+"_OverlayIFrame");_21.style.width=this.DomElement.offsetWidth+"px";_21.style.height=this.DomElement.offsetHeight+"px";}};var _q2F;var _q31;var art_oldResize;var art_dialogDragging;var art_dialogResizing;var art_mouseX;var art_mouseY;var art_offsetX;var art_offsetY;art_returnFalse=function(e){return false;};art_returnTrue=function(e){return true;};art_resizeUpdate=function(){var _24=document.getElementById(art_dialogResizing.Id+"_InnerSpan");var _25=document.getElementById(art_dialogResizing.Id+"_HeaderSpan");var _26=document.getElementById(art_dialogResizing.Id+"_FooterSpan");var _27=0;if(_25){_27=_25.offsetHeight;}
if(_26){_27+=_26.offsetHeight;}
var x=qzAfx(art_dialogResizing.DomElement);var y=qzAfw(art_dialogResizing.DomElement);if(art_mouseX-x>0){_24.style.width=((art_mouseX-x)+1)+"px";art_dialogResizing.DomElement.style.width=((art_mouseX-x)+1)+"px";art_dialogResizing.SetProperty("Width",art_mouseX-x+1);if(art_mouseX-x<art_dialogResizing.MinimumWidth){_24.style.width=(art_dialogResizing.MinimumWidth)+"px";art_dialogResizing.SetProperty("Width",art_dialogResizing.MinimumWidth);art_dialogResizing.DomElement.style.width=(art_dialogResizing.MinimumWidth)+"px";}}
if(art_mouseY-y-_27>0){_24.style.height=((art_mouseY-y)-_27+1)+"px";art_dialogResizing.DomElement.style.height=(art_mouseY-y+1)+"px";art_dialogResizing.SetProperty("Height",art_mouseY-y+1);if(art_mouseY-y<art_dialogResizing.MinimumHeight){_24.style.height=(art_dialogResizing.MinimumHeight-_27)+"px";art_dialogResizing.DomElement.style.height=(art_dialogResizing.MinimumHeight)+"px";art_dialogResizing.SetProperty("Height",art_dialogResizing.MinimumHeight);}}};art_GetMouseXY=function(e){if(!e){e=window.event;}
art_mouseX=cart_browser_ie?e.clientX+(document.documentElement&&document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft):e.pageX;art_mouseY=cart_browser_ie?e.clientY+(document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop):e.pageY;if(art_dialogResizing){art_resizeUpdate();XartWebui_CancelEvent(e);}};XartWebui_Dialog.prototype.HandleMouseUp=function(e){art_dialogDragging=false;art_dialogResizing=null;if(_q31){document.onmouseup=_q31;}
document.onmousemove=null;document.onselectstart=null;if(!this.ResizeArea){this.DomElement.style.cursor="";}};XartWebui_Dialog.prototype.HandleMouseDown=function(e){if(this.ResizeArea&&this.AllowResize){art_GetMouseXY(e);art_dialogResizing=this;document.onmousemove=art_GetMouseXY;}
return true;};XartWebui_Dialog.prototype.getMouseXY=function(e){if(!e){e=window.event;}
art_mouseX=cart_browser_ie?e.clientX+(document.documentElement&&document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft):e.pageX;art_mouseY=cart_browser_ie?e.clientY+(document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop):e.pageY;if(this.AllowResize){if(art_dialogResizing){art_resizeUpdate();}
if(Math.abs(art_mouseX-(parseInt(this.DomElement.style.left)+this.DomElement.offsetWidth))<10&&Math.abs(art_mouseY-(parseInt(this.DomElement.style.top)+this.DomElement.offsetHeight))<10){this.ResizeArea=true;this.DomElement.style.cursor="se-resize";}else{this.ResizeArea=false;this.DomElement.style.cursor="";}}};XartWebui_Dialog.prototype.HandleMouseOut=function(e){if(!art_dialogResizing){this.ResizeArea=false;this.DomElement.style.cursor="";}};XartWebui_Dialog.prototype.StartDrag=function(e){this.Focus();if(this.AllowDrag){art_GetMouseXY(e);art_dialogDragging=true;document.onselectstart=art_returnFalse;_q2F=document.onmousemove;_q31=document.onmouseup;if(this.Modal){maskTable=document.getElementById(this.Id+"_ModalTable");maskTable.onmousemove=art_GetMouseXY;this.DomElement.onmousemove=art_GetMouseXY;}else{document.onmousemove=art_GetMouseXY;}
art_offsetX=art_mouseX-qzAfx(this.DomElement);art_offsetY=art_mouseY-qzAfw(this.DomElement);art_DialogDragStep(this.Id);var _30=this.get_events().getHandler("onDrag");if(_30){_30(this,Sys.EventArgs.Empty);}
XartWebui_CancelEvent(e);}};art_DialogDragStep=function(id){if(art_dialogDragging){document.getElementById(id).style.left=(art_mouseX-art_offsetX)+"px";document.getElementById(id).style.top=(art_mouseY-art_offsetY)+"px";setTimeout("art_DialogDragStep(\""+id+"\")",50);}else{eval(id).SetProperty("X",qzAfx(document.getElementById(id)));eval(id).SetProperty("Y",qzAfw(document.getElementById(id)));var _32=eval(id).get_events().getHandler("onDrop");if(_32){_32(eval(id),Sys.EventArgs.Empty);}}};XartWebui_Dialog.prototype.GetClientTemplate=function(sID){if(this.ClientTemplates){for(var i=0;i<this.ClientTemplates.length;i++){if(this.ClientTemplates[i][0]==sID){return this.ClientTemplates[i][1];}}}
return null;};var XartWebui_DialogToMinimize=null;var XartWebui_AnimationType=null;var XartWebui_AnimationPath=null;XartWebui_Dialog.prototype.ShowAnimate=function(_35,_36,_37){var _38=qzAfx(_36);var _39=qzAfw(_36);var _3a=_36.offsetWidth;var _3b=_36.offsetHeight;var _3c=qzAfx(_37);var _3d=qzAfw(_37);var _3e=_37.offsetWidth;var _3f=_37.offsetHeight;if(!_35){_37.style.visibility="hidden";}
dialog_speed_x=0;dialog_speed_y=0;XartWebui_DialogToMinimize=this;XartWebui_AnimationPath=this.AnimationPath;if(this.AnimationType=="Live"&&cart_browser_ie){XartWebui_DialogMinimizeObject=this.DomElement;var _40=0;if(!_35){_40=this.AnimationDuration-this.TransitionDuration;}
XartWebui_DialogMinimizeObject.MinimizeStartTime=(new Date()).getTime()-_40;XartWebui_DialogMinimizeObject.style.top=_39+"px";XartWebui_DialogMinimizeObject.style.left=_38+"px";XartWebui_AnimationType="Live";}else{XartWebui_AnimationType="Outline";}
art_MinimizeAnimate(_35,this.OutlineCssClass,this.AnimationSlide,this.AnimationDuration,_38,_39,_3a,_3b,_3c,_3d,_3e,_3f,this.TransitionDuration);};XartWebui_Dialog.prototype.CloseAnimate=function(){if(this.AnimationDirectionElement){var _41=document.getElementById(this.AnimationDirectionElement);if(_41){this.ShowAnimate(1,this.DomElement,_41);}}else{this.DomElement.style.visibility="hidden";}};if(!Dialogs){var Dialogs=new Array();}
if(!zTop){var zTop=900;}
var TabElements=new Array();var TabableElements=new Array("A","BUTTON","TEXTAREA","INPUT","IFRAME","SELECT");var XartWebui_Dialog_Kernel_Loaded=true;