/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jan 24 19:02:32 CST 2008 by MyEclipse Hibernate Tool.
 */
package com.insigma.siis.demo.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the REWAGE table. 
 * You can customize the behavior of this class by editing the class, {@link Rewage()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractRewage 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private RewageKey id;

    /** The value of the simple eac018 property. */
    private java.lang.Double eac018;

    /** The value of the simple prseno property. */
    private java.lang.Long prseno;

    /**
     * Simple constructor of AbstractRewage instances.
     */
    public AbstractRewage()
    {
    }

    /**
     * Constructor of AbstractRewage instances given a composite primary key.
     * @param id
     */
    public AbstractRewage(RewageKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return RewageKey
     */
    public RewageKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(RewageKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the EAC018 column.
     * @return java.lang.Double
     */
    public java.lang.Double getEac018()
    {
        return this.eac018;
    }

    /**
     * Set the value of the EAC018 column.
     * @param eac018
     */
    public void setEac018(java.lang.Double eac018)
    {
        this.eac018 = eac018;
    }

    /**
     * Return the value of the PRSENO column.
     * @return java.lang.Long
     */
    public java.lang.Long getPrseno()
    {
        return this.prseno;
    }

    /**
     * Set the value of the PRSENO column.
     * @param prseno
     */
    public void setPrseno(java.lang.Long prseno)
    {
        this.prseno = prseno;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Rewage))
            return false;
        Rewage that = (Rewage) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
