/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jan 24 19:02:32 CST 2008 by MyEclipse Hibernate Tool.
 */
package com.insigma.siis.demo.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the REWAGE
 * table.  This object should only be instantiated for use with instances 
 * of the Rewage class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class RewageKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the AAC001 component of this composite id. */
    private java.lang.String aac001;

    /** The value of the AAE140 component of this composite id. */
    private java.lang.String aae140;

    /**
     * Simple constructor of RewageKey instances.
     */
    public RewageKey()
    {
    }

    /**
     * Returns the value of the aac001 property.
     * @return java.lang.String
     */
    public java.lang.String getAac001()
    {
        return aac001;
    }

    /**
     * Sets the value of the aac001 property.
     * @param aac001
     */
    public void setAac001(java.lang.String aac001)
    {
        hashValue = 0;
        this.aac001 = aac001;
    }

    /**
     * Returns the value of the aae140 property.
     * @return java.lang.String
     */
    public java.lang.String getAae140()
    {
        return aae140;
    }

    /**
     * Sets the value of the aae140 property.
     * @param aae140
     */
    public void setAae140(java.lang.String aae140)
    {
        hashValue = 0;
        this.aae140 = aae140;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof RewageKey))
            return false;
        RewageKey that = (RewageKey) rhs;
        if (this.getAac001() == null || that.getAac001() == null)
        {
            return false;
        }
        if (! this.getAac001().equals(that.getAac001()))
        {
            return false;
        }
        if (this.getAae140() == null || that.getAae140() == null)
        {
            return false;
        }
        if (! this.getAae140().equals(that.getAae140()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int aac001Value = this.getAac001() == null ? 0 : this.getAac001().hashCode();
            result = result * 37 + aac001Value;
            int aae140Value = this.getAae140() == null ? 0 : this.getAae140().hashCode();
            result = result * 37 + aae140Value;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
