package com.insigma.siis.local.pagemodel.sysorg.org.gbjbqk;

import com.insigma.odin.framework.db.DBUtil;
import com.insigma.odin.framework.db.DBUtil.DBType;
import com.insigma.odin.framework.radow.RadowException;

public class GbjbqknlSql {

	public GbjbqknlSql() {
		
	}
	
	public void returnSqlSelect(StringBuffer sb) throws RadowException{
		if(DBType.ORACLE==DBUtil.getDBType()){
			sb.append(" "
					+ " SELECT  "
			       + " count(a.a0000) heji,"//合计
		            +" a.A0221, "//当前职位层次
		            + " sum(CASE "
		            	+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(add_months(sysdate,-264),'yyyy-mm')),'yyyy-mm'))/12)<=20  THEN "
			              + " 1 "
			             + " ELSE "
			              + " 0 "
			              + " END) xydy20, "
			        + " sum(CASE "
	            		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=21  THEN "
			              + " 1 "
			             + " ELSE "
			              + " 0 "
			              + " END) dy21, "
			        + " sum(CASE "
		            		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=22  THEN "
				              + " 1 "
				             + " ELSE "
				              + " 0 "
				              + " END) dy22, "
		            + " sum(CASE "
		        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=23  THEN "
			              + " 1 "
			             + " ELSE "
			              + " 0 "
			              + " END) dy23, "
			        + " sum(CASE "
		        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=24  THEN "
			              + " 1 "
			             + " ELSE "
			              + " 0 "
			              + " END) dy24, "
			        + " sum(CASE "
			        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=25  THEN "
				              + " 1 "
				             + " ELSE "
				              + " 0 "
				              + " END) dy25, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=26  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy26, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=27  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy27, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=28  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy28, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=29  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy29, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=30  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy30, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=31  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy31, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=32  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy32, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=33  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy33, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=34  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy34, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=35  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy35, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=36  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy36, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=37  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy37, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=38  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy38, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=39  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy39, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=40  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy40, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=41  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy41, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=42  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy42, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=43  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy43, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=44  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy44, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=45  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy45, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=46  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy46, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=47  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy47, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=48  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy48, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=49  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy49, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=50  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy50, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=51  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy51, "
		              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=52  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy52, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=53  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy53, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=54  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy54, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=55  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy55, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=56  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy56, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=57  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy57, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=58  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy58, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=59  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy59, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=60  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy60, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=61  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy61, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=62  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy62, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=63  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy63, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)=64  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dy64, "
	              + " sum(CASE "
	        		+ " WHEN floor(months_between(SYSDATE,to_date(nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm')),'yyyy-mm'))/12)>=65  THEN "
		              + " 1 "
		             + " ELSE "
		              + " 0 "
		              + " END) dydy65, "
	              + " round( "
	              	+ " sum( " 
	                      + " floor( "
	                            + "  months_between( SYSDATE,  to_date( nvl(substr(a.a0107,1,6),to_char(sysdate,'yyyy-mm') ) , 'yyyy-mm' )  ) /12 "
	                            + " ) "
	                    + " )  /  sum("
	                         + " case when a.a0107 is not null then 1 else 0 end "
	                         + ") "
	                    + " ,2) pjnl, "//平均年龄
	               +" sum("
	                        + " case when a.a0107 is not null then 1 else 0 end "
	                        + ")  heji_zs "
			  +" FROM (SELECT a01.a0000, "//人员统一标识符
			  			  + " a01.a0107, "//出生日期
						  + " a01.A0221 "//当前职务层次
			          +" FROM A01 a01 "//人员基本信息表
			         +"  ");//任职状态 1 在任
		}else if(DBType.MYSQL==DBUtil.getDBType()){
			sb.append(" "
					+ " SELECT  "
			       + " count(a.a0000) heji,"//合计
		            +" a.A0221, "//当前职位层次
		            + " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 264 month),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) <= 20 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) xydy20, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month,		 "	
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 21 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy21, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 			if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 22 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy22, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 		if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 23 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy23, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 24 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy24, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 25 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy25, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 26 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy26, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 27 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy27, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 28 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy28, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 29 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy29, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 30 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy30, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 31 THEN "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy31,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(   "
					+ " 		timestampdiff (     "
					+ " 			month,    "
					+ " 				if (    "
					+ " 					a.a0107='',   "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),    "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),      "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12   "
					+ " 	) = 32 THEN   "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy32,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(    "
					+ " 		timestampdiff (  "
					+ " 			month, "
					+ " 				if (    "
					+ " 					a.a0107='',  "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),  "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)   "
					+ " 				),      "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12  "
					+ " 	) = 33 THEN "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy33,    "
					+ " sum(       "
					+ " 	CASE   "
					+ " 	WHEN floor( "
					+ " 		timestampdiff (   "
					+ " 			month,   "
					+ " 				if (  "
					+ " 					a.a0107='',    "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)   "
					+ " 				),    "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12  "
					+ " 	) = 34 THEN   "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy34,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(  "
					+ " 		timestampdiff (    "
					+ " 			month, "
					+ " 				if (   "
					+ " 					a.a0107='',    "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),  "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)    "
					+ " 				),       "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12  "
					+ " 	) = 35 THEN  "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy35,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(    "
					+ " 		timestampdiff (   "
					+ " 			month,  "
					+ " 				if (  "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),  "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12   "
					+ " 	) = 36 THEN  "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy36,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(  "
					+ " 		timestampdiff (  "
					+ " 			month, "
					+ " 				if (   "
					+ " 					a.a0107='',   "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),   "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')  "
					+ " 		) / 12 "
					+ " 	) = 37 THEN   "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy37,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(  "
					+ " 		timestampdiff (  "
					+ " 			month, "
					+ " 				if (  "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')  "
					+ " 		) / 12   "
					+ " 	) = 38 THEN  "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy38,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(   "
					+ " 		timestampdiff (   "
					+ " 			month,  "
					+ " 				if (   "
					+ " 					a.a0107='',  "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12  "
					+ " 	) = 39 THEN   "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy39,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(  "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if (  "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),   "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12  "
					+ " 	) = 40 THEN  "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy40,    "
					+ " sum(       "
					+ " 	CASE   "
					+ " 	WHEN floor(   "
					+ " 		timestampdiff (  "
					+ " 			month,  "
					+ " 				if (  "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),  "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),  "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 41 THEN   "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy41,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(   "
					+ " 		timestampdiff (   "
					+ " 			month, "
					+ " 				if (  "
					+ " 					a.a0107='',  "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),  "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)   "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12 "
					+ " 	) = 42 THEN   "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy42,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(   "
					+ " 		timestampdiff (   "
					+ " 			month, "
					+ " 				if (   "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),  "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12  "
					+ " 	) = 43 THEN  "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy43,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor( "
					+ " 		timestampdiff (   "
					+ " 			month,  "
					+ " 				if (  "
					+ " 					a.a0107='',  "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),   "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),  "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12  "
					+ " 	) = 44 THEN "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy44,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor( "
					+ " 		timestampdiff (   "
					+ " 			month,   "
					+ " 				if ( "
					+ " 					a.a0107='',  "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),  "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),  "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12  "
					+ " 	) = 45 THEN  "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy45,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(   "
					+ " 		timestampdiff (  "
					+ " 			month,   "
					+ " 				if (  "
					+ " 					a.a0107='',  "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),   "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),    "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')  "
					+ " 		) / 12  "
					+ " 	) = 46 THEN "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy46,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(           "
					+ " 		timestampdiff (   "
					+ " 			month,        "
					+ " 				if (     "
					+ " 					a.a0107='',     "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12   "
					+ " 	) = 47 THEN  "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy47,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(          "
					+ " 		timestampdiff (  "
					+ " 			month,       "
					+ " 				if (     "
					+ " 					a.a0107='',    "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12    "
					+ " 	) = 48 THEN   "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy48,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(           "
					+ " 		timestampdiff (   "
					+ " 			month,        "
					+ " 				if (      "
					+ " 					a.a0107='',     "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12  "
					+ " 	) = 49 THEN "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy49,    "
					+ " sum(       "
					+ " 	CASE   "
					+ " 	WHEN floor(          "
					+ " 		timestampdiff (  "
					+ " 			month,       "
					+ " 				if (     "
					+ " 					a.a0107='',      "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12    "
					+ " 	) = 50 THEN   "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy50,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(          "
					+ " 		timestampdiff (  "
					+ " 			month,       "
					+ " 				if (     "
					+ " 					a.a0107='',    "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12   "
					+ " 	) = 51 THEN  "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy51,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(          "
					+ " 		timestampdiff (  "
					+ " 			month,       "
					+ " 				if (     "
					+ " 					a.a0107='',      "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12  "
					+ " 	) = 52 THEN "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy52,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(                                          "
					+ " 		timestampdiff (                                  "
					+ " 			month,                                       "
					+ " 				if (                                     "
					+ " 					a.a0107='',                          "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12   "
					+ " 	) = 53 THEN  "
					+ " 		1                                                "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy53,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(         "
					+ " 		timestampdiff ( "
					+ " 			month,      "
					+ " 				if (    "
					+ " 					a.a0107='',    "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12    "
					+ " 	) = 54 THEN   "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy54,     "
					+ " sum(        "
					+ " 	CASE    "
					+ " 	WHEN floor(          "
					+ " 		timestampdiff (  "
					+ " 			month,       "
					+ " 				if (     "
					+ " 					a.a0107='',    "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12    "
					+ " 	) = 55 THEN   "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy55,    "
					+ " sum(       "
					+ " 	CASE        "
					+ " 	WHEN floor(     "
					+ " 		timestampdiff (     "
					+ " 			month,          "
					+ " 				if (        "
					+ " 					a.a0107='',                          "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12    "
					+ " 	) = 56 THEN   "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy56,    "
					+ " sum(       "
					+ " 	CASE   "
					+ " 	WHEN floor(           "
					+ " 		timestampdiff (   "
					+ " 			month,        "
					+ " 				if (      "
					+ " 					a.a0107='',                          "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12               "
					+ " 	) = 57 THEN              "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy57,    "
					+ " sum(       "
					+ " 	CASE   "
					+ " 	WHEN floor(           "
					+ " 		timestampdiff (   "
					+ " 			month,        "
					+ " 				if (      "
					+ " 					a.a0107='',                          "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')  "
					+ " 		) / 12   "
					+ " 	) = 58 THEN  "
					+ " 		1 "
					+ " 	ELSE  "
					+ " 		0 "
					+ " 	END   "
					+ " ) dy58,   "
					+ " sum(      "
					+ " 	CASE  "
					+ " 	WHEN floor(         "
					+ " 		timestampdiff ( "
					+ " 			month,      "
					+ " 				if (    "
					+ " 					a.a0107='',                          "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				),          "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')   "
					+ " 		) / 12              "
					+ " 	) = 59 THEN             "
					+ " 		1  "
					+ " 	ELSE   "
					+ " 		0  "
					+ " 	END    "
					+ " ) dy59,    "
					+ " sum(       "
					+ " 	CASE   "
					+ " 	WHEN floor(           "
					+ " 		timestampdiff (   "
					+ " 			month,        "
					+ " 				if (      "
					+ " 					a.a0107='',                          "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'),     "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107)  "
					+ " 				),           "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d')    "
					+ " 		) / 12               "
					+ " 	) = 60 THEN              "
					+ " 		1   "
					+ " 	ELSE    "
					+ " 		0   "
					+ " 	END     "
					+ " ) dy60,     "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 61 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy61, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( " 
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 62 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy62, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', " 
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 63 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dy63, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( " 
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) = 64 THEN "
					+ " 		1 "
					+ " 	ELSE " 
					+ " 		0 "
					+ " 	END "
					+ " ) dy64, "
					+ " sum( "
					+ " 	CASE "
					+ " 	WHEN floor( "
					+ " 		timestampdiff ( "
					+ " 			month, "
					+ " 				if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 		) / 12 "
					+ " 	) >= 65 THEN "
					+ " 		1 "
					+ " 	ELSE "
					+ " 		0 "
					+ " 	END "
					+ " ) dydy65, "
					+ " round( "
					+ " 	sum( "
					+ " 		floor( "
					+ " 			timestampdiff ( "
					+ " 				month, "
					+ " 					if ( "
					+ " 					a.a0107='', "
					+ " 					DATE_FORMAT(CURDATE(),'%y%m%d'), "
					+ " 					if(length(a.a0107)=6,CONCAT(a.a0107,\"01\"),a.a0107) "
					+ " 				), "
					+ " 				DATE_FORMAT(CURDATE(),'%y%m%d') "
					+ " 			) / 12 "
					+ " 		) "
					+ " 	) / sum( "
					+ " 		CASE "
					+ " 		WHEN a. a0107 IS NOT NULL THEN "
					+ " 			1 "
					+ " 		ELSE "
					+ " 			0 "
					+ " 		END "
					+ " 	) "
					+ " ,2) pjnl, "//平均年龄
	               +" sum("
	                        + " case when a.a0107 is not null then 1 else 0 end "
	                        + ")  heji_zs "
			  +" FROM (SELECT a01.a0000, "//人员统一标识符
			  			  + " a01.a0107, "//出生日期
						  + " a01.A0221 "//当前职务层次
			          +" FROM A01 a01 "//人员基本信息表
			         +"  ");
		}else{
			throw new RadowException("发现未知数据源，请联系系统管理员!");
		}
	}

}
