package com.insigma.siis.local.business.audit;
// Generated 2021-4-7 11:25:03 by Hibernate Tools 5.4.14.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * AuditBatch generated by hbm2java
 */
public class AuditBatch implements java.io.Serializable {

	private String oid;
	private String auditBatchNo;
	private String auditDept;
	private Date deptSubTime;
	private Date auditSubTime;
	private Date feedbackTime;
	private String batchStatus;
	private String createBy;
	private Date createTime;
	private String batchType;

	public AuditBatch() {
	}

	public AuditBatch(String oid) {
		this.oid = oid;
	}

	public AuditBatch(String oid, String auditBatchNo, String auditDept, Date deptSubTime, Date auditSubTime,
			Date feedbackTime, String batchStatus, String createBy, Date createTime, String batchType) {
		this.oid = oid;
		this.auditBatchNo = auditBatchNo;
		this.auditDept = auditDept;
		this.deptSubTime = deptSubTime;
		this.auditSubTime = auditSubTime;
		this.feedbackTime = feedbackTime;
		this.batchStatus = batchStatus;
		this.createBy = createBy;
		this.createTime = createTime;
		this.batchType = batchType;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getAuditBatchNo() {
		return this.auditBatchNo;
	}

	public void setAuditBatchNo(String auditBatchNo) {
		this.auditBatchNo = auditBatchNo;
	}

	public String getAuditDept() {
		return this.auditDept;
	}

	public void setAuditDept(String auditDept) {
		this.auditDept = auditDept;
	}

	public Date getDeptSubTime() {
		return this.deptSubTime;
	}

	public void setDeptSubTime(Date deptSubTime) {
		this.deptSubTime = deptSubTime;
	}

	public Date getAuditSubTime() {
		return this.auditSubTime;
	}

	public void setAuditSubTime(Date auditSubTime) {
		this.auditSubTime = auditSubTime;
	}

	public Date getFeedbackTime() {
		return this.feedbackTime;
	}

	public void setFeedbackTime(Date feedbackTime) {
		this.feedbackTime = feedbackTime;
	}

	public String getBatchStatus() {
		return this.batchStatus;
	}

	public void setBatchStatus(String batchStatus) {
		this.batchStatus = batchStatus;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getBatchType() {
		return this.batchType;
	}

	public void setBatchType(String batchType) {
		this.batchType = batchType;
	}

}
