package com.insigma.siis.local.business.audit;
// Generated 2021-4-1 15:43:02 by Hibernate Tools 5.4.14.Final

import java.math.BigInteger;

/**
 * PersonAuditInfo generated by hbm2java
 */
public class PersonAuditInfo implements java.io.Serializable {

	private String oid;
	private String a0000;
	private String a0101;
	private String a0184;
	private String a0192a;
	private String auditType;
	private String auditResult;
	private String auditDetails;
	private String auditRemark;
	private BigInteger PSortid;
	private String jwResult;
	private String zzbGbResult;
	private String zzbJdResult;
	private String xfResult;
	private String fyResult;
	private String jcyResult;
	private String fgwResult;
	private String gaResult;
	private String rlsbResult;
	private String zrzyResult;
	private String sthjResult;
	private String wjwResult;
	private String yjglResult;
	private String sjResult;
	private String scjgResult;
	private String tjResult;
	private String ghResult;
	private String swResult;

	public PersonAuditInfo() {
	}

	public PersonAuditInfo(String oid) {
		this.oid = oid;
	}

	public PersonAuditInfo(String oid, String a0000, String a0101, String a0184, String a0192a, String auditType,
			String auditResult, String auditDetails, String auditRemark, BigInteger PSortid, String jwResult,
			String zzbGbResult, String zzbJdResult, String xfResult, String fyResult, String jcyResult,
			String fgwResult, String gaResult, String rlsbResult, String zrzyResult, String sthjResult,
			String wjwResult, String yjglResult, String sjResult, String scjgResult, String tjResult, String ghResult,
			String swResult) {
		this.oid = oid;
		this.a0000 = a0000;
		this.a0101 = a0101;
		this.a0184 = a0184;
		this.a0192a = a0192a;
		this.auditType = auditType;
		this.auditResult = auditResult;
		this.auditDetails = auditDetails;
		this.auditRemark = auditRemark;
		this.PSortid = PSortid;
		this.jwResult = jwResult;
		this.zzbGbResult = zzbGbResult;
		this.zzbJdResult = zzbJdResult;
		this.xfResult = xfResult;
		this.fyResult = fyResult;
		this.jcyResult = jcyResult;
		this.fgwResult = fgwResult;
		this.gaResult = gaResult;
		this.rlsbResult = rlsbResult;
		this.zrzyResult = zrzyResult;
		this.sthjResult = sthjResult;
		this.wjwResult = wjwResult;
		this.yjglResult = yjglResult;
		this.sjResult = sjResult;
		this.scjgResult = scjgResult;
		this.tjResult = tjResult;
		this.ghResult = ghResult;
		this.swResult = swResult;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getA0101() {
		return this.a0101;
	}

	public void setA0101(String a0101) {
		this.a0101 = a0101;
	}

	public String getA0184() {
		return this.a0184;
	}

	public void setA0184(String a0184) {
		this.a0184 = a0184;
	}

	public String getA0192a() {
		return this.a0192a;
	}

	public void setA0192a(String a0192a) {
		this.a0192a = a0192a;
	}

	public String getAuditType() {
		return this.auditType;
	}

	public void setAuditType(String auditType) {
		this.auditType = auditType;
	}

	public String getAuditResult() {
		return this.auditResult;
	}

	public void setAuditResult(String auditResult) {
		this.auditResult = auditResult;
	}

	public String getAuditDetails() {
		return this.auditDetails;
	}

	public void setAuditDetails(String auditDetails) {
		this.auditDetails = auditDetails;
	}

	public String getAuditRemark() {
		return this.auditRemark;
	}

	public void setAuditRemark(String auditRemark) {
		this.auditRemark = auditRemark;
	}

	public BigInteger getPSortid() {
		return this.PSortid;
	}

	public void setPSortid(BigInteger PSortid) {
		this.PSortid = PSortid;
	}

	public String getJwResult() {
		return this.jwResult;
	}

	public void setJwResult(String jwResult) {
		this.jwResult = jwResult;
	}

	public String getZzbGbResult() {
		return this.zzbGbResult;
	}

	public void setZzbGbResult(String zzbGbResult) {
		this.zzbGbResult = zzbGbResult;
	}

	public String getZzbJdResult() {
		return this.zzbJdResult;
	}

	public void setZzbJdResult(String zzbJdResult) {
		this.zzbJdResult = zzbJdResult;
	}

	public String getXfResult() {
		return this.xfResult;
	}

	public void setXfResult(String xfResult) {
		this.xfResult = xfResult;
	}

	public String getFyResult() {
		return this.fyResult;
	}

	public void setFyResult(String fyResult) {
		this.fyResult = fyResult;
	}

	public String getJcyResult() {
		return this.jcyResult;
	}

	public void setJcyResult(String jcyResult) {
		this.jcyResult = jcyResult;
	}

	public String getFgwResult() {
		return this.fgwResult;
	}

	public void setFgwResult(String fgwResult) {
		this.fgwResult = fgwResult;
	}

	public String getGaResult() {
		return this.gaResult;
	}

	public void setGaResult(String gaResult) {
		this.gaResult = gaResult;
	}

	public String getRlsbResult() {
		return this.rlsbResult;
	}

	public void setRlsbResult(String rlsbResult) {
		this.rlsbResult = rlsbResult;
	}

	public String getZrzyResult() {
		return this.zrzyResult;
	}

	public void setZrzyResult(String zrzyResult) {
		this.zrzyResult = zrzyResult;
	}

	public String getSthjResult() {
		return this.sthjResult;
	}

	public void setSthjResult(String sthjResult) {
		this.sthjResult = sthjResult;
	}

	public String getWjwResult() {
		return this.wjwResult;
	}

	public void setWjwResult(String wjwResult) {
		this.wjwResult = wjwResult;
	}

	public String getYjglResult() {
		return this.yjglResult;
	}

	public void setYjglResult(String yjglResult) {
		this.yjglResult = yjglResult;
	}

	public String getSjResult() {
		return this.sjResult;
	}

	public void setSjResult(String sjResult) {
		this.sjResult = sjResult;
	}

	public String getScjgResult() {
		return this.scjgResult;
	}

	public void setScjgResult(String scjgResult) {
		this.scjgResult = scjgResult;
	}

	public String getTjResult() {
		return this.tjResult;
	}

	public void setTjResult(String tjResult) {
		this.tjResult = tjResult;
	}

	public String getGhResult() {
		return this.ghResult;
	}

	public void setGhResult(String ghResult) {
		this.ghResult = ghResult;
	}

	public String getSwResult() {
		return this.swResult;
	}

	public void setSwResult(String swResult) {
		this.swResult = swResult;
	}

}
