package com.insigma.siis.local.business.entity.a00hz;
// Generated 2020-10-20 15:57:21 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * HzMntpOrgQxs generated by hbm2java
 */
public class HzMntpOrgQxs implements java.io.Serializable {

	private String b01id;
	private String b0101;
	private String b0111;
	private String bzdw;
	private String bzzf;
	private String bzrd;
	private String bzzx;
	private String bzspdw;
	private String bzspzf;
	private String bzsprd;
	private String bzspzx;
	private String fy;
	private String jcy;
	private String fysp;
	private String jcysp;
	private String bz;
	private String b0236;
	private String b0104;
	private String bztype;
	private String b01idfrom;
	private String mntp00;

	public String getMntp00() {
		return mntp00;
	}

	public void setMntp00(String mntp00) {
		this.mntp00 = mntp00;
	}
	public HzMntpOrgQxs() {
	}

	public HzMntpOrgQxs(String b01id, String b0111) {
		this.b01id = b01id;
		this.b0111 = b0111;
	}


	public String getB01id() {
		return this.b01id;
	}

	public void setB01id(String b01id) {
		this.b01id = b01id;
	}

	public String getB0101() {
		return this.b0101;
	}

	public void setB0101(String b0101) {
		this.b0101 = b0101;
	}

	public String getB0111() {
		return this.b0111;
	}

	public void setB0111(String b0111) {
		this.b0111 = b0111;
	}


	public String getBzdw() {
		return bzdw;
	}

	public void setBzdw(String bzdw) {
		this.bzdw = bzdw;
	}

	public String getBzzf() {
		return bzzf;
	}

	public void setBzzf(String bzzf) {
		this.bzzf = bzzf;
	}

	public String getBzrd() {
		return bzrd;
	}

	public void setBzrd(String bzrd) {
		this.bzrd = bzrd;
	}

	public String getBzzx() {
		return bzzx;
	}

	public void setBzzx(String bzzx) {
		this.bzzx = bzzx;
	}

	public String getBzspdw() {
		return bzspdw;
	}

	public void setBzspdw(String bzspdw) {
		this.bzspdw = bzspdw;
	}

	public String getBzspzf() {
		return bzspzf;
	}

	public void setBzspzf(String bzspzf) {
		this.bzspzf = bzspzf;
	}

	public String getBzsprd() {
		return bzsprd;
	}

	public void setBzsprd(String bzsprd) {
		this.bzsprd = bzsprd;
	}

	public String getBzspzx() {
		return bzspzx;
	}

	public void setBzspzx(String bzspzx) {
		this.bzspzx = bzspzx;
	}

	public String getFy() {
		return fy;
	}

	public void setFy(String fy) {
		this.fy = fy;
	}

	public String getJcy() {
		return jcy;
	}

	public void setJcy(String jcy) {
		this.jcy = jcy;
	}

	public String getFysp() {
		return fysp;
	}

	public void setFysp(String fysp) {
		this.fysp = fysp;
	}

	public String getJcysp() {
		return jcysp;
	}

	public void setJcysp(String jcysp) {
		this.jcysp = jcysp;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getB0236() {
		return this.b0236;
	}

	public void setB0236(String b0236) {
		this.b0236 = b0236;
	}

	public String getB0104() {
		return this.b0104;
	}

	public void setB0104(String b0104) {
		this.b0104 = b0104;
	}

	public String getBztype() {
		return this.bztype;
	}

	public void setBztype(String bztype) {
		this.bztype = bztype;
	}

	public String getB01idfrom() {
		return this.b01idfrom;
	}

	public void setB01idfrom(String b01idfrom) {
		this.b01idfrom = b01idfrom;
	}

}
