package com.insigma.siis.local.business.entity.a00hz;
// Generated 2020-10-20 15:57:21 by Hibernate Tools 3.2.2.GA

/**
 * HzMntpOrgQt generated by hbm2java
 */
public class HzMntpOrgQt implements java.io.Serializable {

	private String b01id;
	private String jgmc;
	private String b0111;
	private String zzhd;
	private String zzsp;
	private String fzhd;
	private String fzsp;
	private String zshd;
	private String zssp;
	private String bzzs;
	private String bz;
	private String b0234;
	private String b0235;
	private String b0236;
	private String b0104;
	private String bztype;
	private String b01idfrom;
	private String mntp00;

	public String getMntp00() {
		return mntp00;
	}

	public void setMntp00(String mntp00) {
		this.mntp00 = mntp00;
	}

	public HzMntpOrgQt() {
	}

	public HzMntpOrgQt(String b01id, String b0111) {
		this.b01id = b01id;
		this.b0111 = b0111;
	}


	public String getB01id() {
		return this.b01id;
	}

	public void setB01id(String b01id) {
		this.b01id = b01id;
	}

	public String getJgmc() {
		return this.jgmc;
	}

	public void setJgmc(String jgmc) {
		this.jgmc = jgmc;
	}

	public String getB0111() {
		return this.b0111;
	}

	public void setB0111(String b0111) {
		this.b0111 = b0111;
	}


	public String getZzhd() {
		return zzhd;
	}

	public void setZzhd(String zzhd) {
		this.zzhd = zzhd;
	}

	public String getZzsp() {
		return zzsp;
	}

	public void setZzsp(String zzsp) {
		this.zzsp = zzsp;
	}

	public String getFzhd() {
		return fzhd;
	}

	public void setFzhd(String fzhd) {
		this.fzhd = fzhd;
	}

	public String getFzsp() {
		return fzsp;
	}

	public void setFzsp(String fzsp) {
		this.fzsp = fzsp;
	}

	public String getZshd() {
		return zshd;
	}

	public void setZshd(String zshd) {
		this.zshd = zshd;
	}

	public String getZssp() {
		return zssp;
	}

	public void setZssp(String zssp) {
		this.zssp = zssp;
	}

	public String getBzzs() {
		return bzzs;
	}

	public void setBzzs(String bzzs) {
		this.bzzs = bzzs;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getB0234() {
		return this.b0234;
	}

	public void setB0234(String b0234) {
		this.b0234 = b0234;
	}

	public String getB0235() {
		return this.b0235;
	}

	public void setB0235(String b0235) {
		this.b0235 = b0235;
	}

	public String getB0236() {
		return this.b0236;
	}

	public void setB0236(String b0236) {
		this.b0236 = b0236;
	}

	public String getB0104() {
		return this.b0104;
	}

	public void setB0104(String b0104) {
		this.b0104 = b0104;
	}

	public String getBztype() {
		return this.bztype;
	}

	public void setBztype(String bztype) {
		this.bztype = bztype;
	}

	public String getB01idfrom() {
		return this.b01idfrom;
	}

	public void setB01idfrom(String b01idfrom) {
		this.b01idfrom = b01idfrom;
	}

}
