package com.insigma.siis.local.business.entity.a00hz;
// Generated 2020-8-11 10:35:36 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * HzTphjZw generated by hbm2java
 */
public class HzTphjZw implements java.io.Serializable {

	private String tpzw00;
	private String tp0100;
	private String tpzw01;
	private BigDecimal fxyp07;
	private String b01id;
	private BigDecimal tpzw02;
	private Date tpzw03;
	private String tpzw04;
	private String tpzw05;
	private String ynId;
	private String tp0116;
	private String gwcode;
	private String zjcode;
	private String zwcode;
	private String a0219;
	private String a0201d;
	private String a0201e;
	private String iscount;
	private String status;

	public HzTphjZw() {
	}

	public HzTphjZw(String tpzw00) {
		this.tpzw00 = tpzw00;
	}

	public HzTphjZw(String tpzw00, String tp0100, String tpzw01, BigDecimal fxyp07, String b01id, BigDecimal tpzw02,
			Date tpzw03, String tpzw04, String tpzw05, String ynId, String tp0116, String gwcode, String zjcode,
			String zwcode, String a0219, String a0201d, String a0201e, String iscount, String status) {
		this.tpzw00 = tpzw00;
		this.tp0100 = tp0100;
		this.tpzw01 = tpzw01;
		this.fxyp07 = fxyp07;
		this.b01id = b01id;
		this.tpzw02 = tpzw02;
		this.tpzw03 = tpzw03;
		this.tpzw04 = tpzw04;
		this.tpzw05 = tpzw05;
		this.ynId = ynId;
		this.tp0116 = tp0116;
		this.gwcode = gwcode;
		this.zjcode = zjcode;
		this.zwcode = zwcode;
		this.a0219 = a0219;
		this.a0201d = a0201d;
		this.a0201e = a0201e;
		this.iscount = iscount;
		this.status = status;
	}

	public String getTpzw00() {
		return this.tpzw00;
	}

	public void setTpzw00(String tpzw00) {
		this.tpzw00 = tpzw00;
	}

	public String getTp0100() {
		return this.tp0100;
	}

	public void setTp0100(String tp0100) {
		this.tp0100 = tp0100;
	}

	public String getTpzw01() {
		return this.tpzw01;
	}

	public void setTpzw01(String tpzw01) {
		this.tpzw01 = tpzw01;
	}

	public BigDecimal getFxyp07() {
		return this.fxyp07;
	}

	public void setFxyp07(BigDecimal fxyp07) {
		this.fxyp07 = fxyp07;
	}

	public String getB01id() {
		return this.b01id;
	}

	public void setB01id(String b01id) {
		this.b01id = b01id;
	}

	public BigDecimal getTpzw02() {
		return this.tpzw02;
	}

	public void setTpzw02(BigDecimal tpzw02) {
		this.tpzw02 = tpzw02;
	}

	public Date getTpzw03() {
		return this.tpzw03;
	}

	public void setTpzw03(Date tpzw03) {
		this.tpzw03 = tpzw03;
	}

	public String getTpzw04() {
		return this.tpzw04;
	}

	public void setTpzw04(String tpzw04) {
		this.tpzw04 = tpzw04;
	}

	public String getTpzw05() {
		return this.tpzw05;
	}

	public void setTpzw05(String tpzw05) {
		this.tpzw05 = tpzw05;
	}

	public String getYnId() {
		return this.ynId;
	}

	public void setYnId(String ynId) {
		this.ynId = ynId;
	}

	public String getTp0116() {
		return this.tp0116;
	}

	public void setTp0116(String tp0116) {
		this.tp0116 = tp0116;
	}

	public String getGwcode() {
		return this.gwcode;
	}

	public void setGwcode(String gwcode) {
		this.gwcode = gwcode;
	}

	public String getZjcode() {
		return this.zjcode;
	}

	public void setZjcode(String zjcode) {
		this.zjcode = zjcode;
	}

	public String getZwcode() {
		return this.zwcode;
	}

	public void setZwcode(String zwcode) {
		this.zwcode = zwcode;
	}

	public String getA0219() {
		return this.a0219;
	}

	public void setA0219(String a0219) {
		this.a0219 = a0219;
	}

	public String getA0201d() {
		return this.a0201d;
	}

	public void setA0201d(String a0201d) {
		this.a0201d = a0201d;
	}

	public String getA0201e() {
		return this.a0201e;
	}

	public void setA0201e(String a0201e) {
		this.a0201e = a0201e;
	}

	public String getIscount() {
		return this.iscount;
	}

	public void setIscount(String iscount) {
		this.iscount = iscount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
