package com.insigma.siis.local.business.hzentity;
// Generated 2020-8-31 16:06:27 by Hibernate Tools 3.2.2.GA

/**
 * B01ZzsLd generated by hbm2java
 */
public class B01ZzsLd implements java.io.Serializable {

	private String ld00;
	private String zzs00;
	private String ld01;
	private String a0000;
	private String ld02;
	private String ld03;
	private String ld04;

	public B01ZzsLd() {
	}

	public B01ZzsLd(String ld00, String zzs00) {
		this.ld00 = ld00;
		this.zzs00 = zzs00;
	}

	public B01ZzsLd(String ld00, String zzs00, String ld01, String a0000, String ld02, String ld03, String ld04) {
		this.ld00 = ld00;
		this.zzs00 = zzs00;
		this.ld01 = ld01;
		this.a0000 = a0000;
		this.ld02 = ld02;
		this.ld03 = ld03;
		this.ld04 = ld04;
	}

	public String getLd00() {
		return this.ld00;
	}

	public void setLd00(String ld00) {
		this.ld00 = ld00;
	}

	public String getZzs00() {
		return this.zzs00;
	}

	public void setZzs00(String zzs00) {
		this.zzs00 = zzs00;
	}

	public String getLd01() {
		return this.ld01;
	}

	public void setLd01(String ld01) {
		this.ld01 = ld01;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getLd02() {
		return this.ld02;
	}

	public void setLd02(String ld02) {
		this.ld02 = ld02;
	}

	public String getLd03() {
		return this.ld03;
	}

	public void setLd03(String ld03) {
		this.ld03 = ld03;
	}

	public String getLd04() {
		return this.ld04;
	}

	public void setLd04(String ld04) {
		this.ld04 = ld04;
	}

}
