package com.insigma.siis.local.business.hzentity;
// Generated 2020-8-31 16:06:27 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Clob;

/**
 * B01Zzs generated by hbm2java
 */
public class B01Zzs implements java.io.Serializable {

	private String zzs00;
	private String b01id;
	private String zzs01;
	private java.lang.String zzs02;
	private String zzs03;
	private java.lang.Long zzs04;
	private java.lang.Long zzs05;
	private java.lang.Long zzs06;
	private String zzs07;
	private java.lang.Long zzs08;
	private java.lang.Long zzs09;
	private java.lang.Long zzs10;

	public B01Zzs() {
	}

	public String getZzs00() {
		return zzs00;
	}

	public void setZzs00(String zzs00) {
		this.zzs00 = zzs00;
	}

	public String getB01id() {
		return b01id;
	}

	public void setB01id(String b01id) {
		this.b01id = b01id;
	}

	public String getZzs01() {
		return zzs01;
	}

	public void setZzs01(String zzs01) {
		this.zzs01 = zzs01;
	}

	public java.lang.String getZzs02() {
		return zzs02;
	}

	public void setZzs02(java.lang.String zzs02) {
		this.zzs02 = zzs02;
	}

	public String getZzs03() {
		return zzs03;
	}

	public void setZzs03(String zzs03) {
		this.zzs03 = zzs03;
	}

	public java.lang.Long getZzs04() {
		return zzs04;
	}

	public void setZzs04(java.lang.Long zzs04) {
		this.zzs04 = zzs04;
	}

	public java.lang.Long getZzs05() {
		return zzs05;
	}

	public void setZzs05(java.lang.Long zzs05) {
		this.zzs05 = zzs05;
	}

	public java.lang.Long getZzs06() {
		return zzs06;
	}

	public void setZzs06(java.lang.Long zzs06) {
		this.zzs06 = zzs06;
	}

	public String getZzs07() {
		return zzs07;
	}

	public void setZzs07(String zzs07) {
		this.zzs07 = zzs07;
	}

	public java.lang.Long getZzs08() {
		return zzs08;
	}

	public void setZzs08(java.lang.Long zzs08) {
		this.zzs08 = zzs08;
	}

	public java.lang.Long getZzs09() {
		return zzs09;
	}

	public void setZzs09(java.lang.Long zzs09) {
		this.zzs09 = zzs09;
	}

	public java.lang.Long getZzs10() {
		return zzs10;
	}

	public void setZzs10(java.lang.Long zzs10) {
		this.zzs10 = zzs10;
	}

	

}
