package com.insigma.siis.local.business.entity;
// Generated 2018-8-21 20:17:36 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * A11 generated by hbm2java
 */
public class A11 implements java.io.Serializable {

	private String a1100;
	private String a0000;
	private String a1101;
	private String a1104;
	private String a1107;
	private BigDecimal a1107a;
	private BigDecimal a1107b;
	private String a1111;
	private String a1114;
	private String a1121a;
	private String a1127;
	private String a1131;
	private String a1134;
	private String a1151;
	private String updated;
	private BigDecimal a1108;
	private BigDecimal a1107c;
	private String g02003;
	private String a1108a;
	private String a1108b;
	private String g11003;
	private String g11004;
	private String g11005;
	private String g11006;
	private String g11007;
	private String g11008;
	private String g11009;
	private String g11010;
	private String g11011;
	private String g11012;
	private String g11013;
	private String g11014;
	private String g11015;
	private String g11020;
	private String g11021;
	private String g11022;
	private String g11023;
	private String g11024;
	public String getG11020() {
		return g11020;
	}

	public void setG11020(String g11020) {
		this.g11020 = g11020;
	}

	public String getG11021() {
		return g11021;
	}

	public void setG11021(String g11021) {
		this.g11021 = g11021;
	}

	public String getG11022() {
		return g11022;
	}

	public void setG11022(String g11022) {
		this.g11022 = g11022;
	}

	public String getG11023() {
		return g11023;
	}

	public void setG11023(String g11023) {
		this.g11023 = g11023;
	}

	public String getG11024() {
		return g11024;
	}

	public void setG11024(String g11024) {
		this.g11024 = g11024;
	}

	public String getG11025() {
		return g11025;
	}

	public void setG11025(String g11025) {
		this.g11025 = g11025;
	}

	private String g11025;
	

	public A11() {
	}

	public A11(String a1100, String a0000) {
		this.a1100 = a1100;
		this.a0000 = a0000;
	}

	public A11(String a1100, String a0000, String a1101, String a1104, String a1107, BigDecimal a1107a,
			BigDecimal a1107b, String a1111, String a1114, String a1121a, String a1127, String a1131, String a1134,
			String a1151, String updated, BigDecimal a1108, BigDecimal a1107c, String g02003, String a1108a,
			String a1108b, String g11003, String g11004, String g11005, String g11006, String g11007, String g11008,
			String g11009, String g11010, String g11011, String g11012, String g11013, String g11014, String g11015) {
		this.a1100 = a1100;
		this.a0000 = a0000;
		this.a1101 = a1101;
		this.a1104 = a1104;
		this.a1107 = a1107;
		this.a1107a = a1107a;
		this.a1107b = a1107b;
		this.a1111 = a1111;
		this.a1114 = a1114;
		this.a1121a = a1121a;
		this.a1127 = a1127;
		this.a1131 = a1131;
		this.a1134 = a1134;
		this.a1151 = a1151;
		this.updated = updated;
		this.a1108 = a1108;
		this.a1107c = a1107c;
		this.g02003 = g02003;
		this.a1108a = a1108a;
		this.a1108b = a1108b;
		this.g11003 = g11003;
		this.g11004 = g11004;
		this.g11005 = g11005;
		this.g11006 = g11006;
		this.g11007 = g11007;
		this.g11008 = g11008;
		this.g11009 = g11009;
		this.g11010 = g11010;
		this.g11011 = g11011;
		this.g11012 = g11012;
		this.g11013 = g11013;
		this.g11014 = g11014;
		this.g11015 = g11015;
	}

	public String getA1100() {
		return this.a1100;
	}

	public void setA1100(String a1100) {
		this.a1100 = a1100;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getA1101() {
		return this.a1101;
	}

	public void setA1101(String a1101) {
		this.a1101 = a1101;
	}

	public String getA1104() {
		return this.a1104;
	}

	public void setA1104(String a1104) {
		this.a1104 = a1104;
	}

	public String getA1107() {
		return this.a1107;
	}

	public void setA1107(String a1107) {
		this.a1107 = a1107;
	}

	public BigDecimal getA1107a() {
		return this.a1107a;
	}

	public void setA1107a(BigDecimal a1107a) {
		this.a1107a = a1107a;
	}

	public BigDecimal getA1107b() {
		return this.a1107b;
	}

	public void setA1107b(BigDecimal a1107b) {
		this.a1107b = a1107b;
	}

	public String getA1111() {
		return this.a1111;
	}

	public void setA1111(String a1111) {
		this.a1111 = a1111;
	}

	public String getA1114() {
		return this.a1114;
	}

	public void setA1114(String a1114) {
		this.a1114 = a1114;
	}

	public String getA1121a() {
		return this.a1121a;
	}

	public void setA1121a(String a1121a) {
		this.a1121a = a1121a;
	}

	public String getA1127() {
		return this.a1127;
	}

	public void setA1127(String a1127) {
		this.a1127 = a1127;
	}

	public String getA1131() {
		return this.a1131;
	}

	public void setA1131(String a1131) {
		this.a1131 = a1131;
	}

	public String getA1134() {
		return this.a1134;
	}

	public void setA1134(String a1134) {
		this.a1134 = a1134;
	}

	public String getA1151() {
		return this.a1151;
	}

	public void setA1151(String a1151) {
		this.a1151 = a1151;
	}

	public String getUpdated() {
		return this.updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	public BigDecimal getA1108() {
		return this.a1108;
	}

	public void setA1108(BigDecimal a1108) {
		this.a1108 = a1108;
	}

	public BigDecimal getA1107c() {
		return this.a1107c;
	}

	public void setA1107c(BigDecimal a1107c) {
		this.a1107c = a1107c;
	}

	public String getG02003() {
		return this.g02003;
	}

	public void setG02003(String g02003) {
		this.g02003 = g02003;
	}

	public String getA1108a() {
		return this.a1108a;
	}

	public void setA1108a(String a1108a) {
		this.a1108a = a1108a;
	}

	public String getA1108b() {
		return this.a1108b;
	}

	public void setA1108b(String a1108b) {
		this.a1108b = a1108b;
	}

	public String getG11003() {
		return this.g11003;
	}

	public void setG11003(String g11003) {
		this.g11003 = g11003;
	}

	public String getG11004() {
		return this.g11004;
	}

	public void setG11004(String g11004) {
		this.g11004 = g11004;
	}

	public String getG11005() {
		return this.g11005;
	}

	public void setG11005(String g11005) {
		this.g11005 = g11005;
	}

	public String getG11006() {
		return this.g11006;
	}

	public void setG11006(String g11006) {
		this.g11006 = g11006;
	}

	public String getG11007() {
		return this.g11007;
	}

	public void setG11007(String g11007) {
		this.g11007 = g11007;
	}

	public String getG11008() {
		return this.g11008;
	}

	public void setG11008(String g11008) {
		this.g11008 = g11008;
	}

	public String getG11009() {
		return this.g11009;
	}

	public void setG11009(String g11009) {
		this.g11009 = g11009;
	}

	public String getG11010() {
		return this.g11010;
	}

	public void setG11010(String g11010) {
		this.g11010 = g11010;
	}

	public String getG11011() {
		return this.g11011;
	}

	public void setG11011(String g11011) {
		this.g11011 = g11011;
	}

	public String getG11012() {
		return this.g11012;
	}

	public void setG11012(String g11012) {
		this.g11012 = g11012;
	}

	public String getG11013() {
		return this.g11013;
	}

	public void setG11013(String g11013) {
		this.g11013 = g11013;
	}

	public String getG11014() {
		return this.g11014;
	}

	public void setG11014(String g11014) {
		this.g11014 = g11014;
	}

	public String getG11015() {
		return this.g11015;
	}

	public void setG11015(String g11015) {
		this.g11015 = g11015;
	}

	public void setA1107c(double a1107c) {
		// TODO Auto-generated method stub
		this.a1107c = new BigDecimal(a1107c);
	}

	public void setA1108(double a1108) {
		// TODO Auto-generated method stub
		this.a1108 = new BigDecimal(a1108);
	}

	public void setA1107a(long a1107a) {
		// TODO Auto-generated method stub
		this.a1107a = new BigDecimal(a1107a);
		
	}

	public void setA1107b(long a1107b) {
		this.a1107b = new BigDecimal(a1107b);
		
	}

}
