package com.insigma.siis.local.business.entity;
// Generated 2018-8-21 11:02:42 by Hibernate Tools 3.2.2.GA

/**
 * A80 generated by hbm2java
 */
public class A80 implements java.io.Serializable,Cloneable {

	private String a0000;
	private String a29314;
	private String a03033;
	private String a29321;
	private String a29324a;
	private String a29324b;
	private String a29327a;
	private String a29327b;
	private Byte a29334;
	private String a29337;
	private String a39061;
	private String a39064;
	private String a39067;
	private String a39071;
	private String a44027;
	private Byte a39077;
	private String a44031;
	private Byte a39084;

	public A80() {
	}

	public A80(String a0000) {
		this.a0000 = a0000;
	}
	@Override
	public A80 clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (A80)super.clone();
	}
	public A80(String a0000, String a29314, String a03033, String a29321, String a29324a, String a29324b,
			String a29327a, String a29327b, Byte a29334, String a29337, String a39061, String a39064, String a39067,
			String a39071, String a44027, Byte a39077, String a44031, Byte a39084) {
		this.a0000 = a0000;
		this.a29314 = a29314;
		this.a03033 = a03033;
		this.a29321 = a29321;
		this.a29324a = a29324a;
		this.a29324b = a29324b;
		this.a29327a = a29327a;
		this.a29327b = a29327b;
		this.a29334 = a29334;
		this.a29337 = a29337;
		this.a39061 = a39061;
		this.a39064 = a39064;
		this.a39067 = a39067;
		this.a39071 = a39071;
		this.a44027 = a44027;
		this.a39077 = a39077;
		this.a44031 = a44031;
		this.a39084 = a39084;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getA29314() {
		return this.a29314;
	}

	public void setA29314(String a29314) {
		this.a29314 = a29314;
	}

	public String getA03033() {
		return this.a03033;
	}

	public void setA03033(String a03033) {
		this.a03033 = a03033;
	}

	public String getA29321() {
		return this.a29321;
	}

	public void setA29321(String a29321) {
		this.a29321 = a29321;
	}

	public String getA29324a() {
		return this.a29324a;
	}

	public void setA29324a(String a29324a) {
		this.a29324a = a29324a;
	}

	public String getA29324b() {
		return this.a29324b;
	}

	public void setA29324b(String a29324b) {
		this.a29324b = a29324b;
	}

	public String getA29327a() {
		return this.a29327a;
	}

	public void setA29327a(String a29327a) {
		this.a29327a = a29327a;
	}

	public String getA29327b() {
		return this.a29327b;
	}

	public void setA29327b(String a29327b) {
		this.a29327b = a29327b;
	}

	public Byte getA29334() {
		return this.a29334;
	}

	public void setA29334(Byte a29334) {
		this.a29334 = a29334;
	}

	public String getA29337() {
		return this.a29337;
	}

	public void setA29337(String a29337) {
		this.a29337 = a29337;
	}

	public String getA39061() {
		return this.a39061;
	}

	public void setA39061(String a39061) {
		this.a39061 = a39061;
	}

	public String getA39064() {
		return this.a39064;
	}

	public void setA39064(String a39064) {
		this.a39064 = a39064;
	}

	public String getA39067() {
		return this.a39067;
	}

	public void setA39067(String a39067) {
		this.a39067 = a39067;
	}

	public String getA39071() {
		return this.a39071;
	}

	public void setA39071(String a39071) {
		this.a39071 = a39071;
	}

	public String getA44027() {
		return this.a44027;
	}

	public void setA44027(String a44027) {
		this.a44027 = a44027;
	}

	public Byte getA39077() {
		return this.a39077;
	}

	public void setA39077(Byte a39077) {
		this.a39077 = a39077;
	}

	public String getA44031() {
		return this.a44031;
	}

	public void setA44031(String a44031) {
		this.a44031 = a44031;
	}

	public Byte getA39084() {
		return this.a39084;
	}

	public void setA39084(Byte a39084) {
		this.a39084 = a39084;
	}

}
