package com.insigma.siis.local.business.entity;
// Generated 2018-8-21 11:02:42 by Hibernate Tools 3.2.2.GA

/**
 * A81 generated by hbm2java
 */
public class A81 implements java.io.Serializable,Cloneable {

	private String a0000;
	private String g02001;
	private String a29071;
	private String a29072;
	private String a29341;
	private Byte a29073;
	private String a29344;
	private String a29347a;
	private String a29347b;
	private String a29347c;
	private String a29351b;
	private String a39067;
	private String a44027;
	private Byte a39077;
	private String a44031;
	private Byte a39084;

	public A81() {
	}

	public A81 clone() throws CloneNotSupportedException
	{
		Object object = super.clone();
		return (A81)object;
	}
	
	public A81(String a0000) {
		this.a0000 = a0000;
	}

	public A81(String a0000, String g02001, String a29071, String a29072, String a29341, Byte a29073, String a29344,
			String a29347a, String a29347b, String a29347c, String a29351b, String a39067, String a44027, Byte a39077,
			String a44031, Byte a39084) {
		this.a0000 = a0000;
		this.g02001 = g02001;
		this.a29071 = a29071;
		this.a29072 = a29072;
		this.a29341 = a29341;
		this.a29073 = a29073;
		this.a29344 = a29344;
		this.a29347a = a29347a;
		this.a29347b = a29347b;
		this.a29347c = a29347c;
		this.a29351b = a29351b;
		this.a39067 = a39067;
		this.a44027 = a44027;
		this.a39077 = a39077;
		this.a44031 = a44031;
		this.a39084 = a39084;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getG02001() {
		return this.g02001;
	}

	public void setG02001(String g02001) {
		this.g02001 = g02001;
	}

	public String getA29071() {
		return this.a29071;
	}

	public void setA29071(String a29071) {
		this.a29071 = a29071;
	}

	public String getA29072() {
		return this.a29072;
	}

	public void setA29072(String a29072) {
		this.a29072 = a29072;
	}

	public String getA29341() {
		return this.a29341;
	}

	public void setA29341(String a29341) {
		this.a29341 = a29341;
	}

	public Byte getA29073() {
		return this.a29073;
	}

	public void setA29073(Byte a29073) {
		this.a29073 = a29073;
	}

	public String getA29344() {
		return this.a29344;
	}

	public void setA29344(String a29344) {
		this.a29344 = a29344;
	}

	public String getA29347a() {
		return this.a29347a;
	}

	public void setA29347a(String a29347a) {
		this.a29347a = a29347a;
	}

	public String getA29347b() {
		return this.a29347b;
	}

	public void setA29347b(String a29347b) {
		this.a29347b = a29347b;
	}

	public String getA29347c() {
		return this.a29347c;
	}

	public void setA29347c(String a29347c) {
		this.a29347c = a29347c;
	}

	public String getA29351b() {
		return this.a29351b;
	}

	public void setA29351b(String a29351b) {
		this.a29351b = a29351b;
	}

	public String getA39067() {
		return this.a39067;
	}

	public void setA39067(String a39067) {
		this.a39067 = a39067;
	}

	public String getA44027() {
		return this.a44027;
	}

	public void setA44027(String a44027) {
		this.a44027 = a44027;
	}

	public Byte getA39077() {
		return this.a39077;
	}

	public void setA39077(Byte a39077) {
		this.a39077 = a39077;
	}

	public String getA44031() {
		return this.a44031;
	}

	public void setA44031(String a44031) {
		this.a44031 = a44031;
	}

	public Byte getA39084() {
		return this.a39084;
	}

	public void setA39084(Byte a39084) {
		this.a39084 = a39084;
	}

}
