package com.insigma.siis.local.business.entity;
// Generated 2018-8-21 11:02:42 by Hibernate Tools 3.2.2.GA

/**
 * A82 generated by hbm2java
 */
public class A82 implements java.io.Serializable,Cloneable {

	private String a0000;
	private String a02191;
	private String a29301;
	private String a29304;
	private String a29044;
	private String a29307;

	public A82() {
	}

	public A82(String a0000) {
		this.a0000 = a0000;
	}

	 @Override
	public A82 clone() throws CloneNotSupportedException
	{
		Object object = super.clone();
		return (A82)object;
	}

	public A82(String a0000, String a02191, String a29301, String a29304, String a29044, String a29307) {
		this.a0000 = a0000;
		this.a02191 = a02191;
		this.a29301 = a29301;
		this.a29304 = a29304;
		this.a29044 = a29044;
		this.a29307 = a29307;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getA02191() {
		return this.a02191;
	}

	public void setA02191(String a02191) {
		this.a02191 = a02191;
	}

	public String getA29301() {
		return this.a29301;
	}

	public void setA29301(String a29301) {
		this.a29301 = a29301;
	}

	public String getA29304() {
		return this.a29304;
	}

	public void setA29304(String a29304) {
		this.a29304 = a29304;
	}

	public String getA29044() {
		return this.a29044;
	}

	public void setA29044(String a29044) {
		this.a29044 = a29044;
	}

	public String getA29307() {
		return this.a29307;
	}

	public void setA29307(String a29307) {
		this.a29307 = a29307;
	}

}
