package com.insigma.siis.local.business.entity;
// Generated 2018-8-21 11:02:42 by Hibernate Tools 3.2.2.GA

/**
 * A83 generated by hbm2java
 */
public class A83 implements java.io.Serializable {

	private String a0000;
	private String a02192;
	private String a29311;
	private String g02002;
	private String a29044;
	private String a29041;
	private String a29354;
	private String a44027;
	//private String a39077;
	private Byte a39077;
	private String a44031;
	//private String a39084;
	private Byte a39084;

	public A83() {
	}

	public A83(String a0000) {
		this.a0000 = a0000;
	}

	

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getA02192() {
		return this.a02192;
	}

	public void setA02192(String a02192) {
		this.a02192 = a02192;
	}

	public String getA29311() {
		return this.a29311;
	}

	public void setA29311(String a29311) {
		this.a29311 = a29311;
	}

	public String getG02002() {
		return this.g02002;
	}

	public void setG02002(String g02002) {
		this.g02002 = g02002;
	}

	public String getA29044() {
		return this.a29044;
	}

	public void setA29044(String a29044) {
		this.a29044 = a29044;
	}

	public String getA29041() {
		return this.a29041;
	}

	public void setA29041(String a29041) {
		this.a29041 = a29041;
	}

	public String getA29354() {
		return this.a29354;
	}

	public void setA29354(String a29354) {
		this.a29354 = a29354;
	}

	public String getA44027() {
		return this.a44027;
	}

	public void setA44027(String a44027) {
		this.a44027 = a44027;
	}

	public String getA44031() {
		return this.a44031;
	}

	public void setA44031(String a44031) {
		this.a44031 = a44031;
	}

	public Byte getA39077() {
		return a39077;
	}

	public void setA39077(Byte a39077) {
		this.a39077 = a39077;
	}

	public Byte getA39084() {
		return a39084;
	}

	public void setA39084(Byte a39084) {
		this.a39084 = a39084;
	}

	@Override
	public String toString() {
		return "A83 [a0000=" + a0000 + ", a02192=" + a02192 + ", a29311=" + a29311 + ", g02002=" + g02002 + ", a29044="
				+ a29044 + ", a29041=" + a29041 + ", a29354=" + a29354 + ", a44027=" + a44027 + ", a39077=" + a39077
				+ ", a44031=" + a44031 + ", a39084=" + a39084 + "]";
	}

	

}
