package com.insigma.siis.local.business.entity;
// Generated 2018-8-21 11:02:42 by Hibernate Tools 3.2.2.GA

/**
 * A84 generated by hbm2java
 */
public class A84 implements java.io.Serializable,Cloneable {

	private String a8400;
	private String a0000;
	private String a03011;
	private String a03021;
	private String a03095;
	private String a03027;
	private String a03014;
	private String a03017;
	private String a03018;
	private String a03024;
	private String a84type;

	@Override
	public A84 clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (A84)super.clone();
	}

	public A84() {
	}

	public A84(String a8400, String a0000) {
		this.a8400 = a8400;
		this.a0000 = a0000;
	}

	public A84(String a8400, String a0000, String a03011, String a03021, String a03095, String a03027, String a03014,
			String a03017, String a03018, String a03024, String a84type) {
		this.a8400 = a8400;
		this.a0000 = a0000;
		this.a03011 = a03011;
		this.a03021 = a03021;
		this.a03095 = a03095;
		this.a03027 = a03027;
		this.a03014 = a03014;
		this.a03017 = a03017;
		this.a03018 = a03018;
		this.a03024 = a03024;
		this.a84type = a84type;
	}

	public String getA8400() {
		return this.a8400;
	}

	public void setA8400(String a8400) {
		this.a8400 = a8400;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getA03011() {
		return this.a03011;
	}

	public void setA03011(String a03011) {
		this.a03011 = a03011;
	}

	public String getA03021() {
		return this.a03021;
	}

	public void setA03021(String a03021) {
		this.a03021 = a03021;
	}

	public String getA03095() {
		return this.a03095;
	}

	public void setA03095(String a03095) {
		this.a03095 = a03095;
	}

	public String getA03027() {
		return this.a03027;
	}

	public void setA03027(String a03027) {
		this.a03027 = a03027;
	}

	public String getA03014() {
		return this.a03014;
	}

	public void setA03014(String a03014) {
		this.a03014 = a03014;
	}

	public String getA03017() {
		return this.a03017;
	}

	public void setA03017(String a03017) {
		this.a03017 = a03017;
	}

	public String getA03018() {
		return this.a03018;
	}

	public void setA03018(String a03018) {
		this.a03018 = a03018;
	}

	public String getA03024() {
		return this.a03024;
	}

	public void setA03024(String a03024) {
		this.a03024 = a03024;
	}

	public String getA84type() {
		return this.a84type;
	}

	public void setA84type(String a84type) {
		this.a84type = a84type;
	}

}
