package com.insigma.siis.local.business.entity;
// Generated 2020-5-31 16:29:37 by Hibernate Tools 3.2.2.GA

/**
 * AttrLrzw generated by hbm2java
 */
public class AttrLrzw implements java.io.Serializable ,Cloneable{
	@Override
	public AttrLrzw clone() throws CloneNotSupportedException
	{
		Object object = super.clone();
		return (AttrLrzw)object;
	}
	private String a0000;
	private String attr2101;
	private String attr2102;
	private String attr2103;
	private String attr2104;
	private String attr2105;
	private String attr2106;
	private String attr2107;
	private String attr2108;
	private String attr2201;
	private String attr2202;
	private String attr2203;
	private String attr2204;
	private String attr2205;
	private String attr2206;
	private String attr2207;
	private String attr2208;
	private String attr2209;
	private String attr2301;
	private String attr2302;
	private String attr2303;
	private String attr2304;
	private String attr2305;
	private String attr2306;
	private String attr2307;
	private String attr2308;
	private String attr2401;
	private String attr2402;
	private String attr2403;
	private String attr2404;
	private String attr2405;
	private String attr2406;
	private String attr2407;
	private String attr2408;
	private String attr2409;
	private String attr41;
	private String attr42;
	private String attr43;
	private String attr44;
	private String attr45;
	private String attr46;
	private String attr31;
	private String attr47;
	private String attr48;
	private String attr49;
	private String attr50;
	private String attr05;
	private String attr06;
	private String attr07;
	private String attr19;
	private String attr51;
	private String attr52;
	private String attr13;
	private String attr21;
	private String attr99;
	
	private String attr101;
	private String attr102;
	private String attr103;
	private String attr104;
	private String attr105;
	private String attr106;
	private String attr107;
	private String attr108;
	private String attr109;
	private String attr110;
	private String attr111;
	private String attr112;

	public AttrLrzw() {
	}

	public AttrLrzw(String a0000) {
		this.a0000 = a0000;
	}

	public AttrLrzw(String a0000, String attr2101, String attr2102, String attr2103, String attr2104, String attr2105,
			String attr2106, String attr2107, String attr2108, String attr2201, String attr2202, String attr2203,
			String attr2204, String attr2205, String attr2206, String attr2207, String attr2208, String attr2209,
			String attr2301, String attr2302, String attr2303, String attr2304, String attr2305, String attr2306,
			String attr2307, String attr2308, String attr2401, String attr2402, String attr2403, String attr2404,
			String attr2405, String attr2406, String attr2407, String attr41, String attr42, String attr43,
			String attr44, String attr45, String attr46, String attr31, String attr47, String attr48, String attr49,
			String attr50, String attr05, String attr06, String attr07, String attr19, String attr51, String attr52,
			String attr13, String attr21, String attr99 ,String attr101,String attr102,String attr103,String attr104
			,String attr105,String attr106,String attr107,String attr108,String attr109,String attr110,String attr111
			,String attr112, String attr2408,String attr2409) {
		this.a0000 = a0000;
		this.attr2101 = attr2101;
		this.attr2102 = attr2102;
		this.attr2103 = attr2103;
		this.attr2104 = attr2104;
		this.attr2105 = attr2105;
		this.attr2106 = attr2106;
		this.attr2107 = attr2107;
		this.attr2108 = attr2108;
		this.attr2201 = attr2201;
		this.attr2202 = attr2202;
		this.attr2203 = attr2203;
		this.attr2204 = attr2204;
		this.attr2205 = attr2205;
		this.attr2206 = attr2206;
		this.attr2207 = attr2207;
		this.attr2208 = attr2208;
		this.attr2209 = attr2209;
		this.attr2301 = attr2301;
		this.attr2302 = attr2302;
		this.attr2303 = attr2303;
		this.attr2304 = attr2304;
		this.attr2305 = attr2305;
		this.attr2306 = attr2306;
		this.attr2307 = attr2307;
		this.attr2308 = attr2308;
		this.attr2401 = attr2401;
		this.attr2402 = attr2402;
		this.attr2403 = attr2403;
		this.attr2404 = attr2404;
		this.attr2405 = attr2405;
		this.attr2406 = attr2406;
		this.attr2407 = attr2407;
		this.attr41 = attr41;
		this.attr42 = attr42;
		this.attr43 = attr43;
		this.attr44 = attr44;
		this.attr45 = attr45;
		this.attr46 = attr46;
		this.attr31 = attr31;
		this.attr47 = attr47;
		this.attr48 = attr48;
		this.attr49 = attr49;
		this.attr50 = attr50;
		this.attr05 = attr05;
		this.attr06 = attr06;
		this.attr07 = attr07;
		this.attr19 = attr19;
		this.attr51 = attr51;
		this.attr52 = attr52;
		this.attr13 = attr13;
		this.attr21 = attr21;
		this.attr99 = attr99;
		this.attr101 = attr101;
		this.attr102 = attr102;
		this.attr103 = attr103;
		this.attr104 = attr104;
		this.attr105 = attr105;
		this.attr106 = attr106;
		this.attr107 = attr107;
		this.attr108 = attr108;
		this.attr109 = attr109;
		this.attr110 = attr110;
		this.attr111 = attr111;
		this.attr112 = attr112;
		this.attr2408=attr2408;
		this.attr2409=attr2409;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}
	public String getAttr2408() {
		return attr2408;
	}

	public void setAttr2408(String attr2408) {
		this.attr2408 = attr2408;
	}

	public String getAttr2409() {
		return attr2409;
	}

	public void setAttr2409(String attr2409) {
		this.attr2409 = attr2409;
	}
	public String getAttr2101() {
		return this.attr2101;
	}

	public void setAttr2101(String attr2101) {
		this.attr2101 = attr2101;
	}

	public String getAttr2102() {
		return this.attr2102;
	}

	public void setAttr2102(String attr2102) {
		this.attr2102 = attr2102;
	}

	public String getAttr2103() {
		return this.attr2103;
	}

	public void setAttr2103(String attr2103) {
		this.attr2103 = attr2103;
	}

	public String getAttr2104() {
		return this.attr2104;
	}

	public void setAttr2104(String attr2104) {
		this.attr2104 = attr2104;
	}

	public String getAttr2105() {
		return this.attr2105;
	}

	public void setAttr2105(String attr2105) {
		this.attr2105 = attr2105;
	}

	public String getAttr2106() {
		return this.attr2106;
	}

	public void setAttr2106(String attr2106) {
		this.attr2106 = attr2106;
	}

	public String getAttr2107() {
		return this.attr2107;
	}

	public void setAttr2107(String attr2107) {
		this.attr2107 = attr2107;
	}

	public String getAttr2108() {
		return this.attr2108;
	}

	public void setAttr2108(String attr2108) {
		this.attr2108 = attr2108;
	}

	public String getAttr2201() {
		return this.attr2201;
	}

	public void setAttr2201(String attr2201) {
		this.attr2201 = attr2201;
	}

	public String getAttr2202() {
		return this.attr2202;
	}

	public void setAttr2202(String attr2202) {
		this.attr2202 = attr2202;
	}

	public String getAttr2203() {
		return this.attr2203;
	}

	public void setAttr2203(String attr2203) {
		this.attr2203 = attr2203;
	}

	public String getAttr2204() {
		return this.attr2204;
	}

	public void setAttr2204(String attr2204) {
		this.attr2204 = attr2204;
	}

	public String getAttr2205() {
		return this.attr2205;
	}

	public void setAttr2205(String attr2205) {
		this.attr2205 = attr2205;
	}

	public String getAttr2206() {
		return this.attr2206;
	}

	public void setAttr2206(String attr2206) {
		this.attr2206 = attr2206;
	}

	public String getAttr2207() {
		return this.attr2207;
	}

	public void setAttr2207(String attr2207) {
		this.attr2207 = attr2207;
	}

	public String getAttr2208() {
		return this.attr2208;
	}

	public void setAttr2208(String attr2208) {
		this.attr2208 = attr2208;
	}

	public String getAttr2209() {
		return this.attr2209;
	}

	public void setAttr2209(String attr2209) {
		this.attr2209 = attr2209;
	}

	public String getAttr2301() {
		return this.attr2301;
	}

	public void setAttr2301(String attr2301) {
		this.attr2301 = attr2301;
	}

	public String getAttr2302() {
		return this.attr2302;
	}

	public void setAttr2302(String attr2302) {
		this.attr2302 = attr2302;
	}

	public String getAttr2303() {
		return this.attr2303;
	}

	public void setAttr2303(String attr2303) {
		this.attr2303 = attr2303;
	}

	public String getAttr2304() {
		return this.attr2304;
	}

	public void setAttr2304(String attr2304) {
		this.attr2304 = attr2304;
	}

	public String getAttr2305() {
		return this.attr2305;
	}

	public void setAttr2305(String attr2305) {
		this.attr2305 = attr2305;
	}

	public String getAttr2306() {
		return this.attr2306;
	}

	public void setAttr2306(String attr2306) {
		this.attr2306 = attr2306;
	}

	public String getAttr2307() {
		return this.attr2307;
	}

	public void setAttr2307(String attr2307) {
		this.attr2307 = attr2307;
	}

	public String getAttr2308() {
		return this.attr2308;
	}

	public void setAttr2308(String attr2308) {
		this.attr2308 = attr2308;
	}

	public String getAttr2401() {
		return this.attr2401;
	}

	public void setAttr2401(String attr2401) {
		this.attr2401 = attr2401;
	}

	public String getAttr2402() {
		return this.attr2402;
	}

	public void setAttr2402(String attr2402) {
		this.attr2402 = attr2402;
	}

	public String getAttr2403() {
		return this.attr2403;
	}

	public void setAttr2403(String attr2403) {
		this.attr2403 = attr2403;
	}

	public String getAttr2404() {
		return this.attr2404;
	}

	public void setAttr2404(String attr2404) {
		this.attr2404 = attr2404;
	}

	public String getAttr2405() {
		return this.attr2405;
	}

	public void setAttr2405(String attr2405) {
		this.attr2405 = attr2405;
	}

	public String getAttr2406() {
		return this.attr2406;
	}

	public void setAttr2406(String attr2406) {
		this.attr2406 = attr2406;
	}

	public String getAttr2407() {
		return this.attr2407;
	}

	public void setAttr2407(String attr2407) {
		this.attr2407 = attr2407;
	}

	public String getAttr41() {
		return this.attr41;
	}

	public void setAttr41(String attr41) {
		this.attr41 = attr41;
	}

	public String getAttr42() {
		return this.attr42;
	}

	public void setAttr42(String attr42) {
		this.attr42 = attr42;
	}

	public String getAttr43() {
		return this.attr43;
	}

	public void setAttr43(String attr43) {
		this.attr43 = attr43;
	}

	public String getAttr44() {
		return this.attr44;
	}

	public void setAttr44(String attr44) {
		this.attr44 = attr44;
	}

	public String getAttr45() {
		return this.attr45;
	}

	public void setAttr45(String attr45) {
		this.attr45 = attr45;
	}

	public String getAttr46() {
		return this.attr46;
	}

	public void setAttr46(String attr46) {
		this.attr46 = attr46;
	}

	public String getAttr31() {
		return this.attr31;
	}

	public void setAttr31(String attr31) {
		this.attr31 = attr31;
	}

	public String getAttr47() {
		return this.attr47;
	}

	public void setAttr47(String attr47) {
		this.attr47 = attr47;
	}

	public String getAttr48() {
		return this.attr48;
	}

	public void setAttr48(String attr48) {
		this.attr48 = attr48;
	}

	public String getAttr49() {
		return this.attr49;
	}

	public void setAttr49(String attr49) {
		this.attr49 = attr49;
	}

	public String getAttr50() {
		return this.attr50;
	}

	public void setAttr50(String attr50) {
		this.attr50 = attr50;
	}

	public String getAttr05() {
		return this.attr05;
	}

	public void setAttr05(String attr05) {
		this.attr05 = attr05;
	}

	public String getAttr06() {
		return this.attr06;
	}

	public void setAttr06(String attr06) {
		this.attr06 = attr06;
	}

	public String getAttr07() {
		return this.attr07;
	}

	public void setAttr07(String attr07) {
		this.attr07 = attr07;
	}

	public String getAttr19() {
		return this.attr19;
	}

	public void setAttr19(String attr19) {
		this.attr19 = attr19;
	}

	public String getAttr51() {
		return this.attr51;
	}

	public void setAttr51(String attr51) {
		this.attr51 = attr51;
	}

	public String getAttr52() {
		return this.attr52;
	}

	public void setAttr52(String attr52) {
		this.attr52 = attr52;
	}

	public String getAttr13() {
		return this.attr13;
	}

	public void setAttr13(String attr13) {
		this.attr13 = attr13;
	}

	public String getAttr21() {
		return this.attr21;
	}

	public void setAttr21(String attr21) {
		this.attr21 = attr21;
	}

	public String getAttr99() {
		return this.attr99;
	}

	public void setAttr99(String attr99) {
		this.attr99 = attr99;
	}

	public String getAttr101() {
		return this.attr101;
	}

	public void setAttr101(String attr101) {
		this.attr101 = attr101;
	}

	public String getAttr102() {
		return this.attr102;
	}

	public void setAttr102(String attr102) {
		this.attr102 = attr102;
	}

	public String getAttr103() {
		return this.attr103;
	}

	public void setAttr103(String attr103) {
		this.attr103 = attr103;
	}

	public String getAttr104() {
		return this.attr104;
	}

	public void setAttr104(String attr104) {
		this.attr104 = attr104;
	}

	public String getAttr105() {
		return this.attr105;
	}

	public void setAttr105(String attr105) {
		this.attr105 = attr105;
	}

	public String getAttr106() {
		return this.attr106;
	}

	public void setAttr106(String attr106) {
		this.attr106 = attr106;
	}

	public String getAttr107() {
		return this.attr107;
	}

	public void setAttr107(String attr107) {
		this.attr107 = attr107;
	}

	public String getAttr108() {
		return this.attr108;
	}

	public void setAttr108(String attr108) {
		this.attr108 = attr108;
	}

	public String getAttr109() {
		return this.attr109;
	}

	public void setAttr109(String attr109) {
		this.attr109 = attr109;
	}

	public String getAttr110() {
		return this.attr110;
	}

	public void setAttr110(String attr110) {
		this.attr110 = attr110;
	}

	public String getAttr111() {
		return this.attr111;
	}

	public void setAttr111(String attr111) {
		this.attr111 = attr111;
	}

	public String getAttr112() {
		return this.attr112;
	}

	public void setAttr112(String attr112) {
		this.attr112 = attr112;
	}

}
