package com.insigma.siis.local.business.entity;
// Generated 2019-5-15 15:20:26 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * Cxtj generated by hbm2java
 */
public class Cxtj implements java.io.Serializable {

	private String cxtj00;
	private BigDecimal cxtj01;
	private String cxtj02;
	private String cxtj03;
	private String cxtj04;
	private String cxtj05;
	private String cxtj06;
	private String cxtj07;
	private String cxtj08;
	private String fxyp00;
	private String cxtj09;

	public Cxtj() {
	}

	public Cxtj(String cxtj00) {
		this.cxtj00 = cxtj00;
	}

	public Cxtj(String cxtj00, BigDecimal cxtj01, String cxtj02, String cxtj03, String cxtj04, String cxtj05,
			String cxtj06, String cxtj07, String cxtj08, String fxyp00, String cxtj09) {
		this.cxtj00 = cxtj00;
		this.cxtj01 = cxtj01;
		this.cxtj02 = cxtj02;
		this.cxtj03 = cxtj03;
		this.cxtj04 = cxtj04;
		this.cxtj05 = cxtj05;
		this.cxtj06 = cxtj06;
		this.cxtj07 = cxtj07;
		this.cxtj08 = cxtj08;
		this.fxyp00 = fxyp00;
		this.cxtj09 = cxtj09;
	}

	public String getCxtj00() {
		return this.cxtj00;
	}

	public void setCxtj00(String cxtj00) {
		this.cxtj00 = cxtj00;
	}

	public BigDecimal getCxtj01() {
		return this.cxtj01;
	}

	public void setCxtj01(BigDecimal cxtj01) {
		this.cxtj01 = cxtj01;
	}

	public String getCxtj02() {
		return this.cxtj02;
	}

	public void setCxtj02(String cxtj02) {
		this.cxtj02 = cxtj02;
	}

	public String getCxtj03() {
		return this.cxtj03;
	}

	public void setCxtj03(String cxtj03) {
		this.cxtj03 = cxtj03;
	}

	public String getCxtj04() {
		return this.cxtj04;
	}

	public void setCxtj04(String cxtj04) {
		this.cxtj04 = cxtj04;
	}

	public String getCxtj05() {
		return this.cxtj05;
	}

	public void setCxtj05(String cxtj05) {
		this.cxtj05 = cxtj05;
	}

	public String getCxtj06() {
		return this.cxtj06;
	}

	public void setCxtj06(String cxtj06) {
		this.cxtj06 = cxtj06;
	}

	public String getCxtj07() {
		return this.cxtj07;
	}

	public void setCxtj07(String cxtj07) {
		this.cxtj07 = cxtj07;
	}

	public String getCxtj08() {
		return this.cxtj08;
	}

	public void setCxtj08(String cxtj08) {
		this.cxtj08 = cxtj08;
	}

	public String getFxyp00() {
		return this.fxyp00;
	}

	public void setFxyp00(String fxyp00) {
		this.fxyp00 = fxyp00;
	}

	public String getCxtj09() {
		return this.cxtj09;
	}

	public void setCxtj09(String cxtj09) {
		this.cxtj09 = cxtj09;
	}

}
