package com.insigma.siis.local.business.entity;
// Generated 2019-5-15 15:20:26 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Fxyp generated by hbm2java
 */
public class FxypSJFA implements java.io.Serializable {

	private String fxyp00;
	private BigDecimal fxyp01;
	private String fxyp02;
	private String fxyp03;
	private Date fxyp04;
	private String fxyp05;
	private String fxyp06;
	private String fxyp07;
	private String a0200;
	public String getFxyp07() {
		return fxyp07;
	}

	public void setFxyp07(String fxyp07) {
		this.fxyp07 = fxyp07;
	}

	public String getA0200() {
		return a0200;
	}

	public void setA0200(String a0200) {
		this.a0200 = a0200;
	}

	private String b01id;
	private String mntp00;

	public String getFxyp06() {
		return fxyp06;
	}

	public void setFxyp06(String fxyp06) {
		this.fxyp06 = fxyp06;
	}

	public String getB01id() {
		return b01id;
	}

	public void setB01id(String b01id) {
		this.b01id = b01id;
	}

	public String getMntp00() {
		return mntp00;
	}

	public void setMntp00(String mntp00) {
		this.mntp00 = mntp00;
	}

	public FxypSJFA() {
	}

	public FxypSJFA(String fxyp00) {
		this.fxyp00 = fxyp00;
	}

	public FxypSJFA(String fxyp00, BigDecimal fxyp01, String fxyp02, String fxyp03, Date fxyp04, String fxyp05) {
		this.fxyp00 = fxyp00;
		this.fxyp01 = fxyp01;
		this.fxyp02 = fxyp02;
		this.fxyp03 = fxyp03;
		this.fxyp04 = fxyp04;
		this.fxyp05 = fxyp05;
	}

	public String getFxyp00() {
		return this.fxyp00;
	}

	public void setFxyp00(String fxyp00) {
		this.fxyp00 = fxyp00;
	}

	public BigDecimal getFxyp01() {
		return this.fxyp01;
	}

	public void setFxyp01(BigDecimal fxyp01) {
		this.fxyp01 = fxyp01;
	}

	public String getFxyp02() {
		return this.fxyp02;
	}

	public void setFxyp02(String fxyp02) {
		this.fxyp02 = fxyp02;
	}

	public String getFxyp03() {
		return this.fxyp03;
	}

	public void setFxyp03(String fxyp03) {
		this.fxyp03 = fxyp03;
	}

	public Date getFxyp04() {
		return this.fxyp04;
	}

	public void setFxyp04(Date fxyp04) {
		this.fxyp04 = fxyp04;
	}

	public String getFxyp05() {
		return this.fxyp05;
	}

	public void setFxyp05(String fxyp05) {
		this.fxyp05 = fxyp05;
	}

}
