package com.insigma.siis.local.business.entity;

import java.math.BigDecimal;

// default package
// Generated 2018-8-17 10:54:54 by Hibernate Tools 3.2.2.GA

/**
 * RecordBatch generated by hbm2java
 */
public class FxypBatch implements java.io.Serializable {
	private String fyUpdated;
	public String getFyUpdated() {
		return fyUpdated;
	}

	public void setFyUpdated(String fyUpdated) {
		this.fyUpdated = fyUpdated;
	}

	private String fyOrg;
	private String fyApplicant;
	private String fyNo;
	private BigDecimal fySysno;
	public BigDecimal getFySysno() {
		return fySysno;
	}

	public void setFySysno(BigDecimal fySysno) {
		this.fySysno = fySysno;
	}

	public String getFyOrg() {
		return fyOrg;
	}

	public void setFyOrg(String fyOrg) {
		this.fyOrg = fyOrg;
	}

	public String getFyApplicant() {
		return fyApplicant;
	}

	public void setFyApplicant(String fyApplicant) {
		this.fyApplicant = fyApplicant;
	}

	public String getFyNo() {
		return fyNo;
	}

	public void setFyNo(String fyNo) {
		this.fyNo = fyNo;
	}

	private String fyId;
	private String fyName;
	private String fyDate;
	private String fyType;
	private String fyUserid;

	public FxypBatch() {
	}

	public FxypBatch(String fyId) {
		this.fyId = fyId;
	}

	public FxypBatch(String fyId, String fyName, String fyDate, String fyType, String fyUserid) {
		this.fyId = fyId;
		this.fyName = fyName;
		this.fyDate = fyDate;
		this.fyType = fyType;
		this.fyUserid = fyUserid;
	}

	public String getFyId() {
		return this.fyId;
	}

	public void setFyId(String fyId) {
		this.fyId = fyId;
	}

	public String getFyName() {
		return this.fyName;
	}

	public void setFyName(String fyName) {
		this.fyName = fyName;
	}

	public String getFyDate() {
		return this.fyDate;
	}

	public void setFyDate(String fyDate) {
		this.fyDate = fyDate;
	}

	public String getFyType() {
		return this.fyType;
	}

	public void setFyType(String fyType) {
		this.fyType = fyType;
	}

	public String getFyUserid() {
		return this.fyUserid;
	}

	public void setFyUserid(String fyUserid) {
		this.fyUserid = fyUserid;
	}

	private String fymeettype;
	
	private String fydeplytype;
	public String getFymeettype() {
		return fymeettype;
	}

	public void setFymeettype(String fymeettype) {
		this.fymeettype = fymeettype;
	}

	public String getFydeplytype() {
		return fydeplytype;
	}

	public void setFydeplytype(String fydeplytype) {
		this.fydeplytype = fydeplytype;
	}
	
	private String fyapprove;
	private String fyreportreson;
	private String fyreportvalue;
	public String getFyapprove() {
		return fyapprove;
	}

	public void setFyapprove(String fyapprove) {
		this.fyapprove = fyapprove;
	}

	public String getFyreportreson() {
		return fyreportreson;
	}

	public void setFyreportreson(String fyreportreson) {
		this.fyreportreson = fyreportreson;
	}

	public String getFyreportvalue() {
		return fyreportvalue;
	}

	public void setFyreportvalue(String fyreportvalue) {
		this.fyreportvalue = fyreportvalue;
	}
	
	private String fyleadview;
	public String getFyleadview() {
		return fyleadview;
	}

	public void setFyleadview(String fyleadview) {
		this.fyleadview = fyleadview;
	}
	
	private String fystatus;
	public String getFystatus() {
		return fystatus;
	}

	public void setFystatus(String fystatus) {
		this.fystatus = fystatus;
	}
	private String fymId;
	private String fymStatus;
	public String getFymId() {
		return fymId;
	}

	public String getFymStatus() {
		return fymStatus;
	}

	public void setFymId(String fymId) {
		this.fymId = fymId;
	}

	public void setFymStatus(String fymStatus) {
		this.fymStatus = fymStatus;
	}
	
}
