package com.insigma.siis.local.business.entity;
// Generated 2019-3-5 17:12:16 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Js2Yntp generated by hbm2java
 */
public class HzJs2Yntp implements java.io.Serializable {

	private String ynId;
	private String ynName;
	private String ynType;
	private String ynUserid;
	private String ynOrg;
	private BigDecimal ynSysno;
	private Timestamp ynDate;

	public HzJs2Yntp() {
	}

	public HzJs2Yntp(String ynId) {
		this.ynId = ynId;
	}

	public HzJs2Yntp(String ynId, String ynName, String ynType, String ynUserid, String ynOrg, BigDecimal ynSysno,
			Timestamp ynDate) {
		this.ynId = ynId;
		this.ynName = ynName;
		this.ynType = ynType;
		this.ynUserid = ynUserid;
		this.ynOrg = ynOrg;
		this.ynSysno = ynSysno;
		this.ynDate = ynDate;
	}

	public String getYnId() {
		return this.ynId;
	}

	public void setYnId(String ynId) {
		this.ynId = ynId;
	}

	public String getYnName() {
		return this.ynName;
	}

	public void setYnName(String ynName) {
		this.ynName = ynName;
	}

	public String getYnType() {
		return this.ynType;
	}

	public void setYnType(String ynType) {
		this.ynType = ynType;
	}

	public String getYnUserid() {
		return this.ynUserid;
	}

	public void setYnUserid(String ynUserid) {
		this.ynUserid = ynUserid;
	}

	public String getYnOrg() {
		return this.ynOrg;
	}

	public void setYnOrg(String ynOrg) {
		this.ynOrg = ynOrg;
	}

	public BigDecimal getYnSysno() {
		return this.ynSysno;
	}

	public void setYnSysno(BigDecimal ynSysno) {
		this.ynSysno = ynSysno;
	}

	public Timestamp getYnDate() {
		return this.ynDate;
	}

	public void setYnDate(Timestamp ynDate) {
		this.ynDate = ynDate;
	}

}
