package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * Js01 generated by hbm2java
 */
public class Js01 implements java.io.Serializable {
	private String js0118;
	public String getJs0118() {
		return js0118;
	}

	public void setJs0118(String js0118) {
		this.js0118 = js0118;
	}

	private String js0117;
	public String getJs0117() {
		return js0117;
	}

	public void setJs0117(String js0117) {
		this.js0117 = js0117;
	}

	private String js0115;
	private String js0114;
	private String js0116;
	public String getJs0115() {
		return js0115;
	}

	public void setJs0115(String js0115) {
		this.js0115 = js0115;
	}

	public String getJs0116() {
		return js0116;
	}

	public void setJs0116(String js0116) {
		this.js0116 = js0116;
	}

	public String getJs0114() {
		return js0114;
	}

	public void setJs0114(String js0114) {
		this.js0114 = js0114;
	}

	private String js0100;
	private String a0000;
	private String dc001;
	private String rbId;
	

	private String js0102;
	private String js0103;
	private String js0104;
	private String js0105;
	private String js0106;
	private String js0107;
	private String js0108;
	private String js0109;
	private String js0110;
	private String js0111;
	private String js0112;
	private BigDecimal js0113;

	public Js01() {
	}

	public Js01(String js0100, String a0000, String dc001, String rbId) {
		this.js0100 = js0100;
		this.a0000 = a0000;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js01(String js0100, String a0000, String dc001, String rbId, String js0102, String js0103, String js0104,
			String js0105, String js0106, String js0107, String js0108, String js0109, String js0110, String js0111,
			String js0112, BigDecimal js0113) {
		this.js0100 = js0100;
		this.a0000 = a0000;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0102 = js0102;
		this.js0103 = js0103;
		this.js0104 = js0104;
		this.js0105 = js0105;
		this.js0106 = js0106;
		this.js0107 = js0107;
		this.js0108 = js0108;
		this.js0109 = js0109;
		this.js0110 = js0110;
		this.js0111 = js0111;
		this.js0112 = js0112;
		this.js0113 = js0113;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getA0000() {
		return this.a0000;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0102() {
		return this.js0102;
	}

	public void setJs0102(String js0102) {
		this.js0102 = js0102;
	}

	public String getJs0103() {
		return this.js0103;
	}

	public void setJs0103(String js0103) {
		this.js0103 = js0103;
	}

	public String getJs0104() {
		return this.js0104;
	}

	public void setJs0104(String js0104) {
		this.js0104 = js0104;
	}

	public String getJs0105() {
		return this.js0105;
	}

	public void setJs0105(String js0105) {
		this.js0105 = js0105;
	}

	public String getJs0106() {
		return this.js0106;
	}

	public void setJs0106(String js0106) {
		this.js0106 = js0106;
	}

	public String getJs0107() {
		return this.js0107;
	}

	public void setJs0107(String js0107) {
		this.js0107 = js0107;
	}

	public String getJs0108() {
		return this.js0108;
	}

	public void setJs0108(String js0108) {
		this.js0108 = js0108;
	}

	public String getJs0109() {
		return this.js0109;
	}

	public void setJs0109(String js0109) {
		this.js0109 = js0109;
	}

	public String getJs0110() {
		return this.js0110;
	}

	public void setJs0110(String js0110) {
		this.js0110 = js0110;
	}

	public String getJs0111() {
		return this.js0111;
	}

	public void setJs0111(String js0111) {
		this.js0111 = js0111;
	}

	public String getJs0112() {
		return this.js0112;
	}

	public void setJs0112(String js0112) {
		this.js0112 = js0112;
	}

	public BigDecimal getJs0113() {
		return this.js0113;
	}

	public void setJs0113(BigDecimal js0113) {
		this.js0113 = js0113;
	}
	
	private String js0120;
	public String getJs0120() {
		return js0120;
	}
	public void setJs0120(String js0120) {
		this.js0120 = js0120;
	}
	private String js0122;
	
	public String getJs0122() {
		return js0122;
	}

	public void setJs0122(String js0122) {
		this.js0122 = js0122;
	}
	
	private String js0121;
	public String getJs0121() {
		return js0121;
	}
	public void setJs0121(String js0121) {
		this.js0121 = js0121;
	}
	
	private String js0123;
	public String getJs0123() {
		return js0123;
	}
	public void setJs0123(String js0123) {
		this.js0123 = js0123;
	}
	
	private String js0111a;
	private String js0117a;
	public String getJs0111a() {
		return js0111a;
	}

	public String getJs0117a() {
		return js0117a;
	}

	public void setJs0111a(String js0111a) {
		this.js0111a = js0111a;
	}

	public void setJs0117a(String js0117a) {
		this.js0117a = js0117a;
	}
	
	private String js0124;
	
	public String getJs0124() {
		return js0124;
	}

	public void setJs0124(String js0124) {
		this.js0124 = js0124;
	}
	
}
