package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js02 generated by hbm2java
 */
public class Js02 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0202;
	private String js0203;
	private String js0204;
	private String js0205;
	private String js0206;
	private String js0207;
	
	private String js0208;
	private String js0209;
	private String js0210;

	private String js0211;
	
	public Js02() {
	}

	public Js02(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js02(String js0100, String dc001, String rbId, String js0202, String js0203, String js0204, String js0205,
			String js0206, String js0207) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0202 = js0202;
		this.js0203 = js0203;
		this.js0204 = js0204;
		this.js0205 = js0205;
		this.js0206 = js0206;
		this.js0207 = js0207;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0202() {
		return this.js0202;
	}

	public void setJs0202(String js0202) {
		this.js0202 = js0202;
	}

	public String getJs0203() {
		return this.js0203;
	}

	public void setJs0203(String js0203) {
		this.js0203 = js0203;
	}

	public String getJs0204() {
		return this.js0204;
	}

	public void setJs0204(String js0204) {
		this.js0204 = js0204;
	}

	public String getJs0205() {
		return this.js0205;
	}

	public void setJs0205(String js0205) {
		this.js0205 = js0205;
	}

	public String getJs0206() {
		return this.js0206;
	}

	public void setJs0206(String js0206) {
		this.js0206 = js0206;
	}

	public String getJs0207() {
		return this.js0207;
	}

	public void setJs0207(String js0207) {
		this.js0207 = js0207;
	}

	public String getJs0208() {
		return js0208;
	}

	public void setJs0208(String js0208) {
		this.js0208 = js0208;
	}

	public String getJs0209() {
		return js0209;
	}

	public void setJs0209(String js0209) {
		this.js0209 = js0209;
	}

	public String getJs0210() {
		return js0210;
	}

	public void setJs0210(String js0210) {
		this.js0210 = js0210;
	}

	public String getJs0211() {
		return js0211;
	}

	public void setJs0211(String js0211) {
		this.js0211 = js0211;
	}

	
	
}
