package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js03 generated by hbm2java
 */
public class Js03 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0302;
	private String js0303;
	private String js0304;
	private String js0305;
	private String js0306;
	private String js0307;
	private String js0308;
	private String js0309;
	private String js0310;
	private String js0311;

	public Js03() {
	}

	public Js03(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js03(String js0100, String dc001, String rbId, String js0302, String js0303, String js0304, String js0305,
			String js0306, String js0307, String js0308, String js0309, String js0310, String js0311) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0302 = js0302;
		this.js0303 = js0303;
		this.js0304 = js0304;
		this.js0305 = js0305;
		this.js0306 = js0306;
		this.js0307 = js0307;
		this.js0308 = js0308;
		this.js0309 = js0309;
		this.js0310 = js0310;
		this.js0311 = js0311;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0302() {
		return this.js0302;
	}

	public void setJs0302(String js0302) {
		this.js0302 = js0302;
	}

	public String getJs0303() {
		return this.js0303;
	}

	public void setJs0303(String js0303) {
		this.js0303 = js0303;
	}

	public String getJs0304() {
		return this.js0304;
	}

	public void setJs0304(String js0304) {
		this.js0304 = js0304;
	}

	public String getJs0305() {
		return this.js0305;
	}

	public void setJs0305(String js0305) {
		this.js0305 = js0305;
	}

	public String getJs0306() {
		return this.js0306;
	}

	public void setJs0306(String js0306) {
		this.js0306 = js0306;
	}

	public String getJs0307() {
		return this.js0307;
	}

	public void setJs0307(String js0307) {
		this.js0307 = js0307;
	}

	public String getJs0308() {
		return this.js0308;
	}

	public void setJs0308(String js0308) {
		this.js0308 = js0308;
	}

	public String getJs0309() {
		return this.js0309;
	}

	public void setJs0309(String js0309) {
		this.js0309 = js0309;
	}

	public String getJs0310() {
		return this.js0310;
	}

	public void setJs0310(String js0310) {
		this.js0310 = js0310;
	}

	public String getJs0311() {
		return this.js0311;
	}

	public void setJs0311(String js0311) {
		this.js0311 = js0311;
	}

}
