package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js04 generated by hbm2java
 */
public class Js04 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0402;
	private String js0403;

	public Js04() {
	}

	public Js04(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js04(String js0100, String dc001, String rbId, String js0402, String js0403) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0402 = js0402;
		this.js0403 = js0403;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0402() {
		return this.js0402;
	}

	public void setJs0402(String js0402) {
		this.js0402 = js0402;
	}

	public String getJs0403() {
		return this.js0403;
	}

	public void setJs0403(String js0403) {
		this.js0403 = js0403;
	}

}
