package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js05 generated by hbm2java
 */
public class Js05 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0502;
	private String js0503;
	private String js0504;
	private String js0505;
	private String js0506;
	private String js0507;
	private String js0508;
	private String js0509;
	private String js0510;
	private String js0511;
	private String js0512;
	private String js0513;
	private String js0514;
	private String js0515;
	private String js0516;
	private String js0517;
	private String js0518;
	private String js0519;
	private String js0520;
	private String js0521;

	public Js05() {
	}

	public Js05(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js05(String js0100, String dc001, String rbId, String js0502, String js0503, String js0504, String js0505,
			String js0506, String js0507, String js0508, String js0509, String js0510, String js0511, String js0512,
			String js0513, String js0514, String js0515, String js0516, String js0517, String js0518, String js0519,
			String js0520, String js0521) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0502 = js0502;
		this.js0503 = js0503;
		this.js0504 = js0504;
		this.js0505 = js0505;
		this.js0506 = js0506;
		this.js0507 = js0507;
		this.js0508 = js0508;
		this.js0509 = js0509;
		this.js0510 = js0510;
		this.js0511 = js0511;
		this.js0512 = js0512;
		this.js0513 = js0513;
		this.js0514 = js0514;
		this.js0515 = js0515;
		this.js0516 = js0516;
		this.js0517 = js0517;
		this.js0518 = js0518;
		this.js0519 = js0519;
		this.js0520 = js0520;
		this.js0521 = js0521;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0502() {
		return this.js0502;
	}

	public void setJs0502(String js0502) {
		this.js0502 = js0502;
	}

	public String getJs0503() {
		return this.js0503;
	}

	public void setJs0503(String js0503) {
		this.js0503 = js0503;
	}

	public String getJs0504() {
		return this.js0504;
	}

	public void setJs0504(String js0504) {
		this.js0504 = js0504;
	}

	public String getJs0505() {
		return this.js0505;
	}

	public void setJs0505(String js0505) {
		this.js0505 = js0505;
	}

	public String getJs0506() {
		return this.js0506;
	}

	public void setJs0506(String js0506) {
		this.js0506 = js0506;
	}

	public String getJs0507() {
		return this.js0507;
	}

	public void setJs0507(String js0507) {
		this.js0507 = js0507;
	}

	public String getJs0508() {
		return this.js0508;
	}

	public void setJs0508(String js0508) {
		this.js0508 = js0508;
	}

	public String getJs0509() {
		return this.js0509;
	}

	public void setJs0509(String js0509) {
		this.js0509 = js0509;
	}

	public String getJs0510() {
		return this.js0510;
	}

	public void setJs0510(String js0510) {
		this.js0510 = js0510;
	}

	public String getJs0511() {
		return this.js0511;
	}

	public void setJs0511(String js0511) {
		this.js0511 = js0511;
	}

	public String getJs0512() {
		return this.js0512;
	}

	public void setJs0512(String js0512) {
		this.js0512 = js0512;
	}

	public String getJs0513() {
		return this.js0513;
	}

	public void setJs0513(String js0513) {
		this.js0513 = js0513;
	}

	public String getJs0514() {
		return this.js0514;
	}

	public void setJs0514(String js0514) {
		this.js0514 = js0514;
	}

	public String getJs0515() {
		return this.js0515;
	}

	public void setJs0515(String js0515) {
		this.js0515 = js0515;
	}

	public String getJs0516() {
		return this.js0516;
	}

	public void setJs0516(String js0516) {
		this.js0516 = js0516;
	}

	public String getJs0517() {
		return this.js0517;
	}

	public void setJs0517(String js0517) {
		this.js0517 = js0517;
	}

	public String getJs0518() {
		return this.js0518;
	}

	public void setJs0518(String js0518) {
		this.js0518 = js0518;
	}

	public String getJs0519() {
		return this.js0519;
	}

	public void setJs0519(String js0519) {
		this.js0519 = js0519;
	}

	public String getJs0520() {
		return this.js0520;
	}

	public void setJs0520(String js0520) {
		this.js0520 = js0520;
	}

	public String getJs0521() {
		return this.js0521;
	}

	public void setJs0521(String js0521) {
		this.js0521 = js0521;
	}

}
