package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js06 generated by hbm2java
 */
public class Js06 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0602;
	private String js0603;
	private String js0604;
	private String js0605;

	public Js06() {
	}

	public Js06(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js06(String js0100, String dc001, String rbId, String js0602, String js0603, String js0604, String js0605) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0602 = js0602;
		this.js0603 = js0603;
		this.js0604 = js0604;
		this.js0605 = js0605;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0602() {
		return this.js0602;
	}

	public void setJs0602(String js0602) {
		this.js0602 = js0602;
	}

	public String getJs0603() {
		return this.js0603;
	}

	public void setJs0603(String js0603) {
		this.js0603 = js0603;
	}

	public String getJs0604() {
		return this.js0604;
	}

	public void setJs0604(String js0604) {
		this.js0604 = js0604;
	}

	public String getJs0605() {
		return this.js0605;
	}

	public void setJs0605(String js0605) {
		this.js0605 = js0605;
	}

}
