package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js07 generated by hbm2java
 */
public class Js07 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0702;
	private String js0703;
	private String js0704;
	private String js0705;
	private String js0706;
	private String js0707;
	private String js0708;
	private String js0709;
	private String js0710;
	private String js0711;
	private String js0712;

	public Js07() {
	}

	public Js07(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js07(String js0100, String dc001, String rbId, String js0702, String js0703, String js0704, String js0705,
			String js0706, String js0707, String js0708, String js0709, String js0710, String js0711, String js0712) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0702 = js0702;
		this.js0703 = js0703;
		this.js0704 = js0704;
		this.js0705 = js0705;
		this.js0706 = js0706;
		this.js0707 = js0707;
		this.js0708 = js0708;
		this.js0709 = js0709;
		this.js0710 = js0710;
		this.js0711 = js0711;
		this.js0712 = js0712;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0702() {
		return this.js0702;
	}

	public void setJs0702(String js0702) {
		this.js0702 = js0702;
	}

	public String getJs0703() {
		return this.js0703;
	}

	public void setJs0703(String js0703) {
		this.js0703 = js0703;
	}

	public String getJs0704() {
		return this.js0704;
	}

	public void setJs0704(String js0704) {
		this.js0704 = js0704;
	}

	public String getJs0705() {
		return this.js0705;
	}

	public void setJs0705(String js0705) {
		this.js0705 = js0705;
	}

	public String getJs0706() {
		return this.js0706;
	}

	public void setJs0706(String js0706) {
		this.js0706 = js0706;
	}

	public String getJs0707() {
		return this.js0707;
	}

	public void setJs0707(String js0707) {
		this.js0707 = js0707;
	}

	public String getJs0708() {
		return this.js0708;
	}

	public void setJs0708(String js0708) {
		this.js0708 = js0708;
	}

	public String getJs0709() {
		return this.js0709;
	}

	public void setJs0709(String js0709) {
		this.js0709 = js0709;
	}

	public String getJs0710() {
		return this.js0710;
	}

	public void setJs0710(String js0710) {
		this.js0710 = js0710;
	}

	public String getJs0711() {
		return this.js0711;
	}

	public void setJs0711(String js0711) {
		this.js0711 = js0711;
	}

	public String getJs0712() {
		return this.js0712;
	}

	public void setJs0712(String js0712) {
		this.js0712 = js0712;
	}

}
