package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:58:43 by Hibernate Tools 3.2.2.GA

/**
 * Js08 generated by hbm2java
 */
public class Js08 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0802;
	private String js0803;
	private String js0804;
	private String js0805;
	private String js0806;
	private String js0807;
	private String js0808;
	
	private String js0810;
	private String js0811;
	
	public Js08() {
	}

	public Js08(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js08(String js0100, String dc001, String rbId, String js0802, String js0803, String js0804, String js0805) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0802 = js0802;
		this.js0803 = js0803;
		this.js0804 = js0804;
		this.js0805 = js0805;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0802() {
		return this.js0802;
	}

	public void setJs0802(String js0802) {
		this.js0802 = js0802;
	}

	public String getJs0803() {
		return this.js0803;
	}

	public void setJs0803(String js0803) {
		this.js0803 = js0803;
	}

	public String getJs0804() {
		return this.js0804;
	}

	public void setJs0804(String js0804) {
		this.js0804 = js0804;
	}

	public String getJs0805() {
		return js0805;
	}

	public void setJs0805(String js0805) {
		this.js0805 = js0805;
	}

	public String getJs0806() {
		return js0806;
	}

	public void setJs0806(String js0806) {
		this.js0806 = js0806;
	}

	public String getJs0807() {
		return js0807;
	}

	public void setJs0807(String js0807) {
		this.js0807 = js0807;
	}

	public String getJs0808() {
		return js0808;
	}
	
	public void setJs0808(String js0808) {
		this.js0808 = js0808;
	}
	
	private String js0809;

	public String getJs0809() {
		return js0809;
	}

	public void setJs0809(String js0809) {
		this.js0809 = js0809;
	}

	public String getJs0810() {
		return js0810;
	}

	public void setJs0810(String js0810) {
		this.js0810 = js0810;
	}

	public String getJs0811() {
		return js0811;
	}

	public void setJs0811(String js0811) {
		this.js0811 = js0811;
	}
	
	
	
}
