package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js09 generated by hbm2java
 */
public class Js09 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js0902;
	private String js0903;
	private String js0904;
	private String js0905;
	private String js0906;

	public Js09() {
	}

	public Js09(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js09(String js0100, String dc001, String rbId, String js0902, String js0903, String js0904, String js0905,
			String js0906) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js0902 = js0902;
		this.js0903 = js0903;
		this.js0904 = js0904;
		this.js0905 = js0905;
		this.js0906 = js0906;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs0902() {
		return this.js0902;
	}

	public void setJs0902(String js0902) {
		this.js0902 = js0902;
	}

	public String getJs0903() {
		return this.js0903;
	}

	public void setJs0903(String js0903) {
		this.js0903 = js0903;
	}

	public String getJs0904() {
		return this.js0904;
	}

	public void setJs0904(String js0904) {
		this.js0904 = js0904;
	}

	public String getJs0905() {
		return this.js0905;
	}

	public void setJs0905(String js0905) {
		this.js0905 = js0905;
	}

	public String getJs0906() {
		return this.js0906;
	}

	public void setJs0906(String js0906) {
		this.js0906 = js0906;
	}

}
