package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js10 generated by hbm2java
 */
public class Js10 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js1002;
	private String js1003;
	private String js1004;

	public Js10() {
	}

	public Js10(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js10(String js0100, String dc001, String rbId, String js1002, String js1003, String js1004) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js1002 = js1002;
		this.js1003 = js1003;
		this.js1004 = js1004;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs1002() {
		return this.js1002;
	}

	public void setJs1002(String js1002) {
		this.js1002 = js1002;
	}

	public String getJs1003() {
		return this.js1003;
	}

	public void setJs1003(String js1003) {
		this.js1003 = js1003;
	}

	public String getJs1004() {
		return this.js1004;
	}

	public void setJs1004(String js1004) {
		this.js1004 = js1004;
	}

}
