package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js11 generated by hbm2java
 */
public class Js11 implements java.io.Serializable {

	private String js0100;
	private String dc001;
	private String rbId;
	private String js1102;
	private String js1103;
	private String js1104;
	private String js1105;
	private String js1106;

	public Js11() {
	}

	public Js11(String js0100, String dc001, String rbId) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js11(String js0100, String dc001, String rbId, String js1102, String js1103, String js1104, String js1105,
			String js1106) {
		this.js0100 = js0100;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js1102 = js1102;
		this.js1103 = js1103;
		this.js1104 = js1104;
		this.js1105 = js1105;
		this.js1106 = js1106;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs1102() {
		return this.js1102;
	}

	public void setJs1102(String js1102) {
		this.js1102 = js1102;
	}

	public String getJs1103() {
		return this.js1103;
	}

	public void setJs1103(String js1103) {
		this.js1103 = js1103;
	}

	public String getJs1104() {
		return this.js1104;
	}

	public void setJs1104(String js1104) {
		this.js1104 = js1104;
	}

	public String getJs1105() {
		return this.js1105;
	}

	public void setJs1105(String js1105) {
		this.js1105 = js1105;
	}

	public String getJs1106() {
		return this.js1106;
	}

	public void setJs1106(String js1106) {
		this.js1106 = js1106;
	}

}
