package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Js02 generated by hbm2java
 */
public class Js12 implements java.io.Serializable {

	private String js1200;
	private String dc001;
	private String rbId;
	private String js1201;
	private String js1202;
	private String js1203;
	private String js1204;
	private String js1205;
	private String js1206;
	private String js1207;
	private String js1208;
	private String js1209;
	private String js1210;
	private String js1211;
	private String js1212;
	private String js1213;
	private String js1214;

	public Js12() {
	}

	public Js12(String js1200, String dc001, String rbId) {
		this.js1200 = js1200;
		this.dc001 = dc001;
		this.rbId = rbId;
	}

	public Js12(String js1200, String dc001, String rbId, String js1201, String js1202, String js1203, String js1204,
			String js1205, String js1206, String js1207, String js1208, String js1209, String js1210, String js1211, 
			String js1212, String js1213,String js1214) {
		this.js1200 = js1200;
		this.dc001 = dc001;
		this.rbId = rbId;
		this.js1201 = js1201;
		this.js1202 = js1202;
		this.js1203 = js1203;
		this.js1204 = js1204;
		this.js1205 = js1205;
		this.js1206 = js1206;
		this.js1207 = js1207;
		this.js1208 = js1208;
		this.js1209 = js1209;
		this.js1210 = js1210;
		this.js1211 = js1211;
		this.js1212 = js1212;
		this.js1213 = js1213;
		this.js1214 = js1214;
	}

	public String getJs1214() {
		return js1214;
	}

	public void setJs1214(String js1214) {
		this.js1214 = js1214;
	}

	public String getJs1200() {
		return this.js1200;
	}

	public void setJs1200(String js1200) {
		this.js1200 = js1200;
	}

	public String getDc001() {
		return this.dc001;
	}

	public void setDc001(String dc001) {
		this.dc001 = dc001;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs1201() {
		return js1201;
	}

	public void setJs1201(String js1201) {
		this.js1201 = js1201;
	}

	public String getJs1202() {
		return js1202;
	}

	public void setJs1202(String js1202) {
		this.js1202 = js1202;
	}

	public String getJs1203() {
		return js1203;
	}

	public void setJs1203(String js1203) {
		this.js1203 = js1203;
	}

	public String getJs1204() {
		return js1204;
	}

	public void setJs1204(String js1204) {
		this.js1204 = js1204;
	}

	public String getJs1205() {
		return js1205;
	}

	public void setJs1205(String js1205) {
		this.js1205 = js1205;
	}

	public String getJs1206() {
		return js1206;
	}

	public void setJs1206(String js1206) {
		this.js1206 = js1206;
	}

	public String getJs1207() {
		return js1207;
	}

	public void setJs1207(String js1207) {
		this.js1207 = js1207;
	}

	public String getJs1208() {
		return js1208;
	}

	public void setJs1208(String js1208) {
		this.js1208 = js1208;
	}

	public String getJs1209() {
		return js1209;
	}

	public void setJs1209(String js1209) {
		this.js1209 = js1209;
	}

	public String getJs1210() {
		return js1210;
	}

	public void setJs1210(String js1210) {
		this.js1210 = js1210;
	}

	public String getJs1211() {
		return js1211;
	}

	public void setJs1211(String js1211) {
		this.js1211 = js1211;
	}

	public String getJs1212() {
		return js1212;
	}

	public void setJs1212(String js1212) {
		this.js1212 = js1212;
	}

	public String getJs1213() {
		return js1213;
	}

	public void setJs1213(String js1213) {
		this.js1213 = js1213;
	}



}
