package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;

/**
 * Js02 generated by hbm2java
 */
public class Js13 implements Serializable {

	private String js1300;
	private String rbId;
	private String js1311;
	private String js1312;
	private String js1313;
	private String js1314;
	private String js1315;
	private String js1316;
	private String js1321;
	private String js1322;
	private String js1323;
	private String js1324;
	private String js1325;
	private String js1326;
	private String js1331;
	private String js1332;
	private String js1333;
	private String js1334;
	private String js1335;
	private String js1336;
	private String js1341;
	private String js1342;
	private String js1343;
	private String js1344;
	private String js1345;
	private String js1346;
	private String js1351;
	private String js1352;
	private String js1353;
	private String js1354;
	private String js1355;
	private String js1356;
	private String js1361;
	private String js1362;
	private String js1363;
	private String js1364;
	private String js1365;
	private String js1366;
	private String js1395;
	private String js1396;
	private String js1397;
	private String js1398;


	// --------------------------------------- get and set --------------------------------------- //

	public String getJs1300() {
		return js1300;
	}

	public void setJs1300(String js1300) {
		this.js1300 = js1300;
	}

	public String getRbId() {
		return rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJs1311() {
		return js1311;
	}

	public void setJs1311(String js1311) {
		this.js1311 = js1311;
	}

	public String getJs1312() {
		return js1312;
	}

	public void setJs1312(String js1312) {
		this.js1312 = js1312;
	}

	public String getJs1313() {
		return js1313;
	}

	public void setJs1313(String js1313) {
		this.js1313 = js1313;
	}

	public String getJs1314() {
		return js1314;
	}

	public void setJs1314(String js1314) {
		this.js1314 = js1314;
	}

	public String getJs1315() {
		return js1315;
	}

	public void setJs1315(String js1315) {
		this.js1315 = js1315;
	}

	public String getJs1316() {
		return js1316;
	}

	public void setJs1316(String js1316) {
		this.js1316 = js1316;
	}

	public String getJs1321() {
		return js1321;
	}

	public void setJs1321(String js1321) {
		this.js1321 = js1321;
	}

	public String getJs1322() {
		return js1322;
	}

	public void setJs1322(String js1322) {
		this.js1322 = js1322;
	}

	public String getJs1323() {
		return js1323;
	}

	public void setJs1323(String js1323) {
		this.js1323 = js1323;
	}

	public String getJs1324() {
		return js1324;
	}

	public void setJs1324(String js1324) {
		this.js1324 = js1324;
	}

	public String getJs1325() {
		return js1325;
	}

	public void setJs1325(String js1325) {
		this.js1325 = js1325;
	}

	public String getJs1326() {
		return js1326;
	}

	public void setJs1326(String js1326) {
		this.js1326 = js1326;
	}

	public String getJs1331() {
		return js1331;
	}

	public void setJs1331(String js1331) {
		this.js1331 = js1331;
	}

	public String getJs1332() {
		return js1332;
	}

	public void setJs1332(String js1332) {
		this.js1332 = js1332;
	}

	public String getJs1333() {
		return js1333;
	}

	public void setJs1333(String js1333) {
		this.js1333 = js1333;
	}

	public String getJs1334() {
		return js1334;
	}

	public void setJs1334(String js1334) {
		this.js1334 = js1334;
	}

	public String getJs1335() {
		return js1335;
	}

	public void setJs1335(String js1335) {
		this.js1335 = js1335;
	}

	public String getJs1336() {
		return js1336;
	}

	public void setJs1336(String js1336) {
		this.js1336 = js1336;
	}

	public String getJs1341() {
		return js1341;
	}

	public void setJs1341(String js1341) {
		this.js1341 = js1341;
	}

	public String getJs1342() {
		return js1342;
	}

	public void setJs1342(String js1342) {
		this.js1342 = js1342;
	}

	public String getJs1343() {
		return js1343;
	}

	public void setJs1343(String js1343) {
		this.js1343 = js1343;
	}

	public String getJs1344() {
		return js1344;
	}

	public void setJs1344(String js1344) {
		this.js1344 = js1344;
	}

	public String getJs1345() {
		return js1345;
	}

	public void setJs1345(String js1345) {
		this.js1345 = js1345;
	}

	public String getJs1346() {
		return js1346;
	}

	public void setJs1346(String js1346) {
		this.js1346 = js1346;
	}

	public String getJs1351() {
		return js1351;
	}

	public void setJs1351(String js1351) {
		this.js1351 = js1351;
	}

	public String getJs1352() {
		return js1352;
	}

	public void setJs1352(String js1352) {
		this.js1352 = js1352;
	}

	public String getJs1353() {
		return js1353;
	}

	public void setJs1353(String js1353) {
		this.js1353 = js1353;
	}

	public String getJs1354() {
		return js1354;
	}

	public void setJs1354(String js1354) {
		this.js1354 = js1354;
	}

	public String getJs1355() {
		return js1355;
	}

	public void setJs1355(String js1355) {
		this.js1355 = js1355;
	}

	public String getJs1356() {
		return js1356;
	}

	public void setJs1356(String js1356) {
		this.js1356 = js1356;
	}

	public String getJs1361() {
		return js1361;
	}

	public void setJs1361(String js1361) {
		this.js1361 = js1361;
	}

	public String getJs1362() {
		return js1362;
	}

	public void setJs1362(String js1362) {
		this.js1362 = js1362;
	}

	public String getJs1363() {
		return js1363;
	}

	public void setJs1363(String js1363) {
		this.js1363 = js1363;
	}

	public String getJs1364() {
		return js1364;
	}

	public void setJs1364(String js1364) {
		this.js1364 = js1364;
	}

	public String getJs1365() {
		return js1365;
	}

	public void setJs1365(String js1365) {
		this.js1365 = js1365;
	}

	public String getJs1366() {
		return js1366;
	}

	public void setJs1366(String js1366) {
		this.js1366 = js1366;
	}

	public String getJs1395() {
		return js1395;
	}

	public void setJs1395(String js1395) {
		this.js1395 = js1395;
	}

	public String getJs1396() {
		return js1396;
	}

	public void setJs1396(String js1396) {
		this.js1396 = js1396;
	}

	public String getJs1397() {
		return js1397;
	}

	public void setJs1397(String js1397) {
		this.js1397 = js1397;
	}

	public String getJs1398() {
		return js1398;
	}

	public void setJs1398(String js1398) {
		this.js1398 = js1398;
	}
}
