package com.insigma.siis.local.business.entity;
// Generated 2019-3-5 17:12:16 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Js2Yntp generated by hbm2java
 */
public class Js2Yntp implements java.io.Serializable {

	/**
	 * 邹志林2019-08-12
	 *  酝酿批次表
	 */
	private static final long serialVersionUID = 1L;
	private String ynId;								//酝酿ID		
	private String ynName;						//酝酿名称
	private String ynType;							//调配表类型
	private String ynUserid;						//用户id
	private String ynOrg;							//用户所属机构
	private BigDecimal ynSysno;				//默认排序号
	private Timestamp ynDate;					//酝酿登记时间
	private String tbUnit;							//填报处室
	private String calAgeYear;					//截止计算年龄时间
	
	/**
	 * 获得截止计算年龄时间
	 * @return
	 */
	public String getCalAgeYear() {
		return calAgeYear;
	}
	/**
	 * 设置截止计算年龄时间
	 * @return
	 */
	public void setCalAgeYear(String calAgeYear) {
		this.calAgeYear = calAgeYear;
	}

	/**
	 * 获得填报单位【处室】
	 * @return
	 */
	public String getTbUnit() {
		return tbUnit;
	}

	/**
	 * 设置填报单位【处室】
	 * @return
	 */
	public void setTbUnit(String tbUnit) {
		this.tbUnit = tbUnit;
	}

	/***
	 * 构造函数
	 */
	public Js2Yntp() {
	}

	/***
	 * 带参构造函数
	 * @param ynId 酝酿ID
	 */
	public Js2Yntp(String ynId) {
		this.ynId = ynId;
	}

	/***
	 * 带参构造函数
	 * @param ynId 酝酿ID
	 * @param ynName 酝酿名称
	 * @param ynType 调配表类型
	 * @param ynUserid 用户id
	 * @param ynOrg 用户所属机构
	 * @param ynSysno 默认排序号
	 * @param ynDate 酝酿登记时间
	 */
	public Js2Yntp(String ynId, String ynName, String ynType, String ynUserid, String ynOrg, BigDecimal ynSysno,
			Timestamp ynDate) {
		this.ynId = ynId;
		this.ynName = ynName;
		this.ynType = ynType;
		this.ynUserid = ynUserid;
		this.ynOrg = ynOrg;
		this.ynSysno = ynSysno;
		this.ynDate = ynDate;
	}

	/***
	 * 得到酝酿ID
	 * @return
	 */
	public String getYnId() {
		return this.ynId;
	}

	/***
	 * 设置酝酿ID
	 * @param ynId
	 */
	public void setYnId(String ynId) {
		this.ynId = ynId;
	}

	/**
	 * 得到酝酿名称
	 * @return
	 */
	public String getYnName() {
		return this.ynName;
	}

	/***
	 * 设置酝酿名称
	 * @param ynName
	 */
	public void setYnName(String ynName) {
		this.ynName = ynName;
	}

	/***
	 * 设置酝酿类型
	 * @return
	 */
	public String getYnType() {
		return this.ynType;
	}

	/****
	 * 取得酝酿类型
	 * @param ynType
	 */
	public void setYnType(String ynType) {
		this.ynType = ynType;
	}

	/***
	 * 得到共享用户
	 * @return
	 */
	public String getYnUserid() {
		return this.ynUserid;
	}

	/***
	 * 设置共享用户
	 * @param ynUserid
	 */
	public void setYnUserid(String ynUserid) {
		this.ynUserid = ynUserid;
	}

	/***
	 * 得到用户所属机构
	 * @return
	 */
	public String getYnOrg() {
		return this.ynOrg;
	}

	/**
	 * 设置用户所属机构
	 * @param ynOrg
	 */
	public void setYnOrg(String ynOrg) {
		this.ynOrg = ynOrg;
	}

	/**
	 * 设置默认排序号
	 * @return
	 */
	public BigDecimal getYnSysno() {
		return this.ynSysno;
	}

	/***
	 * 获取默认排序号
	 * @param ynSysno
	 */
	public void setYnSysno(BigDecimal ynSysno) {
		this.ynSysno = ynSysno;
	}

	/***
	 * 获取酝酿日期
	 * @return
	 */
	public Timestamp getYnDate() {
		return this.ynDate;
	}
	/***
	 * 设置酝酿日期
	 * @return
	 */
	public void setYnDate(Timestamp ynDate) {
		this.ynDate = ynDate;
	}

}
