package com.insigma.siis.local.business.entity;

import java.math.BigDecimal;

// default package
// Generated 2018-8-17 10:54:54 by Hibernate Tools 3.2.2.GA

/**
 * RecordBatch generated by hbm2java
 */
public class RecordBatch implements java.io.Serializable {
	private String rbUpdated;
	public String getRbUpdated() {
		return rbUpdated;
	}

	public void setRbUpdated(String rbUpdated) {
		this.rbUpdated = rbUpdated;
	}

	private String rbOrg;
	private String rbApplicant;
	private String rbNo;
	private BigDecimal rbSysno;
	public BigDecimal getRbSysno() {
		return rbSysno;
	}

	public void setRbSysno(BigDecimal rbSysno) {
		this.rbSysno = rbSysno;
	}

	public String getRbOrg() {
		return rbOrg;
	}

	public void setRbOrg(String rbOrg) {
		this.rbOrg = rbOrg;
	}

	public String getRbApplicant() {
		return rbApplicant;
	}

	public void setRbApplicant(String rbApplicant) {
		this.rbApplicant = rbApplicant;
	}

	public String getRbNo() {
		return rbNo;
	}

	public void setRbNo(String rbNo) {
		this.rbNo = rbNo;
	}

	private String rbId;
	private String rbName;
	private String rbDate;
	private String rbType;
	private String rbUserid;

	public RecordBatch() {
	}

	public RecordBatch(String rbId) {
		this.rbId = rbId;
	}

	public RecordBatch(String rbId, String rbName, String rbDate, String rbType, String rbUserid) {
		this.rbId = rbId;
		this.rbName = rbName;
		this.rbDate = rbDate;
		this.rbType = rbType;
		this.rbUserid = rbUserid;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getRbName() {
		return this.rbName;
	}

	public void setRbName(String rbName) {
		this.rbName = rbName;
	}

	public String getRbDate() {
		return this.rbDate;
	}

	public void setRbDate(String rbDate) {
		this.rbDate = rbDate;
	}

	public String getRbType() {
		return this.rbType;
	}

	public void setRbType(String rbType) {
		this.rbType = rbType;
	}

	public String getRbUserid() {
		return this.rbUserid;
	}

	public void setRbUserid(String rbUserid) {
		this.rbUserid = rbUserid;
	}

	private String rbmeettype;
	
	private String rbdeplytype;
	public String getRbmeettype() {
		return rbmeettype;
	}

	public void setRbmeettype(String rbmeettype) {
		this.rbmeettype = rbmeettype;
	}

	public String getRbdeplytype() {
		return rbdeplytype;
	}

	public void setRbdeplytype(String rbdeplytype) {
		this.rbdeplytype = rbdeplytype;
	}
	
	private String rbapprove;
	private String rbreportreson;
	private String rbreportvalue;
	public String getRbapprove() {
		return rbapprove;
	}

	public void setRbapprove(String rbapprove) {
		this.rbapprove = rbapprove;
	}

	public String getRbreportreson() {
		return rbreportreson;
	}

	public void setRbreportreson(String rbreportreson) {
		this.rbreportreson = rbreportreson;
	}

	public String getRbreportvalue() {
		return rbreportvalue;
	}

	public void setRbreportvalue(String rbreportvalue) {
		this.rbreportvalue = rbreportvalue;
	}
	
	private String rbleadview;
	public String getRbleadview() {
		return rbleadview;
	}

	public void setRbleadview(String rbleadview) {
		this.rbleadview = rbleadview;
	}
	
	private String rbstatus;
	public String getRbstatus() {
		return rbstatus;
	}

	public void setRbstatus(String rbstatus) {
		this.rbstatus = rbstatus;
	}
	private String rbmId;
	private String rbmStatus;
	public String getRbmId() {
		return rbmId;
	}

	public String getRbmStatus() {
		return rbmStatus;
	}

	public void setRbmId(String rbmId) {
		this.rbmId = rbmId;
	}

	public void setRbmStatus(String rbmStatus) {
		this.rbmStatus = rbmStatus;
	}
	private String rbmDept;
	public String getRbmDept() {
		return rbmDept;
	}

	public void setRbmDept(String rbmDept) {
		this.rbmDept = rbmDept;
	}
}
