package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * Supervision generated by hbm2java
 */
public class Supervision implements java.io.Serializable {
	
	private String id;
	private String a0000;
	private String position;
	private String informationtype;	
	private String matter;
	private String startdate;
	private String dealorg;
	private String result;
	private String influencetime;
	private String filenumber;
	
	public Supervision() {
	}


	public Supervision(String id, String a0000, String position, String informationtype, String matter, 
			String startdate, String dealorg, String result, String influencetime, String filenumber) {
		this.setId(id);
		this.setA0000(a0000);
		this.setPosition(position);
		this.setInformationtype(informationtype);
		this.setMatter(matter);
		this.setStartdate(startdate);
		this.setDealorg(dealorg);
		this.setResult(result);
		this.setInfluencetime(influencetime);
		this.setFilenumber(filenumber);

	}


	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public String getA0000() {
		return a0000;
	}


	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}


	public String getPosition() {
		return position;
	}


	public void setPosition(String position) {
		this.position = position;
	}


	public String getInformationtype() {
		return informationtype;
	}


	public void setInformationtype(String informationtype) {
		this.informationtype = informationtype;
	}


	public String getMatter() {
		return matter;
	}


	public void setMatter(String matter) {
		this.matter = matter;
	}


	public String getStartdate() {
		return startdate;
	}


	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}


	public String getDealorg() {
		return dealorg;
	}


	public void setDealorg(String dealorg) {
		this.dealorg = dealorg;
	}


	public String getResult() {
		return result;
	}


	public void setResult(String result) {
		this.result = result;
	}


	public String getInfluencetime() {
		return influencetime;
	}


	public void setInfluencetime(String influencetime) {
		this.influencetime = influencetime;
	}


	public String getFilenumber() {
		return filenumber;
	}


	public void setFilenumber(String filenumber) {
		this.filenumber = filenumber;
	}

	

}
