package com.insigma.siis.local.business.entity;
// Generated 2018-8-20 10:03:34 by Hibernate Tools 3.2.2.GA

/**
 * JsAtt generated by hbm2java
 */
public class TpbAtt implements java.io.Serializable {
	private String jsa08;
	public String getJsa08() {
		return jsa08;
	}

	public void setJsa08(String jsa08) {
		this.jsa08 = jsa08;
	}

	private String jsa00;
	private String js0100;
	private String rbId;
	private String jsa02;
	private String jsa03;
	private String jsa04;
	private String jsa05;
	private String jsa06;
	private String jsa07;

	public TpbAtt() {
	}

	public TpbAtt(String jsa00, String js0100, String rbId) {
		this.jsa00 = jsa00;
		this.js0100 = js0100;
		this.rbId = rbId;
	}

	public TpbAtt(String jsa00, String js0100, String rbId, String jsa02, String jsa03, String jsa04, String jsa05,
			String jsa06, String jsa07) {
		this.jsa00 = jsa00;
		this.js0100 = js0100;
		this.rbId = rbId;
		this.jsa02 = jsa02;
		this.jsa03 = jsa03;
		this.jsa04 = jsa04;
		this.jsa05 = jsa05;
		this.jsa06 = jsa06;
		this.jsa07 = jsa07;
	}

	public String getJsa00() {
		return this.jsa00;
	}

	public void setJsa00(String jsa00) {
		this.jsa00 = jsa00;
	}

	public String getJs0100() {
		return this.js0100;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}

	public String getRbId() {
		return this.rbId;
	}

	public void setRbId(String rbId) {
		this.rbId = rbId;
	}

	public String getJsa02() {
		return this.jsa02;
	}

	public void setJsa02(String jsa02) {
		this.jsa02 = jsa02;
	}

	public String getJsa03() {
		return this.jsa03;
	}

	public void setJsa03(String jsa03) {
		this.jsa03 = jsa03;
	}

	public String getJsa04() {
		return this.jsa04;
	}

	public void setJsa04(String jsa04) {
		this.jsa04 = jsa04;
	}

	public String getJsa05() {
		return this.jsa05;
	}

	public void setJsa05(String jsa05) {
		this.jsa05 = jsa05;
	}

	public String getJsa06() {
		return this.jsa06;
	}

	public void setJsa06(String jsa06) {
		this.jsa06 = jsa06;
	}

	public String getJsa07() {
		return this.jsa07;
	}

	public void setJsa07(String jsa07) {
		this.jsa07 = jsa07;
	}

}
