package com.insigma.siis.local.business.entity;

import java.io.Serializable;

/**
 * YJMX表实体类
 * Generated by the MappingUtil
 * 2019-03-14 16:40:50 520
 */
public class YJMX implements Serializable{

	private static final long serialVersionUID = 7407310646282839517L;

	/**
	 * 预警明细ID
	 */
	private String mx001;

	/**
	 * 人员ID
	 */
	private String a0000;

	/**
	 * 拟任免人选基本情况表ID
	 */
	private String js0100;

	/**
	 * 预警明细
	 */
	private String chinesename;

	/**
	 * 预警类型
	 */
	private String yjtype;
	
	public YJMX() {
		super();
	}
	
	public YJMX(String mx001,String a0000, String js0100, String chinesename, String yjtype) {
		super();
		this.mx001 = mx001;
		this.a0000 = a0000;
		this.js0100 = js0100;
		this.chinesename = chinesename;
		this.yjtype = yjtype;
	}


	public void setMx001(String mx001) {
		this.mx001 = mx001;
	}
	public String getMx001() {
		return mx001;
	}

	public void setA0000(String a0000) {
		this.a0000 = a0000;
	}
	public String getA0000() {
		return a0000;
	}

	public void setJs0100(String js0100) {
		this.js0100 = js0100;
	}
	public String getJs0100() {
		return js0100;
	}

	public void setChinesename(String chinesename) {
		this.chinesename = chinesename;
	}
	public String getChinesename() {
		return chinesename;
	}

	public void setYjtype(String yjtype) {
		this.yjtype = yjtype;
	}
	public String getYjtype() {
		return yjtype;
	}

	@Override
	public String toString() {
		return "YJMX [mx001=" + mx001 + ", a0000=" + a0000 + ", js0100="
				+ js0100 + ", chinesename=" + chinesename + ", yjtype="
				+ yjtype + "]";
	}
}